//! ARM Cortex-M33 / Thumb2 Code Generator
//!
//! Phase 5 backend for the RP2350 target.
//! Emits GNU ARM assembly (.s) compatible with arm-none-eabi-as.
//!
//! Pipeline:
//!   VPy AST (UnifiedModule)
//!     → generate_arm_asm()
//!     → game.s  (Thumb2 ASM)
//!     → arm-none-eabi-as game.s -o game.o
//!     → arm-none-eabi-ld game.o vectrex_hal.o -T rp2350.ld -o game.elf
//!     → arm-none-eabi-objcopy -O binary game.elf game.bin
//!     → flash_game.py game.bin
//!
//! Key differences from M6809 backend:
//!   - No BIOS — builtins write directly to VIA 6522 at 0xD000 via bus master
//!   - 32-bit registers (r0–r15): no A/B/D split, MUL/SDIV are single instructions
//!   - Calling convention: args in r0–r3, return in r0, callee saves r4–r11
//!   - Stack: full-descending (PUSH/POP), SP = r13
//!   - No bankswitching — 4MB flash, 512KB SRAM, all addressable
//!   - WAIT_RECAL = busy-wait on VIA Timer 1 via SPI/bus master

pub mod header;
pub mod ram_layout;
pub mod functions;
pub mod expressions;
pub mod builtins;
pub mod helpers;
pub mod assets;
pub mod drawing;
pub mod analysis;

use vpy_parser::Module;
use crate::AssetInfo;

/// Entry point: generate a complete Thumb2 .s file for the given module.
pub fn generate_arm_asm(
    module: &Module,
    title: &str,
    assets: &[AssetInfo],
) -> Result<String, String> {
    let mut asm = String::new();

    // File header comment
    asm.push_str(&format!(
        "@ VPy — ARM Thumb2 target (RP2350 / Cortex-M33)\n\
         @ Game: {}\n\
         @ Generated by vpy_codegen arm backend\n\
         @ Assemble with: arm-none-eabi-as -mthumb -mcpu=cortex-m33 game.s -o game.o\n\n",
        title
    ));

    // Thumb2 directive — all code is Thumb
    asm.push_str(".syntax unified\n");
    asm.push_str(".cpu cortex-m33\n");
    asm.push_str(".fpu fpv5-sp-d16\n");
    asm.push_str(".thumb\n\n");

    // RAM layout (EQU-style .equ directives)
    asm.push_str(& ram_layout::emit_ram_layout());

    // VIA register addresses (Vectrex hardware, accessed via bus master)
    asm.push_str(&emit_via_constants());

    // RP2350 SIO (single-cycle IO) for GPIO
    asm.push_str(&emit_sio_constants());

    // Game ROM section
    asm.push_str(".section .game_rom, \"ax\"\n");
    asm.push_str(".align 2\n\n");

    // RP2350 image definition (replaces Vectrex cartridge header)
    asm.push_str(&header::emit_image_def());

    // Usage analysis: emit runtime routines only when the program uses them.
    // Core stubs (bus_write/bus_read, vpy_wait_recal, vpy_set_intensity,
    // dv_reset/dv_move_to/dv_draw_delta) are always emitted.
    let usage = analysis::analyze(module);

    // Recordings (.vrec) are usage-filtered: only those referenced by a
    // DRAW_RECORDING("name", ...) call are emitted. Other asset types pass
    // through unchanged.
    let assets = assets::filter_recording_assets(assets, module);
    // Audio samples (.vsmp) are usage-filtered the same way: only those
    // referenced by a PLAY_SAMPLE("name") call are emitted.
    let assets = assets::filter_sample_assets(&assets, module);
    let assets = assets.as_slice();

    // Runtime helpers (bus_write / bus_read GPIO bit-bang + enemy runtime)
    asm.push_str(&helpers::emit_helpers(&usage));

    // Drawing engine (sin table, smul_lut, dv_move_to, draw_vector, draw_vector_3d)
    asm.push_str(&drawing::emit_drawing(&usage));

    // Builtin function implementations (DRAW_LINE, WAIT_RECAL, etc.)
    let msg_entries = builtins::collect_msg_entries(module);
    asm.push_str(&builtins::emit_builtins(&msg_entries, &usage));

    // User functions + main/loop
    asm.push_str(&functions::emit_functions(module, assets, &usage)?);

    // Asset data (vector draw lists, etc.)
    asm.push_str(&assets::emit_arm_assets(assets));

    // Post-process 1: peephole cleanup of the naive stack-machine output
    // (spill elision, compare→branch fusion). Runs on raw text before cbz
    // expansion so it sees the emitter's deterministic idioms intact.
    let asm = peephole(&asm);

    // Post-process 2: expand `cbz rN, label` to `cmp rN, #0; beq.w label`
    // cbz only works with low registers (r0-r7) and has ±252 byte range.
    // The wide beq.w form handles high registers and long-range branches.
    Ok(expand_cbz(&asm))
}

/// Normalise an instruction line for matching: strip any `@` comment and
/// collapse whitespace runs to single spaces. Label lines (`foo:`) survive
/// as `"foo:"`.
fn norm_code(line: &str) -> String {
    let no_comment = line.split('@').next().unwrap_or(line);
    no_comment.split_whitespace().collect::<Vec<_>>().join(" ")
}

/// If `code` is `push {rN}` or `pop {rN}` (single register), return the register.
fn single_reg(code: &str, op: &str) -> Option<String> {
    let rest = code.strip_prefix(op)?.trim();
    let inner = rest.strip_prefix('{')?.strip_suffix('}')?.trim();
    if inner.starts_with('r') && inner[1..].chars().all(|c| c.is_ascii_digit()) {
        Some(inner.to_string())
    } else {
        None
    }
}

/// The conditional branch mnemonics emitted by `bool_from_flags`.
fn is_cond_branch(mnem: &str) -> bool {
    matches!(mnem, "beq" | "bne" | "blt" | "bgt" | "ble" | "bge" | "bcs" | "bcc")
}

/// Peephole pass over the deterministic emitter output.
///
/// Collapses three idioms produced by the stack-machine codegen:
///  - P1/P2: operand-spill elision — `push {r0}; <eval right→r0>; mov r1,r0;
///    pop {r0}` becomes the right operand evaluated straight into r1, when the
///    right side is a leaf (immediate or single variable load).
///  - P3: adjacent no-op `push {rX}; pop {rX}` (single-arg call setup) is dropped.
///  - P4: `bool_from_flags` materialisation immediately consumed by a branch
///    (`... cmp r0,#0; beq TARGET`) fuses to a single conditional branch.
fn peephole(asm: &str) -> String {
    let lines: Vec<&str> = asm.lines().collect();
    let n = lines.len();
    let mut out: Vec<String> = Vec::with_capacity(n);
    let c = |i: usize| -> String { if i < n { norm_code(lines[i]) } else { String::new() } };

    let mut i = 0;
    while i < n {
        // --- P4: bool-materialise + branch fusion -------------------------
        // <cbranch> .LcfK / movs r0,#1 / b .LcfKe / .LcfK: / movs r0,#0 /
        // .LcfKe: / cmp r0,#0 / beq TARGET   →   <cbranch> TARGET
        if i + 7 < n {
            let head = c(i);
            let mut parts = head.split_whitespace();
            if let (Some(mnem), Some(lbl)) = (parts.next(), parts.next()) {
                if is_cond_branch(mnem)
                    && lbl.starts_with(".Lcf")
                    && parts.next().is_none()
                    && c(i + 1) == "movs r0, #1"
                    && c(i + 2) == format!("b {lbl}e")
                    && c(i + 3) == format!("{lbl}:")
                    && c(i + 4) == "movs r0, #0"
                    && c(i + 5) == format!("{lbl}e:")
                    && c(i + 6) == "cmp r0, #0"
                {
                    let tail = c(i + 7);
                    let mut tp = tail.split_whitespace();
                    if let (Some("beq"), Some(target)) = (tp.next(), tp.next()) {
                        if tp.next().is_none() {
                            out.push(format!("    {mnem:<7} {target}"));
                            i += 8;
                            continue;
                        }
                    }
                }
            }
        }

        // --- P3: adjacent no-op push/pop of the same register -------------
        if i + 1 < n {
            if let (Some(a), Some(b)) = (single_reg(&c(i), "push"), single_reg(&c(i + 1), "pop")) {
                if a == b {
                    i += 2;
                    continue;
                }
            }
        }

        // --- P1: immediate right operand spill ---------------------------
        // push {r0} / (mov r0,#N | ldr r0,=X) / mov r1,r0 / pop {r0}
        if i + 3 < n
            && c(i) == "push {r0}"
            && c(i + 2) == "mov r1, r0"
            && c(i + 3) == "pop {r0}"
        {
            let mid = c(i + 1);
            if let Some(imm) = mid.strip_prefix("mov r0, ") {
                out.push(format!("    mov     r1, {imm}"));
                i += 4;
                continue;
            }
            if let Some(imm) = mid.strip_prefix("ldr r0, ") {
                out.push(format!("    ldr     r1, {imm}"));
                i += 4;
                continue;
            }
        }

        // --- P2: single variable-load right operand spill ----------------
        // push {r0} / ldr r1,=ADDR / ldr r0,[r1] / mov r1,r0 / pop {r0}
        if i + 4 < n
            && c(i) == "push {r0}"
            && c(i + 1).starts_with("ldr r1, =")
            && c(i + 2) == "ldr r0, [r1]"
            && c(i + 3) == "mov r1, r0"
            && c(i + 4) == "pop {r0}"
        {
            out.push(lines[i + 1].to_string()); // keep `ldr r1, =ADDR  @ comment`
            out.push("    ldr     r1, [r1]".to_string());
            i += 5;
            continue;
        }

        out.push(lines[i].to_string());
        i += 1;
    }

    let mut result = out.join("\n");
    result.push('\n');
    result
}

/// Public re-export so the uvm2 backend can reuse the same post-processing.
pub fn expand_cbz_pub(asm: &str) -> String { expand_cbz(asm) }

/// Expand all `cbz rN, label` instructions to `cmp rN, #0` + `beq.w label`.
/// This handles:
/// - High registers (r8+): cbz only accepts r0-r7
/// - Long-range branches: cbz has max +252 byte forward range; beq.w has ±16MB
fn expand_cbz(asm: &str) -> String {
    let mut result = String::with_capacity(asm.len() + asm.len() / 8);
    for line in asm.lines() {
        let trimmed = line.trim_start();
        if trimmed.starts_with("cbz") {
            let rest = trimmed["cbz".len()..].trim_start();
            if let Some(comma_pos) = rest.find(',') {
                let reg = rest[..comma_pos].trim();
                let label = rest[comma_pos + 1..].trim();
                let indent = &line[..line.len() - trimmed.len()];
                result.push_str(&format!(
                    "{}cmp     {}, #0\n{}beq.w   {}\n",
                    indent, reg, indent, label
                ));
                continue;
            }
        }
        result.push_str(line);
        result.push('\n');
    }
    result
}

/// VIA 6522 register addresses as seen on the Vectrex bus.
/// The RP2350 accesses these via bus master mode (Phase 3 firmware).
/// These are the Vectrex bus addresses — the firmware translates them
/// to GPIO writes via bus::write(addr, data).
fn emit_via_constants() -> String {
    let mut s = String::from("@ --- VIA 6522 registers (Vectrex bus addresses) ---\n");
    s.push_str(".equ VIA_BASE,       0xD000\n");
    s.push_str(".equ VIA_PORT_B,     0xD000   @ Port B data (MUX, beam, z-pulse)\n");
    s.push_str(".equ VIA_PORT_A,     0xD001   @ Port A data (DAC / joystick)\n");
    s.push_str(".equ VIA_DDR_B,      0xD002   @ Port B direction\n");
    s.push_str(".equ VIA_DDR_A,      0xD003   @ Port A direction\n");
    s.push_str(".equ VIA_T1C_L,      0xD004   @ Timer 1 counter low\n");
    s.push_str(".equ VIA_T1C_H,      0xD005   @ Timer 1 counter high\n");
    s.push_str(".equ VIA_T1L_L,      0xD006   @ Timer 1 latch low\n");
    s.push_str(".equ VIA_T1L_H,      0xD007   @ Timer 1 latch high\n");
    s.push_str(".equ VIA_SR,         0xD00A   @ Shift register (beam on/off via CB2)\n");
    s.push_str(".equ VIA_ACR,        0xD00B   @ Auxiliary control register\n");
    s.push_str(".equ VIA_PCR,        0xD00C   @ Peripheral control register\n");
    s.push_str(".equ VIA_IFR,        0xD00D   @ Interrupt flag register\n");
    s.push_str(".equ VIA_IER,        0xD00E   @ Interrupt enable register\n");
    s.push_str("\n@ VIA Port B bits\n");
    s.push_str(".equ PB_MUX,         0x01     @ PSG BDIR (bit 0)\n");
    s.push_str(".equ PB_BEAM,        0x08     @ Beam on/off\n");
    s.push_str(".equ PB_ZPULSE,      0x10     @ Z-axis pulse\n");
    s.push_str("\n@ VIA ACR / PCR values\n");
    s.push_str(".equ ACR_SR_SHIFT,   0x18     @ SR = shift out under PHI2\n");
    s.push_str(".equ PCR_BEAM_OFF,   0xCE\n");
    s.push_str(".equ PCR_BEAM_ON,    0xDE\n");
    s.push_str(".equ T1_STANDARD,    0x7F     @ Timer 1 value for standard vector scale\n");
    s.push_str("\n");
    s
}

/// RP2350 SIO base address for GPIO bit-bang (bus master).
fn emit_sio_constants() -> String {
    let mut s = String::from("@ --- RP2350 SIO (GPIO bit-bang) ---\n");
    s.push_str(".equ SIO_BASE,       0xD0000000\n");
    s.push_str(".equ SIO_GPIO_OUT,   0xD0000010  @ GPIO output value\n");
    s.push_str(".equ SIO_GPIO_SET,   0xD0000014  @ GPIO output set (atomic)\n");
    s.push_str(".equ SIO_GPIO_CLR,   0xD0000018  @ GPIO output clear (atomic)\n");
    s.push_str(".equ SIO_GPIO_OE_SET,0xD0000024  @ GPIO OE set\n");
    s.push_str(".equ SIO_GPIO_OE_CLR,0xD0000028  @ GPIO OE clear\n");
    s.push_str(".equ SIO_GPIO_IN,    0xD0000004  @ GPIO input value\n");
    s.push_str("\n@ GPIO pin masks (from pins.rs)\n");
    s.push_str(".equ ADDR_MASK,      0x00007FFF  @ GP0-GP14 (A0-A14)\n");
    s.push_str(".equ DATA_MASK,      0x007F8000  @ GP15-GP22 (D0-D7)\n");
    s.push_str(".equ PIN_NCE,        23\n");
    s.push_str(".equ PIN_RW,         24\n");
    s.push_str(".equ PIN_NOE,        25\n");
    s.push_str(".equ PIN_NHALT,      27\n");
    s.push_str(".equ PIN_DIR_CTRL,   29\n");
    s.push_str("\n");
    s
}

#[cfg(test)]
mod peephole_tests {
    use super::peephole;

    /// P4: bool-materialise + `cmp r0,#0; beq TARGET` fuses to one branch.
    #[test]
    fn fuses_bool_block_into_branch() {
        let asm = "\
    cmp     r0, r1
    bne    .Lcf80
    movs    r0, #1
    b       .Lcf80e
.Lcf80:
    movs    r0, #0
.Lcf80e:
    cmp     r0, #0
    beq     while_end_83
";
        let out = peephole(asm);
        assert!(out.contains("bne     while_end_83"), "got:\n{out}");
        assert!(!out.contains(".Lcf80"), "bool block not removed:\n{out}");
        assert!(!out.contains("movs    r0, #1"), "materialise not removed:\n{out}");
    }

    /// P1: immediate right operand — spill push/pop elided into `mov r1,#N`.
    #[test]
    fn elides_immediate_operand_spill() {
        let asm = "\
    push    {r0}
    mov     r0, #8
    mov     r1, r0
    pop     {r0}
    cmp     r0, r1
";
        let out = peephole(asm);
        assert!(out.contains("mov     r1, #8"), "got:\n{out}");
        assert!(!out.contains("push"), "push not removed:\n{out}");
        assert!(!out.contains("pop"), "pop not removed:\n{out}");
    }

    /// P2: single variable-load right operand — spill elided, value into r1.
    #[test]
    fn elides_varload_operand_spill() {
        let asm = "\
    push    {r0}
    ldr     r1, =0x2007F6CC    @ ey
    ldr     r0, [r1]
    mov     r1, r0
    pop     {r0}
    cmp     r0, r1
";
        let out = peephole(asm);
        assert!(out.contains("ldr     r1, =0x2007F6CC"), "got:\n{out}");
        assert!(out.contains("ldr     r1, [r1]"), "value reload missing:\n{out}");
        assert!(!out.contains("push"), "push not removed:\n{out}");
        assert!(!out.contains("mov     r1, r0"), "spill move not removed:\n{out}");
    }

    /// P3: adjacent no-op `push {rX}; pop {rX}` is dropped.
    #[test]
    fn drops_adjacent_push_pop_noop() {
        let asm = "\
    ldr     r0, [r1]
    push    {r0}
    pop     {r0}
    bl      vpy_set_camera_y
";
        let out = peephole(asm);
        assert!(!out.contains("push"), "push not removed:\n{out}");
        assert!(!out.contains("pop"), "pop not removed:\n{out}");
        assert!(out.contains("bl      vpy_set_camera_y"), "surrounding code changed:\n{out}");
    }

    /// A bool block consumed by `and`/`or` (tail `b 2f`, not `cmp r0,#0`) is left intact.
    #[test]
    fn leaves_nonbranch_consumer_untouched() {
        let asm = "\
    beq    .Lcf5
    movs    r0, #1
    b       .Lcf5e
.Lcf5:
    movs    r0, #0
.Lcf5e:
    b       2f
";
        let out = peephole(asm);
        assert!(out.contains(".Lcf5"), "must not fuse without cmp/beq consumer:\n{out}");
        assert!(out.contains("movs    r0, #1"), "materialise wrongly removed:\n{out}");
    }

    /// Push/pop of different registers must NOT be treated as a no-op.
    #[test]
    fn keeps_mismatched_push_pop() {
        let asm = "\
    push    {r0}
    pop     {r1}
";
        let out = peephole(asm);
        assert!(out.contains("push    {r0}"), "got:\n{out}");
        assert!(out.contains("pop     {r1}"), "got:\n{out}");
    }
}
