//! ARM Cortex-M33 / Thumb2 Code Generator
//!
//! Phase 5 backend for the RP2350 target.
//! Emits GNU ARM assembly (.s) compatible with arm-none-eabi-as.
//!
//! Pipeline:
//!   VPy AST (UnifiedModule)
//!     → generate_arm_asm()
//!     → game.s  (Thumb2 ASM)
//!     → arm-none-eabi-as game.s -o game.o
//!     → arm-none-eabi-ld game.o vectrex_hal.o -T rp2350.ld -o game.elf
//!     → arm-none-eabi-objcopy -O binary game.elf game.bin
//!     → flash_game.py game.bin
//!
//! Key differences from M6809 backend:
//!   - No BIOS — builtins write directly to VIA 6522 at 0xD000 via bus master
//!   - 32-bit registers (r0–r15): no A/B/D split, MUL/SDIV are single instructions
//!   - Calling convention: args in r0–r3, return in r0, callee saves r4–r11
//!   - Stack: full-descending (PUSH/POP), SP = r13
//!   - No bankswitching — 4MB flash, 512KB SRAM, all addressable
//!   - WAIT_RECAL = busy-wait on VIA Timer 1 via SPI/bus master

pub mod header;
pub mod ram_layout;
pub mod functions;
pub mod expressions;
pub mod builtins;
pub mod helpers;
pub mod assets;
pub mod drawing;

use vpy_parser::Module;
use crate::AssetInfo;

/// Entry point: generate a complete Thumb2 .s file for the given module.
pub fn generate_arm_asm(
    module: &Module,
    title: &str,
    assets: &[AssetInfo],
) -> Result<String, String> {
    let mut asm = String::new();

    // File header comment
    asm.push_str(&format!(
        "@ VPy — ARM Thumb2 target (RP2350 / Cortex-M33)\n\
         @ Game: {}\n\
         @ Generated by vpy_codegen arm backend\n\
         @ Assemble with: arm-none-eabi-as -mthumb -mcpu=cortex-m33 game.s -o game.o\n\n",
        title
    ));

    // Thumb2 directive — all code is Thumb
    asm.push_str(".syntax unified\n");
    asm.push_str(".cpu cortex-m33\n");
    asm.push_str(".fpu fpv5-sp-d16\n");
    asm.push_str(".thumb\n\n");

    // RAM layout (EQU-style .equ directives)
    asm.push_str(& ram_layout::emit_ram_layout());

    // VIA register addresses (Vectrex hardware, accessed via bus master)
    asm.push_str(&emit_via_constants());

    // RP2350 SIO (single-cycle IO) for GPIO
    asm.push_str(&emit_sio_constants());

    // Game ROM section
    asm.push_str(".section .game_rom, \"ax\"\n");
    asm.push_str(".align 2\n\n");

    // RP2350 image definition (replaces Vectrex cartridge header)
    asm.push_str(&header::emit_image_def());

    // Runtime helpers (bus_write / bus_read GPIO bit-bang)
    asm.push_str(&helpers::emit_helpers());

    // Drawing engine (sin table, smul_lut, dv_move_to, draw_vector, draw_vector_3d)
    asm.push_str(&drawing::emit_drawing());

    // Builtin function implementations (DRAW_LINE, WAIT_RECAL, etc.)
    let msg_entries = builtins::collect_msg_entries(module);
    asm.push_str(&builtins::emit_builtins(&msg_entries));

    // User functions + main/loop
    asm.push_str(&functions::emit_functions(module, assets)?);

    // Asset data (vector draw lists, etc.)
    asm.push_str(&assets::emit_arm_assets(assets));

    Ok(asm)
}

/// VIA 6522 register addresses as seen on the Vectrex bus.
/// The RP2350 accesses these via bus master mode (Phase 3 firmware).
/// These are the Vectrex bus addresses — the firmware translates them
/// to GPIO writes via bus::write(addr, data).
fn emit_via_constants() -> String {
    let mut s = String::from("@ --- VIA 6522 registers (Vectrex bus addresses) ---\n");
    s.push_str(".equ VIA_BASE,       0xD000\n");
    s.push_str(".equ VIA_PORT_B,     0xD000   @ Port B data (MUX, beam, z-pulse)\n");
    s.push_str(".equ VIA_PORT_A,     0xD001   @ Port A data (DAC / joystick)\n");
    s.push_str(".equ VIA_DDR_B,      0xD002   @ Port B direction\n");
    s.push_str(".equ VIA_DDR_A,      0xD003   @ Port A direction\n");
    s.push_str(".equ VIA_T1C_L,      0xD004   @ Timer 1 counter low\n");
    s.push_str(".equ VIA_T1C_H,      0xD005   @ Timer 1 counter high\n");
    s.push_str(".equ VIA_T1L_L,      0xD006   @ Timer 1 latch low\n");
    s.push_str(".equ VIA_T1L_H,      0xD007   @ Timer 1 latch high\n");
    s.push_str(".equ VIA_SR,         0xD00A   @ Shift register (beam on/off via CB2)\n");
    s.push_str(".equ VIA_ACR,        0xD00B   @ Auxiliary control register\n");
    s.push_str(".equ VIA_PCR,        0xD00C   @ Peripheral control register\n");
    s.push_str(".equ VIA_IFR,        0xD00D   @ Interrupt flag register\n");
    s.push_str(".equ VIA_IER,        0xD00E   @ Interrupt enable register\n");
    s.push_str("\n@ VIA Port B bits\n");
    s.push_str(".equ PB_MUX,         0x01     @ PSG BDIR (bit 0)\n");
    s.push_str(".equ PB_BEAM,        0x08     @ Beam on/off\n");
    s.push_str(".equ PB_ZPULSE,      0x10     @ Z-axis pulse\n");
    s.push_str("\n@ VIA ACR / PCR values\n");
    s.push_str(".equ ACR_SR_SHIFT,   0x18     @ SR = shift out under PHI2\n");
    s.push_str(".equ PCR_BEAM_OFF,   0xCE\n");
    s.push_str(".equ PCR_BEAM_ON,    0xDE\n");
    s.push_str(".equ T1_STANDARD,    0x7F     @ Timer 1 value for standard vector scale\n");
    s.push_str("\n");
    s
}

/// RP2350 SIO base address for GPIO bit-bang (bus master).
fn emit_sio_constants() -> String {
    let mut s = String::from("@ --- RP2350 SIO (GPIO bit-bang) ---\n");
    s.push_str(".equ SIO_BASE,       0xD0000000\n");
    s.push_str(".equ SIO_GPIO_OUT,   0xD0000010  @ GPIO output value\n");
    s.push_str(".equ SIO_GPIO_SET,   0xD0000014  @ GPIO output set (atomic)\n");
    s.push_str(".equ SIO_GPIO_CLR,   0xD0000018  @ GPIO output clear (atomic)\n");
    s.push_str(".equ SIO_GPIO_OE_SET,0xD0000024  @ GPIO OE set\n");
    s.push_str(".equ SIO_GPIO_OE_CLR,0xD0000028  @ GPIO OE clear\n");
    s.push_str(".equ SIO_GPIO_IN,    0xD0000004  @ GPIO input value\n");
    s.push_str("\n@ GPIO pin masks (from pins.rs)\n");
    s.push_str(".equ ADDR_MASK,      0x00007FFF  @ GP0-GP14 (A0-A14)\n");
    s.push_str(".equ DATA_MASK,      0x007F8000  @ GP15-GP22 (D0-D7)\n");
    s.push_str(".equ PIN_NCE,        23\n");
    s.push_str(".equ PIN_RW,         24\n");
    s.push_str(".equ PIN_NOE,        25\n");
    s.push_str(".equ PIN_NHALT,      27\n");
    s.push_str(".equ PIN_DIR_CTRL,   29\n");
    s.push_str("\n");
    s
}
