/**
 * Thumb2.ts — ARM Cortex-M33 / Thumb2 CPU emulator.
 *
 * Implements the subset of Thumb2 instructions generated by the VPy ARM
 * codegen (functions.rs, expressions.rs, builtins.rs, helpers.rs, drawing.rs).
 *
 * Register file:
 *   r0-r12 : general purpose
 *   r13    : SP  (stack pointer)
 *   r14    : LR  (link register)
 *   r15    : PC  (program counter — points to current insn +4 during decode)
 *   CPSR   : N(31) Z(30) C(29) V(28)
 *   itState: IT-block state machine (1 byte)
 */

import type { ICpu } from '../interfaces/ICpu.js';
import type { IBus } from '../interfaces/IBus.js';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Force a JS number into the unsigned 32-bit range. */
function u32(n: number): number {
  return n >>> 0;
}

/** Sign-extend 32-bit: treat the Uint32Array slot as signed. */
function s32(n: number): number {
  return n | 0;
}

/** Rotate-right 32 bits. */
function ror32(val: number, shift: number): number {
  shift &= 31;
  if (shift === 0) return u32(val);
  return u32((val >>> shift) | (val << (32 - shift)));
}

/**
 * Decode the Thumb2 "modified immediate" 12-bit constant used in 32-bit
 * data-processing instructions.
 */
function decodeThumb2Imm(imm12: number): number {
  const imm8 = imm12 & 0xff;
  const rot8 = (imm12 >>> 8) & 0xf;  // bits [11:8] — used only for pattern 0-3
  if (rot8 === 0) return imm8;
  if (rot8 === 1) return u32((imm8 << 16) | imm8);
  if (rot8 === 2) return u32((imm8 << 24) | (imm8 << 8));
  if (rot8 === 3) return u32((imm8 << 24) | (imm8 << 16) | (imm8 << 8) | imm8);
  // Rotated form: ARM ISA uses 5-bit rotation imm12[11:7] and value = {1, imm12[6:0]}
  const rotAmt = (imm12 >>> 7) & 0x1f;
  const val    = 0x80 | (imm12 & 0x7f);
  return ror32(val, rotAmt);
}

// ---------------------------------------------------------------------------
// Thumb2 CPU
// ---------------------------------------------------------------------------

export class Thumb2 implements ICpu {
  // r0-r15 stored as unsigned 32-bit (Uint32Array enforces it automatically)
  private readonly regs: Uint32Array = new Uint32Array(16);

  /** CPSR: only N(31) Z(30) C(29) V(28) bits are maintained. */
  private cpsr: number = 0;

  /** IT-block state. 0 = not in an IT block. */
  private itState: number = 0;

  /** Accumulated cycle counter since reset(). */
  private _cycles: number = 0;

  /** Instruction-fetch fast path: a linear code region (the RAM/flash image) the
   * CPU can read directly, skipping the per-byte bus range-dispatch. Set by the
   * system after load. When PC is in [base, base+mem.length) the fetch reads the
   * array; otherwise it falls back to bus.read8. Data accesses always use the bus. */
  private _fetchMem: Uint8Array | null = null;
  private _fetchBase: number = 0;
  setFetchRegion(mem: Uint8Array | null, base: number): void {
    this._fetchMem = mem;
    this._fetchBase = base >>> 0;
  }

  /**
   * Set by exec of a WFI instruction; cleared by the outer run-loop at the
   * start of each frame.  The Rp2350System uses this as the frame-sync gate.
   */
  public hitWfi: boolean = false;

  // ─── Register aliases ──────────────────────────────────────────────────

  private get SP(): number { return this.regs[13]; }
  private set SP(v: number) { this.regs[13] = v; }

  private get LR(): number { return this.regs[14]; }
  private set LR(v: number) { this.regs[14] = v; }

  // PC points to current insn + 4 during execution (Thumb convention +4)
  private get PC(): number { return this.regs[15]; }
  private set PC(v: number) { this.regs[15] = v & ~1; }  // force Thumb bit off

  // ─── ICpu ─────────────────────────────────────────────────────────────

  reset(): void {
    this.regs.fill(0);
    this.cpsr = 0;
    this.itState = 0;
    this._cycles = 0;
    this.hitWfi = false;
  }

  get pc(): number { return this.regs[15]; }
  get cycles(): number { return this._cycles; }

  // ─── Register accessors (used by Rp2350System for trap handling) ──────

  /** Read general-purpose register n (0–15) as unsigned 32-bit. */
  getReg(n: number): number { return this.regs[n] >>> 0; }

  /** Write general-purpose register n (0–15). */
  setReg(n: number, v: number): void { this.regs[n] = v >>> 0; }

  irq(_line: number): void {
    // Interrupts not required for VPy emulation — treat as no-op.
  }

  /** Instruction counter for trace logging (first N instructions only). */
  private _stepCount: number = 0;

  step(bus: IBus): number {
    const pc = this.regs[15];
    // Fetch fast path: read the 16/32-bit instruction directly from the code
    // array when PC is inside it (RAM-linked games run from SRAM), avoiding 2–4
    // bus.read8 range-dispatch calls per instruction — the dominant cost for the
    // heavy Z80/6502 arcade cores.
    const fm = this._fetchMem;
    const foff = pc - this._fetchBase;
    const fast = fm !== null && foff >= 0 && (foff + 3) < fm.length;
    const hw0 = fast ? (fm![foff] | (fm![foff + 1] << 8))
                     : (bus.read8(pc) | (bus.read8(pc + 1) << 8));
    const is32 = (hw0 >>> 11) >= 0x1d;   // 32-bit when bits[15:11] >= 0b11101

    // IT-block conditioning applies to BOTH 16- and 32-bit instructions. It used
    // to live only in exec16(), so a 32-bit instruction inside an IT block (e.g.
    // gcc's `itete mi; addmi; addpl.w; strmi; addpl` for the 6502 branch macros)
    // ran unconditionally AND failed to advance the IT state — desynchronising
    // the remaining slots so a following conditional store was wrongly skipped
    // (BEQ/BNE etc. computed the branch target but never wrote it back).
    // Decide skip BEFORE executing, but advance the IT state AFTER, so that
    // inItBlock() stays true *during* the instruction — 16-bit ALU ops that
    // would set flags outside an IT block must NOT set them inside one, and they
    // check inItBlock() to decide (see setFlagsInIt()).
    const wasInIt = this.inItBlock();
    const itSkip = wasInIt && !this.itCondTrue();

    let cycles: number;
    if (itSkip) {
      this.regs[15] = pc + (is32 ? 4 : 2);
      cycles = 1;
    } else if (is32) {
      const hw1 = fast ? (fm![foff + 2] | (fm![foff + 3] << 8))
                       : (bus.read8(pc + 2) | (bus.read8(pc + 3) << 8));
      this.regs[15] = pc + 4;
      cycles = this.exec32(hw0, hw1, bus, pc);
    } else {
      this.regs[15] = pc + 2;
      cycles = this.exec16(hw0, bus, pc);
    }

    if (wasInIt) this.advanceIt();

    this._stepCount++;
    this._cycles += cycles;
    return cycles;
  }

  // ─── IT-block helpers ─────────────────────────────────────────────────

  private inItBlock(): boolean {
    return (this.itState & 0x0f) !== 0;
  }

  /**
   * Returns true when the current IT-conditioned instruction should execute.
   *
   * The advanceIt() shift encodes THEN/ELSE in the LSB of the condition code:
   *   - THEN slots keep the base condition (e.g. GT = 0xC, LSB=0)
   *   - ELSE slots shift to the inverse condition (e.g. LE = 0xD, LSB=1)
   *
   * condPasses(cond) correctly handles the odd/even pair:
   *   condPasses(0xC) = evalCond(GT)   → execute if GT is true (THEN)
   *   condPasses(0xD) = !evalCond(GT)  → execute if GT is false = LE (ELSE)
   *
   * evalCond(cond) alone uses (cond & 0xe) which strips the inversion bit,
   * so it would evaluate BOTH GT and LE as the same underlying GT condition —
   * causing ELSE slots to execute when GT is true instead of when it is false.
   */
  private itCondTrue(): boolean {
    const cond = (this.itState >>> 4) & 0xf;
    return this.condPasses(cond);
  }

  private advanceIt(): void {
    if ((this.itState & 0x07) === 0) {
      this.itState = 0;  // last instruction in block
    } else {
      this.itState = (this.itState & 0xe0) | ((this.itState << 1) & 0x1f);
    }
  }

  // ─── Flag helpers ─────────────────────────────────────────────────────

  private get flagN(): number { return (this.cpsr >>> 31) & 1; }
  private get flagZ(): number { return (this.cpsr >>> 30) & 1; }
  private get flagC(): number { return (this.cpsr >>> 29) & 1; }
  private get flagV(): number { return (this.cpsr >>> 28) & 1; }

  private setFlag(bit: number, val: boolean): void {
    if (val) this.cpsr |= (1 << bit);
    else     this.cpsr &= ~(1 << bit);
  }

  private setN(val: boolean): void { this.setFlag(31, val); }
  private setZ(val: boolean): void { this.setFlag(30, val); }
  private setC(val: boolean): void { this.setFlag(29, val); }
  private setV(val: boolean): void { this.setFlag(28, val); }

  // Flag updates for a *destination-writing* 16-bit ALU op (MOV/ADD/SUB/shift/
  // logical). In Thumb-1 these set flags OUTSIDE an IT block but NOT inside one
  // (the S is implicit only outside IT). Compares (CMP/CMN/TST) have no
  // destination and always set flags, so they keep calling setNZ/setNZCV_*.
  // step() advances the IT state AFTER the instruction, so inItBlock() is true
  // here for an in-block instruction.
  private nzIt(result: number): void { if (!this.inItBlock()) this.setNZ(result); }
  private addIt(a: number, b: number): void { if (!this.inItBlock()) this.setNZCV_add(a, b); }
  private subIt(a: number, b: number): void { if (!this.inItBlock()) this.setNZCV_sub(a, b); }

  private setNZ(result: number): void {
    const r = u32(result);
    this.setN((r >>> 31) === 1);
    this.setZ(r === 0);
  }

  /** Set all four flags after an addition: result32 = a + b (no carry-in). */
  private setNZCV_add(a: number, b: number): void {
    const a32 = u32(a);
    const b32 = u32(b);
    const r64 = a32 + b32;       // JavaScript: safe as float for 32-bit inputs
    const r32 = u32(r64);
    this.setN((r32 >>> 31) === 1);
    this.setZ(r32 === 0);
    this.setC(r64 > 0xffff_ffff);
    // Overflow: sign change when both inputs same sign but result differs
    const signA = (a32 >>> 31) & 1;
    const signB = (b32 >>> 31) & 1;
    const signR = (r32 >>> 31) & 1;
    this.setV(signA === signB && signR !== signA);
  }

  /** Set all four flags after a subtraction: result32 = a - b. */
  private setNZCV_sub(a: number, b: number): void {
    // a - b == a + NOT(b) + 1 (carry semantics)
    const a32 = u32(a);
    const b32 = u32(b);
    const nb32 = u32(~b32);
    const r64 = a32 + nb32 + 1;
    const r32 = u32(r64);
    this.setN((r32 >>> 31) === 1);
    this.setZ(r32 === 0);
    this.setC(r64 > 0xffff_ffff);  // borrow-out: C=1 means NO borrow
    const signA = (a32 >>> 31) & 1;
    const signB = (b32 >>> 31) & 1;
    const signR = (r32 >>> 31) & 1;
    this.setV(signA !== signB && signR !== signA);
  }

  // ─── Condition evaluation ─────────────────────────────────────────────

  private evalCond(cond: number): boolean {
    const N = this.flagN;
    const Z = this.flagZ;
    const C = this.flagC;
    const V = this.flagV;
    switch (cond & 0xe) {
      case 0x0: return Z === 1;             // EQ(0)/NE(1)
      case 0x2: return C === 1;             // CS(2)/CC(3)
      case 0x4: return N === 1;             // MI(4)/PL(5)
      case 0x6: return V === 1;             // VS(6)/VC(7)
      case 0x8: return C === 1 && Z === 0;  // HI(8)/LS(9)
      case 0xa: return N === V;             // GE(A)/LT(B)
      case 0xc: return N === V && Z === 0;  // GT(C)/LE(D)
      case 0xe: return true;                // AL(E)/—(F)
    }
    return false;
  }

  /** Return true if condition passes, accounting for the odd-numbered inverse. */
  private condPasses(cond: number): boolean {
    const base = this.evalCond(cond);
    return (cond & 1) ? !base : base;
  }

  // ─── Shift helpers ────────────────────────────────────────────────────

  private lsl(val: number, amount: number, updateC: boolean): number {
    if (amount === 0) return u32(val);
    if (amount >= 32) {
      if (updateC) this.setC(amount === 32 ? (val & 1) !== 0 : false);
      return 0;
    }
    if (updateC) this.setC(((val >>> (32 - amount)) & 1) !== 0);
    return u32(val << amount);
  }

  private lsr(val: number, amount: number, updateC: boolean): number {
    const v = u32(val);
    if (amount === 0) return v;
    if (amount >= 32) {
      if (updateC) this.setC(amount === 32 ? (v >>> 31) !== 0 : false);
      return 0;
    }
    if (updateC) this.setC(((v >>> (amount - 1)) & 1) !== 0);
    return v >>> amount;
  }

  private asr(val: number, amount: number, updateC: boolean): number {
    const v = s32(val);
    if (amount === 0) return u32(v);
    const shift = amount >= 32 ? 31 : amount;
    if (updateC) this.setC(((v >> (shift - 1)) & 1) !== 0);
    return u32(v >> shift);
  }

  private ror(val: number, amount: number, updateC: boolean): number {
    const v = u32(val);
    amount &= 31;
    if (amount === 0) {
      // RRX — not generated by VPy codegen, but handle gracefully
      return v;
    }
    const result = ror32(v, amount);
    if (updateC) this.setC((result >>> 31) !== 0);
    return result;
  }

  // ─── Memory helpers ───────────────────────────────────────────────────

  private read16(bus: IBus, addr: number): number {
    return bus.read8(addr) | (bus.read8(addr + 1) << 8);
  }

  private read32(bus: IBus, addr: number): number {
    return u32(bus.read8(addr)
      | (bus.read8(addr + 1) << 8)
      | (bus.read8(addr + 2) << 16)
      | (bus.read8(addr + 3) << 24));
  }

  private write16(bus: IBus, addr: number, val: number): void {
    bus.write8(addr,     val & 0xff);
    bus.write8(addr + 1, (val >>> 8) & 0xff);
  }

  private write32(bus: IBus, addr: number, val: number): void {
    const v = u32(val);
    bus.write8(addr,     v & 0xff);
    bus.write8(addr + 1, (v >>> 8)  & 0xff);
    bus.write8(addr + 2, (v >>> 16) & 0xff);
    bus.write8(addr + 3, (v >>> 24) & 0xff);
  }

  // ─── PUSH / POP helpers ───────────────────────────────────────────────

  private push32(bus: IBus, val: number): void {
    this.SP = u32(this.SP - 4);
    this.write32(bus, this.SP, val);
  }

  private pop32(bus: IBus): number {
    const v = this.read32(bus, this.SP);
    this.SP = u32(this.SP + 4);
    return v;
  }

  // =========================================================================
  // 16-bit instruction execution
  // =========================================================================

  private exec16(hw: number, bus: IBus, pc: number): number {
    // IT-block conditioning (skip + advance) is handled in step() for BOTH
    // 16- and 32-bit instructions, so exec16 no longer does it here.
    const op = (hw >>> 10) & 0x3f;   // bits[15:10]

    // ── Shift / Add / Sub / Move / Compare (bits[15:14] = 00 or 001) ──────
    if ((hw & 0xc000) === 0x0000) {
      // bits[15:13] = 000 → shifts
      // bits[15:13] = 001 → MOV/CMP/ADD/SUB imm8
      return this.exec16_shift_add(hw, pc);
    }

    // ── Data-processing (bits[15:10] = 010000) ────────────────────────────
    if (op === 0x10) {
      return this.exec16_alu(hw, pc);
    }

    // ── Hi-register / BX (bits[15:10] = 010001) ──────────────────────────
    if (op === 0x11) {
      return this.exec16_hireg(hw, bus, pc);
    }

    // ── LDR literal (bits[15:11] = 01001) ────────────────────────────────
    if ((hw >>> 11) === 0x09) {
      const rt   = (hw >>> 8) & 0x7;
      // PC is already +2 from the fetch; align down to 4-byte boundary +4
      // The spec says address = Align(PC,4) + imm8*4 where PC = insn_addr+4
      const base = (pc + 4) & ~3;
      const addr = base + ((hw & 0xff) << 2);
      this.regs[rt] = this.read32(bus, addr);
      return 2;
    }

    // ── Load/Store register offset (bits[15:12] = 0101) ──────────────────
    if ((hw >>> 12) === 0x5) {
      return this.exec16_ldst_reg(hw, bus);
    }

    // ── Load/Store immediate offset (bits[15:13] = 011) ──────────────────
    if ((hw & 0xe000) === 0x6000) {
      return this.exec16_ldst_imm(hw, bus);
    }

    // ── Load/Store halfword (bits[15:12] = 1000) ─────────────────────────
    if ((hw >>> 12) === 0x8) {
      const l   = (hw >>> 11) & 1;
      const imm5 = (hw >>> 6) & 0x1f;
      const rn  = (hw >>> 3) & 0x7;
      const rt  = hw & 0x7;
      const addr = u32(this.regs[rn] + (imm5 << 1));
      if (l) {
        this.regs[rt] = this.read16(bus, addr);
      } else {
        this.write16(bus, addr, this.regs[rt]);
      }
      return 2;
    }

    // ── SP-relative (bits[15:12] = 1001) ─────────────────────────────────
    if ((hw >>> 12) === 0x9) {
      const l   = (hw >>> 11) & 1;
      const rt  = (hw >>> 8) & 0x7;
      const addr = u32(this.SP + ((hw & 0xff) << 2));
      if (l) {
        this.regs[rt] = this.read32(bus, addr);
      } else {
        this.write32(bus, addr, this.regs[rt]);
      }
      return 2;
    }

    // ── ADD Rd, PC, #imm8*4 (bits[15:11] = 10100) ────────────────────────
    if ((hw >>> 11) === 0x14) {
      const rd   = (hw >>> 8) & 0x7;
      const base = (pc + 4) & ~3;
      this.regs[rd] = u32(base + ((hw & 0xff) << 2));
      return 1;
    }

    // ── ADD Rd, SP, #imm8*4 (bits[15:11] = 10101) ────────────────────────
    if ((hw >>> 11) === 0x15) {
      const rd = (hw >>> 8) & 0x7;
      this.regs[rd] = u32(this.SP + ((hw & 0xff) << 2));
      return 1;
    }

    // ── Miscellaneous (bits[15:12] = 1011) ───────────────────────────────
    if ((hw >>> 12) === 0xb) {
      return this.exec16_misc(hw, bus, pc);
    }

    // ── STM / LDM (bits[15:12] = 1100) ───────────────────────────────────
    if ((hw >>> 12) === 0xc) {
      const l    = (hw >>> 11) & 1;
      const rn   = (hw >>> 8) & 0x7;
      const rlist = hw & 0xff;
      let addr = this.regs[rn];
      let cycles = 1;
      for (let i = 0; i <= 7; i++) {
        if (rlist & (1 << i)) {
          if (l) {
            this.regs[i] = this.read32(bus, addr);
          } else {
            this.write32(bus, addr, this.regs[i]);
          }
          addr = u32(addr + 4);
          cycles++;
        }
      }
      this.regs[rn] = addr;  // writeback
      return cycles;
    }

    // ── Conditional branch (bits[15:12] = 1101) ──────────────────────────
    if ((hw >>> 12) === 0xd) {
      const cond   = (hw >>> 8) & 0xf;
      if (cond === 0xe) {
        // UDF / permanently undefined — throw
        throw new Error(`UDF at PC=0x${pc.toString(16)}`);
      }
      if (cond === 0xf) {
        // SVC #imm8 — supervisor call. Dispatch to the system's BIOS syscall
        // handler if it provides one (RP2350); otherwise a NOP (no supervisor).
        bus.onSvc?.(hw & 0xff, this);
        return 1;
      }
      if (this.condPasses(cond)) {
        const offset = ((hw & 0xff) << 24) >> 24;  // sign-extend 8-bit
        this.regs[15] = u32(pc + 4 + (offset << 1));
      }
      return 1;
    }

    // ── Unconditional branch (bits[15:11] = 11100) ───────────────────────
    if ((hw >>> 11) === 0x1c) {
      const offset = ((hw & 0x7ff) << 21) >> 21;  // sign-extend 11-bit
      this.regs[15] = u32(pc + 4 + (offset << 1));
      return 1;
    }

    throw new Error(`Unimplemented 16-bit Thumb2: 0x${hw.toString(16).padStart(4,'0')} at PC=0x${pc.toString(16)}`);
  }

  // ─── 16-bit: Shifts, Add/Sub, Mov/Cmp ────────────────────────────────────

  private exec16_shift_add(hw: number, _pc: number): number {
    const b15_13 = (hw >>> 13) & 0x7;

    if (b15_13 === 0x1) {
      // bits[15:13] = 001 — MOV/CMP/ADD/SUB #imm8
      const op2 = (hw >>> 11) & 0x3;
      const rdn = (hw >>> 8) & 0x7;
      const imm8 = hw & 0xff;
      switch (op2) {
        case 0: {  // MOV Rd, #imm8
          const r = u32(imm8);
          this.regs[rdn] = r;
          this.nzIt(r);
          // C,V unchanged
          break;
        }
        case 1: {  // CMP Rn, #imm8 (compare — always sets flags)
          this.setNZCV_sub(this.regs[rdn], imm8);
          break;
        }
        case 2: {  // ADD Rd, #imm8
          const a = this.regs[rdn];
          this.addIt(a, imm8);
          this.regs[rdn] = u32(a + imm8);
          break;
        }
        case 3: {  // SUB Rd, #imm8
          const a = this.regs[rdn];
          this.subIt(a, imm8);
          this.regs[rdn] = u32(a - imm8);
          break;
        }
      }
      return 1;
    }

    // bits[15:13] = 000 — shifts and add/sub
    const b12_10 = (hw >>> 10) & 0x7;

    if (b12_10 <= 0x5) {
      // LSL / LSR / ASR imm5 (b12_10: LSL=0/1, LSR=2/3, ASR=4/5)
      const shiftType = (hw >>> 11) & 0x3;  // 0=LSL, 1=LSR, 2=ASR
      const imm5 = (hw >>> 6) & 0x1f;
      const rm   = (hw >>> 3) & 0x7;
      const rd   = hw & 0x7;
      let result: number;
      if (shiftType === 0) {
        result = this.lsl(this.regs[rm], imm5 === 0 ? 0 : imm5, imm5 !== 0);
      } else if (shiftType === 1) {
        result = this.lsr(this.regs[rm], imm5 === 0 ? 32 : imm5, true);
      } else {
        result = this.asr(this.regs[rm], imm5 === 0 ? 32 : imm5, true);
      }
      this.regs[rd] = result;
      this.nzIt(result);
      return 1;
    }

    // bits[12:10] = 110 or 111 — ADD/SUB reg or imm3
    // bits[12:9] = 0b0110 → ADD Rd, Rn, Rm
    //              0b0111 → SUB Rd, Rn, Rm
    //              0b1100 → ADD Rd, Rn, #imm3
    //              0b1101 → SUB Rd, Rn, #imm3
    const b12_9 = (hw >>> 9) & 0xf;
    const rd    = hw & 0x7;
    const rn    = (hw >>> 3) & 0x7;

    if (b12_9 === 0xc) {
      // ADD Rd, Rn, Rm
      const rm = (hw >>> 6) & 0x7;
      const a  = this.regs[rn];
      const b  = this.regs[rm];
      this.addIt(a, b);
      this.regs[rd] = u32(a + b);
    } else if (b12_9 === 0xd) {
      // SUB Rd, Rn, Rm
      const rm = (hw >>> 6) & 0x7;
      const a  = this.regs[rn];
      const b  = this.regs[rm];
      this.subIt(a, b);
      this.regs[rd] = u32(a - b);
    } else if (b12_9 === 0xe) {
      // ADD Rd, Rn, #imm3
      const imm3 = (hw >>> 6) & 0x7;
      const a    = this.regs[rn];
      this.addIt(a, imm3);
      this.regs[rd] = u32(a + imm3);
    } else if (b12_9 === 0xf) {
      // SUB Rd, Rn, #imm3
      const imm3 = (hw >>> 6) & 0x7;
      const a    = this.regs[rn];
      this.subIt(a, imm3);
      this.regs[rd] = u32(a - imm3);
    } else {
      throw new Error(`Unimplemented shift_add group: 0x${hw.toString(16).padStart(4,'0')}`);
    }
    return 1;
  }

  // ─── 16-bit: ALU operations (bits[15:10] = 010000) ───────────────────────

  private exec16_alu(hw: number, _pc: number): number {
    const aluOp = (hw >>> 6) & 0xf;
    const rm    = (hw >>> 3) & 0x7;
    const rdn   = hw & 0x7;
    const a     = this.regs[rdn];
    const b     = this.regs[rm];

    switch (aluOp) {
      case 0x0: {  // AND
        const r = u32(a & b);
        this.regs[rdn] = r;
        this.nzIt(r);
        break;
      }
      case 0x1: {  // EOR
        const r = u32(a ^ b);
        this.regs[rdn] = r;
        this.nzIt(r);
        break;
      }
      case 0x2: {  // LSL reg
        const shift = b & 0xff;
        const r = this.lsl(a, shift, true);
        this.regs[rdn] = r;
        this.nzIt(r);
        break;
      }
      case 0x3: {  // LSR reg
        const shift = b & 0xff;
        const r = this.lsr(a, shift === 0 ? 0 : shift, shift !== 0);
        this.regs[rdn] = r;
        this.nzIt(r);
        break;
      }
      case 0x4: {  // ASR reg
        const shift = b & 0xff;
        const r = this.asr(a, shift, shift !== 0);
        this.regs[rdn] = r;
        this.nzIt(r);
        break;
      }
      case 0x5: {  // ADC
        const carry = this.flagC;
        const r64 = u32(a) + u32(b) + carry;
        const r32 = u32(r64);
        this.regs[rdn] = r32;
        if (!this.inItBlock()) {
          this.setN((r32 >>> 31) === 1);
          this.setZ(r32 === 0);
          this.setC(r64 > 0xffff_ffff);
          const sA = (a >>> 31) & 1;
          const sB = (b >>> 31) & 1;
          const sR = (r32 >>> 31) & 1;
          this.setV(sA === sB && sR !== sA);
        }
        break;
      }
      case 0x6: {  // SBC
        const borrow = 1 - this.flagC;
        const r64 = u32(a) - u32(b) - borrow;
        const r32 = u32(r64);
        if (!this.inItBlock()) this.setNZCV_sub(a, b + borrow);  // approximate for flags
        this.regs[rdn] = r32;
        break;
      }
      case 0x7: {  // ROR
        const shift = b & 0xff;
        const r = this.ror(a, shift, shift !== 0);
        this.regs[rdn] = r;
        this.nzIt(r);
        break;
      }
      case 0x8: {  // TST
        const r = u32(a & b);
        this.setNZ(r);
        break;
      }
      case 0x9: {  // RSB / NEG (Rd = 0 - Rn)
        const r = u32(0 - b);
        this.regs[rdn] = r;
        this.subIt(0, b);
        break;
      }
      case 0xa: {  // CMP
        this.setNZCV_sub(a, b);
        break;
      }
      case 0xb: {  // CMN
        this.setNZCV_add(a, b);
        break;
      }
      case 0xc: {  // ORR
        const r = u32(a | b);
        this.regs[rdn] = r;
        this.nzIt(r);
        break;
      }
      case 0xd: {  // MUL
        // 32-bit multiply; lower 32 bits of product
        // JavaScript multiplication is floating-point; need BigInt for correctness
        // at the extremes, but for VPy the values are bounded to ±127 typically.
        const r = u32(Math.imul(a, b));
        this.regs[rdn] = r;
        this.nzIt(r);
        break;
      }
      case 0xe: {  // BIC
        const r = u32(a & ~b);
        this.regs[rdn] = r;
        this.nzIt(r);
        break;
      }
      case 0xf: {  // MVN
        const r = u32(~b);
        this.regs[rdn] = r;
        this.nzIt(r);
        break;
      }
    }
    return 1;
  }

  // ─── 16-bit: Hi-register ops / BX (bits[15:10] = 010001) ─────────────────

  private exec16_hireg(hw: number, _bus: IBus, _pc: number): number {
    const op2 = (hw >>> 8) & 0x3;
    const dn   = (hw >>> 7) & 0x1;
    const rm   = (hw >>> 3) & 0xf;  // includes hi-reg bit
    const rdn  = ((hw & 0x7) | (dn << 3));  // 4-bit register number

    switch (op2) {
      case 0x0: {  // ADD (hi registers)
        this.regs[rdn] = u32(this.regs[rdn] + this.regs[rm]);
        // No flag update for hi-reg ADD
        break;
      }
      case 0x1: {  // CMP (hi registers) — sets flags, discards result
        this.setNZCV_sub(this.regs[rdn], this.regs[rm]);
        break;
      }
      case 0x2: {  // MOV (hi registers)
        const val = this.regs[rm];
        if (rdn === 15) {
          this.regs[15] = val & ~1;  // branch (Thumb bit stripped)
        } else {
          this.regs[rdn] = val;
        }
        // No flag update
        break;
      }
      case 0x3: {
        // BX Rm when dn_bit=0, BLX Rm when dn_bit=1
        if (dn === 0) {
          // BX Rm
          this.regs[15] = this.regs[rm] & ~1;
        } else {
          // BLX Rm — LR = return address with Thumb bit set
          this.LR = this.regs[15] | 1;
          this.regs[15] = this.regs[rm] & ~1;
        }
        break;
      }
    }
    return 1;
  }

  // ─── 16-bit: Load/Store register offset (bits[15:12] = 0101) ─────────────

  private exec16_ldst_reg(hw: number, bus: IBus): number {
    const op  = (hw >>> 9) & 0x7;  // bits[11:9]
    const rm  = (hw >>> 6) & 0x7;
    const rn  = (hw >>> 3) & 0x7;
    const rt  = hw & 0x7;
    const addr = u32(this.regs[rn] + this.regs[rm]);

    switch (op) {
      case 0x0:  // STR   Rt, [Rn, Rm]
        this.write32(bus, addr, this.regs[rt]);
        break;
      case 0x1:  // STRH  Rt, [Rn, Rm]
        this.write16(bus, addr, this.regs[rt] & 0xffff);
        break;
      case 0x2:  // STRB  Rt, [Rn, Rm]
        bus.write8(addr, this.regs[rt] & 0xff);
        break;
      case 0x3:  // LDRSB Rt, [Rn, Rm] — sign-extend 8-bit
        this.regs[rt] = u32((bus.read8(addr) << 24) >> 24);
        break;
      case 0x4:  // LDR   Rt, [Rn, Rm]
        this.regs[rt] = this.read32(bus, addr);
        break;
      case 0x5:  // LDRH  Rt, [Rn, Rm]
        this.regs[rt] = this.read16(bus, addr);
        break;
      case 0x6:  // LDRB  Rt, [Rn, Rm]
        this.regs[rt] = bus.read8(addr);
        break;
      case 0x7:  // LDRSH Rt, [Rn, Rm] — sign-extend 16-bit
        this.regs[rt] = u32((this.read16(bus, addr) << 16) >> 16);
        break;
    }
    return 2;
  }

  // ─── 16-bit: Load/Store immediate (bits[15:13] = 011) ────────────────────

  private exec16_ldst_imm(hw: number, bus: IBus): number {
    // bits[12] = B/W flag, bits[11] = L flag
    const b12  = (hw >>> 12) & 1;
    const l    = (hw >>> 11) & 1;
    const imm5 = (hw >>> 6) & 0x1f;
    const rn   = (hw >>> 3) & 0x7;
    const rt   = hw & 0x7;

    if (b12 === 0) {
      // Word: imm5 * 4
      const addr = u32(this.regs[rn] + (imm5 << 2));
      if (l) {
        this.regs[rt] = this.read32(bus, addr);
      } else {
        this.write32(bus, addr, this.regs[rt]);
      }
    } else {
      // Byte: imm5 * 1
      const addr = u32(this.regs[rn] + imm5);
      if (l) {
        this.regs[rt] = bus.read8(addr);
      } else {
        bus.write8(addr, this.regs[rt] & 0xff);
      }
    }
    return 2;
  }

  // ─── 16-bit: Miscellaneous (bits[15:12] = 1011) ──────────────────────────

  private exec16_misc(hw: number, bus: IBus, _pc: number): number {
    const b11_8 = (hw >>> 8) & 0xf;

    // ── PUSH {regs [, LR]} — bits[11:9] = 010
    if (b11_8 === 0x5 || b11_8 === 0x4) {
      const pbit  = (hw >>> 8) & 1;   // bit 8 = push LR
      const rlist = hw & 0xff;
      // Push LR first (highest address) then descend
      if (pbit) this.push32(bus, this.LR);
      for (let i = 7; i >= 0; i--) {
        if (rlist & (1 << i)) this.push32(bus, this.regs[i]);
      }
      return 1 + (rlist ? this.bitCount(rlist) : 0) + pbit;
    }

    // ── POP {regs [, PC]} — bits[11:9] = 110
    if (b11_8 === 0xd || b11_8 === 0xc) {
      const pbit  = (hw >>> 8) & 1;   // bit 8 = pop PC
      const rlist = hw & 0xff;
      for (let i = 0; i <= 7; i++) {
        if (rlist & (1 << i)) this.regs[i] = this.pop32(bus);
      }
      if (pbit) {
        const target = this.pop32(bus);
        this.regs[15] = target & ~1;
      }
      return 1 + (rlist ? this.bitCount(rlist) : 0) + pbit;
    }

    // ── ADD SP, SP, #imm7*4 — bits[11:8] = 0000
    if (b11_8 === 0x0) {
      const sign = (hw >>> 7) & 1;
      const imm  = (hw & 0x7f) << 2;
      if (sign === 0) {
        this.SP = u32(this.SP + imm);
      } else {
        this.SP = u32(this.SP - imm);
      }
      return 1;
    }

    // ── SXTH / SXTB / UXTH / UXTB — bits[11:8] = 0010
    if (b11_8 === 0x2) {
      const op2 = (hw >>> 6) & 0x3;
      const rm  = (hw >>> 3) & 0x7;
      const rd  = hw & 0x7;
      switch (op2) {
        case 0x0:  // SXTH
          this.regs[rd] = u32((this.regs[rm] << 16) >> 16);
          break;
        case 0x1:  // SXTB
          this.regs[rd] = u32((this.regs[rm] << 24) >> 24);
          break;
        case 0x2:  // UXTH
          this.regs[rd] = this.regs[rm] & 0xffff;
          break;
        case 0x3:  // UXTB
          this.regs[rd] = this.regs[rm] & 0xff;
          break;
      }
      return 1;
    }

    // ── REV / REV16 / REVSH — bits[11:8] = 1010
    if (b11_8 === 0xa) {
      const op2 = (hw >>> 6) & 0x3;
      const rm  = (hw >>> 3) & 0x7;
      const rd  = hw & 0x7;
      const v   = this.regs[rm];
      switch (op2) {
        case 0x0: {  // REV
          this.regs[rd] = u32(
            ((v & 0xff) << 24) | (((v >>> 8) & 0xff) << 16) |
            (((v >>> 16) & 0xff) << 8) | ((v >>> 24) & 0xff)
          );
          break;
        }
        case 0x1: {  // REV16
          this.regs[rd] = u32(
            (((v >>> 8) & 0xff) | ((v & 0xff) << 8)) |
            (((v >>> 24) & 0xff) << 16) | (((v >>> 16) & 0xff) << 24)
          );
          break;
        }
        case 0x3: {  // REVSH
          const lo = ((v & 0xff) << 8) | ((v >>> 8) & 0xff);
          this.regs[rd] = u32((lo << 16) >> 16);
          break;
        }
      }
      return 1;
    }

    // ── IT instruction — bits[11:8] = 1111
    if (b11_8 === 0xf) {
      const firstCond = (hw >>> 4) & 0xf;
      const mask      = hw & 0xf;

      // NOP (and NOP-compatible hints: WFI, WFE, etc.)
      if (mask === 0x0) {
        const hint = (hw >>> 4) & 0xf;
        if (hint === 0x3) {
          // WFI — frame sync point
          this.hitWfi = true;
        }
        // All other hints (NOP=0, YIELD=1, WFE=2, SEV=4) treated as NOP
        return 1;
      }

      // Build itState:
      //   bits[7:4] = condition code (firstCond)
      //   bits[4:0] = THEN/ELSE sense bits
      // ARM encoding: mask[3:1] = positions for instructions 2-4,
      // bit[0] always 1 for the "end" marker (or unused positions = 0).
      // Simplification: store firstCond in [7:4], then bits that drive
      // itCondTrue() for each of the up to 4 slots.
      //
      // The ARM IT mask packs things this way:
      //   mask = [t4][t3][t2][1] for ITE/ITEE/ITET/ITETE etc.
      // bit[3] (mask & 0x8) being 1 means "only 1 more instruction"
      // bit[2] being 1 (with bit[3]=0) means "2 more", etc.
      //
      // We store a simplified form: itState[7:4]=firstCond, itState[4:0]=active mask
      // where each active bit's THEN sense matches firstCond[0] XOR position-parity.
      this.itState = ((firstCond & 0xf) << 4) | (mask & 0x1f);
      return 1;
    }

    // ── CBZ / CBNZ — bits[11:8] = 0001 or 0011 or 1001 or 1011
    if ((hw & 0xf500) === 0xb100 || (hw & 0xf500) === 0xb900) {
      const nz  = (hw >>> 11) & 1;
      const rn  = hw & 0x7;
      const imm = ((hw >>> 3) & 0x1f) << 1 | ((hw >>> 9) & 1) << 6;
      const test = this.regs[rn];
      if (nz ? test !== 0 : test === 0) {
        this.regs[15] = u32(_pc + 4 + imm);
      }
      return 1;
    }

    throw new Error(`Unimplemented 16-bit misc: 0x${hw.toString(16).padStart(4,'0')}`);
  }

  // =========================================================================
  // 32-bit instruction execution
  // =========================================================================

  private exec32(hw0: number, hw1: number, bus: IBus, pc: number): number {
    // ARM Thumb-2 32-bit dispatch.
    // hw0[15:11] identifies the primary instruction group:
    //   11101 (0x1D) → load/store / data-processing register
    //   11110 (0x1E) → data-processing immediate OR branch (hw1[15] discriminates)
    //   11111 (0x1F) → coprocessor / FP / misc

    // IT-block conditioning (skip + advance) is handled once in step() for BOTH
    // 16- and 32-bit instructions. It must NOT be repeated here: doing it in both
    // step() and exec32 advanced the IT state TWICE per 32-bit instruction,
    // desyncing mixed 16/32-bit IT blocks (e.g. the 6502 BIT flag macro
    // `ite eq; orreq.w; bicne.w` ran the else branch too, corrupting the Z flag).
    const op5 = (hw0 >>> 11) & 0x1f;

    if (op5 === 0x1e) {
      // hw1[15]=1 → branches and miscellaneous control (BL, B.W, etc.)
      // hw1[15]=0 → data-processing (modified immediate, MOVW, MOVT, ADDW, …)
      if ((hw1 & 0x8000) !== 0) {
        return this.exec32_branch(hw0, hw1, pc);
      } else {
        return this.exec32_data(hw0, hw1, bus, pc);
      }
    }

    if (op5 === 0x1d || op5 === 0x1f) {
      return this.exec32_data(hw0, hw1, bus, pc);
    }

    throw new Error(`Unimplemented 32-bit Thumb2: hw0=0x${hw0.toString(16).padStart(4,'0')} hw1=0x${hw1.toString(16).padStart(4,'0')} at PC=0x${pc.toString(16)}`);
  }

  // ─── 32-bit: Branches ─────────────────────────────────────────────────────

  private exec32_branch(hw0: number, hw1: number, pc: number): number {
    // BL: hw0[15:11]=11110, hw1[15:14]=11, hw1[12]=1
    // B.W unconditional: hw0[15:11]=11110, hw1[15:14]=10, hw1[12]=1
    // B.W conditional:   hw0[15:11]=11110, hw1[15:14]=10, hw1[12]=0

    const J1  = (hw1 >>> 13) & 1;
    const J2  = (hw1 >>> 11) & 1;
    const S   = (hw0 >>> 10) & 1;
    const I1  = ((~(J1 ^ S)) & 1);
    const I2  = ((~(J2 ^ S)) & 1);

    const hw1_15_14 = (hw1 >>> 14) & 0x3;
    const hw1_12    = (hw1 >>> 12) & 1;

    if (hw1_15_14 === 0x3) {
      // BL (unconditional, with link)
      const offset_hi = hw0 & 0x3ff;
      const offset_lo = hw1 & 0x7ff;
      const raw = (S << 24) | (I1 << 23) | (I2 << 22) | (offset_hi << 12) | (offset_lo << 1);
      const offset = (raw << 7) >> 7;  // sign-extend 25-bit
      this.LR = u32(pc + 4) | 1;  // Thumb bit set in LR
      this.regs[15] = u32(pc + 4 + offset);
      return 3;
    }

    if (hw1_15_14 === 0x2) {
      if (hw1_12 === 1) {
        // B.W unconditional
        const offset_hi = hw0 & 0x3ff;
        const offset_lo = hw1 & 0x7ff;
        const raw = (S << 24) | (I1 << 23) | (I2 << 22) | (offset_hi << 12) | (offset_lo << 1);
        const offset = (raw << 7) >> 7;  // sign-extend 25-bit
        this.regs[15] = u32(pc + 4 + offset);
        return 3;
      } else {
        // hw1[15:14]=0b10, hw1[12]=0 is EITHER a conditional B.W (cond != 0b111x)
        // OR — when cond (hw0[9:6]) == 0b111x — a "branch and miscellaneous
        // control" instruction: barriers (DMB/DSB/ISB/CLREX), hints (NOP/SEV/
        // WFE/WFI/DBG), MSR/MRS. The dual-core game SDK uses `dmb sy` (0xf3bf
        // 0x8f5f) in v_WaitRecal; without this it decoded as an always-taken
        // branch and jumped to garbage. VPy single-core games never emit these.
        const cond = (hw0 >>> 6) & 0xf;
        if (cond >= 0xE) {
          const op = (hw0 >>> 4) & 0x7f;  // hw0[10:4]
          // 0x3b = CLREX/DSB/DMB/ISB, 0x3a = hint space (NOP/YIELD/WFE/SEV/WFI/DBG).
          // All are no-ops in this functional core (no caches, no real 2nd core).
          if (op === 0x3b || op === 0x3a) return 1;
          throw new Error(`Unimplemented 32-bit misc-control: hw0=0x${hw0.toString(16)} hw1=0x${hw1.toString(16)} at PC=0x${pc.toString(16)}`);
        }
        // B.W conditional: hw1[11]=J2 used as J2, cond in hw0[9:6]
        const S2   = (hw0 >>> 10) & 1;
        const imm6 = hw0 & 0x3f;
        const imm11 = hw1 & 0x7ff;
        const J1c = (hw1 >>> 13) & 1;
        const J2c = (hw1 >>> 11) & 1;
        const raw2 = (S2 << 20) | (J2c << 19) | (J1c << 18) | (imm6 << 12) | (imm11 << 1);
        const offset = (raw2 << 11) >> 11;  // sign-extend 21-bit
        if (this.condPasses(cond)) {
          this.regs[15] = u32(pc + 4 + offset);
        }
        return 3;
      }
    }

    throw new Error(`Unimplemented 32-bit branch: hw0=0x${hw0.toString(16)} hw1=0x${hw1.toString(16)} at PC=0x${pc.toString(16)}`);
  }

  // ─── 32-bit: Data processing and memory ──────────────────────────────────

  private exec32_data(hw0: number, hw1: number, bus: IBus, pc: number): number {
    // Decode the 32-bit instruction based on primary opcode fields.
    // hw0[15:11] = 11110 or 11111 for all 32-bit data / memory / multiply.

    // Combined 32-bit view (for some fields it's easier):
    // Reconstruct bits: [hw0 bit15..0] [hw1 bit15..0]
    // i.e. bit31 = hw0[15], bit16 = hw0[0], bit15 = hw1[15], bit0 = hw1[0]

    // MOVW: hw0 = 1111 0 i10 0100 imm4, hw1 = 0 imm3 Rd imm8
    // Check hw0[15:12]=1111, hw0[11]=0, hw0[9:8]=10, hw0[7:4]=0100
    if ((hw0 & 0xfbf0) === 0xf240) {
      // MOVW
      const imm4 = hw0 & 0xf;
      const i    = (hw0 >>> 10) & 1;
      const imm3 = (hw1 >>> 12) & 0x7;
      const rd   = (hw1 >>> 8) & 0xf;
      const imm8 = hw1 & 0xff;
      const imm16 = (imm4 << 12) | (i << 11) | (imm3 << 8) | imm8;
      this.regs[rd] = imm16;
      return 2;
    }

    // MOVT: hw0 = 1111 0 i10 1100 imm4, hw1 = 0 imm3 Rd imm8
    if ((hw0 & 0xfbf0) === 0xf2c0) {
      const imm4 = hw0 & 0xf;
      const i    = (hw0 >>> 10) & 1;
      const imm3 = (hw1 >>> 12) & 0x7;
      const rd   = (hw1 >>> 8) & 0xf;
      const imm8 = hw1 & 0xff;
      const imm16 = (imm4 << 12) | (i << 11) | (imm3 << 8) | imm8;
      // Keep lower 16 bits, set upper 16
      this.regs[rd] = (this.regs[rd] & 0x0000ffff) | (imm16 << 16);
      return 2;
    }

    // SDIV: hw0 = 1111 1011 1001 Rn, hw1 = 1111 Rd 1111 Rm
    if ((hw0 & 0xfff0) === 0xfb90 && (hw1 & 0xf0f0) === 0xf0f0) {
      const rn = hw0 & 0xf;
      const rd = (hw1 >>> 8) & 0xf;
      const rm = hw1 & 0xf;
      const dividend = s32(this.regs[rn]);
      const divisor  = s32(this.regs[rm]);
      if (divisor === 0) {
        this.regs[rd] = 0;  // SDIV by zero → 0 (Cortex-M)
      } else {
        // Truncate toward zero
        this.regs[rd] = u32(Math.trunc(dividend / divisor));
      }
      return 8;  // ~2-12 cycles; use 8 as average
    }

    // UDIV: hw0 = 1111 1011 1011 Rn, hw1 = 1111 Rd 1111 Rm
    if ((hw0 & 0xfff0) === 0xfbb0 && (hw1 & 0xf0f0) === 0xf0f0) {
      const rn = hw0 & 0xf;
      const rd = (hw1 >>> 8) & 0xf;
      const rm = hw1 & 0xf;
      const dividend = u32(this.regs[rn]);
      const divisor  = u32(this.regs[rm]);
      if (divisor === 0) {
        this.regs[rd] = 0;
      } else {
        this.regs[rd] = u32(Math.floor(dividend / divisor));
      }
      return 8;
    }

    // MUL / MLA / MLS (32-bit): hw0=1111 1011 0000 Rn, hw1 = Ra Rd 000 op Rm.
    //   Ra==1111 → MUL (rd = rn*rm)
    //   op(bit4)=0 → MLA (rd = rn*rm + Ra)   ← was mis-decoded as plain MUL,
    //   op(bit4)=1 → MLS (rd = Ra - rn*rm)      dropping Ra → the vpy_load_level
    // copy loop's bound `20*count + base` collapsed to `20*count`, so the pointer
    // never reached it and the level load spun forever.
    if ((hw0 & 0xfff0) === 0xfb00 && (hw1 & 0x00e0) === 0x0000) {
      const rn = hw0 & 0xf;
      const ra = (hw1 >>> 12) & 0xf;
      const rd = (hw1 >>> 8) & 0xf;
      const op = (hw1 >>> 4) & 0x1;
      const rm = hw1 & 0xf;
      const prod = Math.imul(this.regs[rn], this.regs[rm]);
      if (ra === 15)      this.regs[rd] = u32(prod);                    // MUL
      else if (op === 1)  this.regs[rd] = u32(this.regs[ra] - prod);    // MLS
      else                this.regs[rd] = u32(this.regs[ra] + prod);    // MLA
      return 3;
    }

    // SMUL{B,T}{B,T} / SMLA{B,T}{B,T} — signed 16×16→32 halfword multiply.
    // hw0 = 1111 1011 0001 Rn, hw1 = Ra Rd 00 N M Rm. N/M pick the top(1) or
    // bottom(0) signed halfword of Rn/Rm; Ra==15 → SMUL, else SMLA (add Ra).
    // C emits these for fixed-point/16-bit math; VPy codegen never did (the
    // "blocks at 10 s" freeze — an unimplemented-instruction throw mid-frame).
    if ((hw0 & 0xfff0) === 0xfb10 && (hw1 & 0x00c0) === 0x0000) {
      const rn = hw0 & 0xf;
      const ra = (hw1 >>> 12) & 0xf;
      const rd = (hw1 >>> 8) & 0xf;
      const n  = (hw1 >>> 5) & 1;
      const m  = (hw1 >>> 4) & 1;
      const rm = hw1 & 0xf;
      const op1 = n ? (this.regs[rn] >> 16) : ((this.regs[rn] << 16) >> 16);
      const op2 = m ? (this.regs[rm] >> 16) : ((this.regs[rm] << 16) >> 16);
      let res = op1 * op2;                       // ≤ ±2^30, exact in JS
      if (ra !== 15) res += this.regs[ra] | 0;   // SMLA: + Ra (signed)
      this.regs[rd] = u32(res);
      return 3;
    }

    // SMULL/UMULL/SMLAL/UMLAL — 32×32→64 long multiply(-accumulate).
    // hw0 = 1111 1011 1 op1 Rn (op1[6:4]: 000/010/100/110), hw1 = RdLo RdHi 0000 Rm.
    //   bit5 (0x20): 1 = unsigned (U…), 0 = signed (S…)
    //   bit6 (0x40): 1 = accumulate into {RdHi:RdLo} (…LAL)
    // gcc emits these for 64-bit and widening integer math; VPy codegen never
    // did, so C imports (e.g. AAE's 6502 core) are the first to reach them.
    // BigInt keeps the 64-bit product exact (JS numbers lose precision > 2^53).
    if ((hw0 & 0xff90) === 0xfb80 && (hw1 & 0x00f0) === 0x0000) {
      const rn = hw0 & 0xf, rm = hw1 & 0xf;
      const rdlo = (hw1 >>> 12) & 0xf, rdhi = (hw1 >>> 8) & 0xf;
      const unsigned   = (hw0 & 0x0020) !== 0;
      const accumulate = (hw0 & 0x0040) !== 0;
      const a = unsigned ? BigInt(this.regs[rn] >>> 0) : BigInt(s32(this.regs[rn]));
      const b = unsigned ? BigInt(this.regs[rm] >>> 0) : BigInt(s32(this.regs[rm]));
      let res = a * b;
      if (accumulate) {
        res += (BigInt(this.regs[rdhi] >>> 0) << 32n) | BigInt(this.regs[rdlo] >>> 0);
      }
      res &= (1n << 64n) - 1n;
      this.regs[rdlo] = Number(res & 0xffffffffn) >>> 0;
      this.regs[rdhi] = Number((res >> 32n) & 0xffffffffn) >>> 0;
      return 5;
    }

    // CLZ Rd, Rm — count leading zeros. hw0 = 1111 1010 1011 Rm, hw1 = 1111 Rd 1000 Rm.
    if ((hw0 & 0xfff0) === 0xfab0 && (hw1 & 0xf0f0) === 0xf080) {
      const rm = hw1 & 0xf;
      const rd = (hw1 >>> 8) & 0xf;
      this.regs[rd] = Math.clz32(this.regs[rm] >>> 0);
      return 1;
    }

    // ── 32-bit Data-processing immediate ─────────────────────────────────
    // hw0[15:11]=11110: covers AND/BIC/ORR/MOV/EOR/ADD/ADC/SUB/RSB with imm
    if ((hw0 & 0xf800) === 0xf000) {
      return this.exec32_dp_imm(hw0, hw1, pc);
    }

    // ── 32-bit Data-processing register (EA00-EBFF) ───────────────────────
    if ((hw0 & 0xfe00) === 0xea00) {
      return this.exec32_dp_reg(hw0, hw1);
    }

    // ── LSL/LSR/ASR/ROR (register), 32-bit ────────────────────────────────
    // hw0 = 1111 1010 0 tt S Rn, hw1 = 1111 Rd 0000 Rm  (tt: 0=LSL,1=LSR,2=ASR,3=ROR).
    // These share the FA00-FA7F block with the extend ops but are distinguished
    // by hw1[15:12]=1111 AND hw1[7:4]=0000. Without this they were misrouted to
    // exec32_extend (UXTB/SXTB…) and mangled — e.g. __aeabi_f2iz's `lsr.w r0,r3,r2`
    // returned garbage, so every soft-float coordinate (AAE's draws) was wrong.
    if ((hw0 & 0xff80) === 0xfa00 && (hw1 & 0xf0f0) === 0xf000) {
      const rn = hw0 & 0xf, rm = hw1 & 0xf, rd = (hw1 >>> 8) & 0xf;
      const s = ((hw0 >>> 4) & 1) === 1;
      const type = (hw0 >>> 5) & 0x3;
      const amount = this.regs[rm] & 0xff;
      let r: number;
      if (type === 0) r = this.lsl(this.regs[rn], amount, s);
      else if (type === 1) r = this.lsr(this.regs[rn], amount === 0 ? 0 : amount, s && amount !== 0);
      else if (type === 2) r = this.asr(this.regs[rn], amount, s && amount !== 0);
      else r = this.ror(this.regs[rn], amount, s && amount !== 0);
      this.regs[rd] = r;
      if (s) this.setNZ(r);
      return 1;
    }

    // ── Saturate / extend / misc (FA00-FA7F) ──────────────────────────────
    if ((hw0 & 0xff80) === 0xfa00) {
      return this.exec32_extend(hw0, hw1);
    }

    // ── 32-bit Load/Store (F800-F9FF) ─────────────────────────────────────
    if ((hw0 & 0xfe00) === 0xf800 || (hw0 & 0xfe00) === 0xf900) {
      return this.exec32_ldst(hw0, hw1, bus, pc);
    }

    // Remaining 32-bit patterns (FBxx, FCxx, FDxx, FExx, FFxx) — try LS
    return this.exec32_ldst(hw0, hw1, bus, pc);
  }

  // ─── 32-bit: Load/Store ───────────────────────────────────────────────────

  private exec32_ldst(hw0: number, hw1: number, bus: IBus, pc: number): number {
    // Decode the full 32-bit load/store space.
    // We handle the patterns actually generated by VPy codegen:
    //   LDR  Rt, [Rn, #imm12]
    //   STR  Rt, [Rn, #imm12]
    //   LDRB Rt, [Rn, #imm12]
    //   STRB Rt, [Rn, #imm12]
    //   LDRH Rt, [Rn, #imm12]
    //   STRH Rt, [Rn, #imm12]
    //   LDRSH Rt,[Rn, #imm12]
    //   LDRSB Rt,[Rn, #imm12]
    //   LDR  Rt, [Rn, #-imm8] (Thumb2 pre/post)
    //   LDR  Rt, [SP, #imm8*4]
    //   STR  Rt, [SP, #imm8*4]
    //   STMDB SP!, reglist  (PUSH T2 — 32-bit, used when reglist includes r8-r14)
    //   LDMIA SP!, reglist  (POP  T2 — 32-bit, used when reglist includes r8-r15)

    // ── STMDB SP!, reglist (PUSH T2): hw0 = 0xE92D ──────────────────────
    // Thumb2 STMDB T2 encoding: hw0 = 1110 1001 0 W 0 Rn (W=1, Rn=SP=13 → 0xE92D)
    // hw1 = 0 M 0 register_list[12:0]  (M=bit14=LR, bits 0-12 = r0-r12)
    if (hw0 === 0xe92d) {
      const list = hw1;
      // Count registers to determine new SP
      let count = 0;
      for (let r = 0; r <= 14; r++) {
        if (list & (1 << r)) count++;
      }
      this.regs[13] = u32(this.regs[13] - count * 4);
      let addr = this.regs[13];
      // Store in ascending register order at ascending addresses (STMDB semantics)
      for (let r = 0; r <= 14; r++) {
        if (list & (1 << r)) {
          this.write32(bus, addr, this.regs[r]);
          addr += 4;
        }
      }
      return count + 1;
    }

    // ── LDMIA SP!, reglist (POP T2): hw0 = 0xE8BD ───────────────────────
    // Thumb2 LDMIA T2 encoding: hw0 = 1110 1000 1 W 1 Rn (W=1, Rn=SP=13 → 0xE8BD)
    // hw1 = P M 0 register_list[12:0]  (P=bit15=PC, M=bit14=LR, bits 0-12 = r0-r12)
    if (hw0 === 0xe8bd) {
      const list = hw1;
      let addr = this.regs[13];
      let count = 0;
      for (let r = 0; r <= 15; r++) {
        if (list & (1 << r)) {
          const val = this.read32(bus, addr);
          if (r === 15) {
            this.regs[15] = val & ~1;
          } else if (r !== 13) {
            this.regs[r] = val;
          }
          addr += 4;
          count++;
        }
      }
      this.regs[13] = u32(addr);
      return count + 1;
    }

    // ── TBB / TBH (table branch — `switch` dispatch) ─────────────────────
    // hw0 = 1110 1000 1101 Rn (0xE8D0|Rn; Rn=15 → 0xE8DF, table follows PC).
    // hw1 = 1111 0000 000 H Rm (H: 0=byte, 1=halfword table; Rm = index).
    // Branch: PC = (insn+4) + 2*table[base + Rm (<<1 if H)]. VPy codegen never
    // emits this, but C compilers use it for dense switches (the game_state
    // loop in a C-built game), so it's needed to run the C rp2350 backend.
    if ((hw0 & 0xFFF0) === 0xE8D0 && (hw1 & 0xFFE0) === 0xF000) {
      const rnTbl = hw0 & 0xF;
      const H     = (hw1 >>> 4) & 1;
      const rmIdx = hw1 & 0xF;
      // regs[15] is already (insn addr + 4) = the architectural PC.
      const base  = (rnTbl === 15) ? this.regs[15] : this.regs[rnTbl];
      const idx   = this.regs[rmIdx];
      const value = H
        ? this.read16(bus, u32(base + (idx << 1)))
        : (bus.read8(u32(base + idx)) & 0xff);
      this.regs[15] = u32(this.regs[15] + (value << 1));
      return 2;
    }

    // ── STRD / LDRD (store/load register dual, immediate T1) ─────────────
    // hw0 = 1110 100P U1WL Rn (bit4 L: 0=STRD, 1=LDRD). hw1 = Rt Rt2 imm8.
    // addr = Rn +/- imm8*4 (pre/post per P, optional writeback W). C compilers
    // use this to spill/reload register pairs (frame setup); VPy codegen didn't.
    if ((hw0 & 0xFE40) === 0xE840) {
      const P    = (hw0 >>> 8) & 1;
      const U    = (hw0 >>> 7) & 1;
      const W    = (hw0 >>> 5) & 1;
      const L    = (hw0 >>> 4) & 1;
      const rnD  = hw0 & 0xF;
      const rt1  = (hw1 >>> 12) & 0xF;
      const rt2  = (hw1 >>> 8) & 0xF;
      const off  = (U ? (hw1 & 0xff) : -(hw1 & 0xff)) * 4;
      const base = (rnD === 15) ? u32(this.regs[15] & ~3) : this.regs[rnD];
      const addr = P ? u32(base + off) : u32(base);
      if (L) {
        this.regs[rt1] = this.read32(bus, addr);
        this.regs[rt2] = this.read32(bus, u32(addr + 4));
      } else {
        this.write32(bus, addr, this.regs[rt1]);
        this.write32(bus, u32(addr + 4), this.regs[rt2]);
      }
      if (W && rnD !== 15) this.regs[rnD] = u32(base + off);
      return 3;
    }

    // ── LDMIA (load multiple, increment after) T2 ───────────────────────
    // hw0 = 0xE890|Rn (W=0) or 0xE8B0|Rn (W=1, writeback). hw1 = reglist.
    // Note: 0xE8BD (LDMIA SP!, …) is already handled as POP T2 above.
    if ((hw0 & 0xFFF0) === 0xE890 || (hw0 & 0xFFF0) === 0xE8B0) {
      const rn2 = hw0 & 0xF;
      const writeback = (hw0 & 0x0020) !== 0;
      let addr = u32(this.regs[rn2]);
      for (let r = 0; r <= 15; r++) {
        if (hw1 & (1 << r)) {
          const val = this.read32(bus, addr);
          if (r === 15) this.regs[15] = val & ~1;
          else if (r !== 13) this.regs[r] = val;
          addr = u32(addr + 4);
        }
      }
      if (writeback) this.regs[rn2] = addr;
      return 2;
    }

    // ── STMIA (store multiple, increment after) T2 ──────────────────────
    // hw0 = 0xE880|Rn (W=0) or 0xE8A0|Rn (W=1, writeback). hw1 = reglist.
    if ((hw0 & 0xFFF0) === 0xE880 || (hw0 & 0xFFF0) === 0xE8A0) {
      const rn2 = hw0 & 0xF;
      const writeback = (hw0 & 0x0020) !== 0;
      let addr = u32(this.regs[rn2]);
      for (let r = 0; r <= 14; r++) {
        if (hw1 & (1 << r)) {
          this.write32(bus, addr, this.regs[r]);
          addr = u32(addr + 4);
        }
      }
      if (writeback) this.regs[rn2] = addr;
      return 2;
    }

    const rn  = hw0 & 0xf;
    const rt  = (hw1 >>> 12) & 0xf;

    // ── LDR Rt,[PC,#±imm12] (LDR literal T2): hw0=0xF8DF (U=1) or 0xF85F (U=0) ──
    // ARM requires Align(PC,4) = this.regs[15] & ~3 as the base — NOT raw regs[15].
    // Without this, 32-bit instructions at 2-byte-aligned addresses (after a 2-byte
    // instruction) would compute literal-pool addresses that are 2 bytes too high.
    if (hw0 === 0xf8df) {
      const imm12 = hw1 & 0xfff;
      const base  = this.regs[15] & ~3;   // Align(PC, 4)
      this.regs[rt] = this.read32(bus, u32(base + imm12));
      return 2;
    }
    if (hw0 === 0xf85f) {
      const imm12 = hw1 & 0xfff;
      const base  = this.regs[15] & ~3;   // Align(PC, 4)
      this.regs[rt] = this.read32(bus, u32(base - imm12));
      return 2;
    }

    // The most reliable decode: match against common Thumb2 LS patterns
    // hw0 pattern for LDR  (unsigned 32-bit load):  1111 1000 x101 Rn
    //                 STR  (unsigned 32-bit store): 1111 1000 x100 Rn
    //                 LDRB (unsigned 8-bit):  1111 1000 x001 Rn
    //                 LDRH (unsigned 16-bit): 1111 1000 x011 Rn
    //                 LDRSB (signed 8-bit):   1111 1001 x001 Rn
    //                 LDRSH (signed 16-bit):  1111 1001 x011 Rn

    // Unsigned 32-bit
    if ((hw0 & 0xffd0) === 0xf850 || (hw0 & 0xffd0) === 0xf8d0) {
      // LDR/STR with positive imm12 or negative imm8
      const isLoad    = ((hw0 >>> 4) & 1) === 1 || ((hw0 & 0x0010) !== 0);
      // Detect imm12 (hw1[11:0]) vs PUW form (hw1[10:8] + imm8)
      const hw1_11    = (hw1 >>> 11) & 1;
      let addr: number;
      let writeback = false;
      let wbValue = 0;
      const base = this.regs[rn];
      // The form is selected by hw0 bit7 (0x0080) and hw1[11] — NOT by whether
      // the upper hw1 bits happen to be zero. (The old `(hw1>>>8)===0` heuristic
      // mis-read register-indexed loads with Rt=0, e.g. `ldr r0,[ip,r0,lsl#2]`
      // for sprites[idx], as an imm12 load [base+32] → wrong pointer tables.)
      if ((hw0 & 0x0080) !== 0) {
        // T3: LDR/STR.W Rt, [Rn, #imm12]  — hw0 = 0xF8D0/0xF8C0|Rn (bit7=1)
        addr = u32(base + (hw1 & 0xfff));
      } else if (hw1_11 === 1) {
        // T4 PUW form: hw1 = Rt | 1 | P[10] | U[9] | W[8] | imm8[7:0]
        const P    = (hw1 >>> 10) & 1;
        const U    = (hw1 >>> 9)  & 1;
        const W    = (hw1 >>> 8)  & 1;
        const imm8 = hw1 & 0xff;
        const offset = U ? imm8 : -imm8;
        addr = P ? u32(base + offset) : u32(base);
        if (W) { writeback = true; wbValue = u32(base + offset); }
      } else {
        // T2 register-indexed: LDR/STR.W Rt, [Rn, Rm{, LSL #imm2}] (bit7=0, hw1[11]=0)
        const rm   = hw1 & 0xf;
        const imm2 = (hw1 >>> 4) & 0x3;
        addr = u32(base + (this.regs[rm] << imm2));
      }
      const actualLoad = ((hw0 >>> 4) & 1) !== 0;
      if (actualLoad) {
        const v = this.read32(bus, addr);
        // LDR pc,[...] is an interworking branch (BXWritePC): bit0 selects Thumb
        // state (always Thumb on M-profile), so mask it off for the fetch PC.
        // gcc compiles a dense switch (e.g. the 6502 opcode dispatch) as
        // `ldr.w pc,[table, idx, lsl #2]` into a table of Thumb handler
        // addresses (bit0=1); without this the PC lands odd and the next fetch
        // decodes garbage. VPy codegen never emits this form, so C imports hit
        // it first.
        if (rt === 15) this.regs[15] = v & ~1;
        else this.regs[rt] = v;
      } else {
        this.write32(bus, addr, this.regs[rt]);
      }
      if (writeback) this.regs[rn] = wbValue;
      return 2;
    }

    // Pattern-based decode: try all common patterns
    // hw0 bits identify: [15:12]=1111, [11]=0, [10:9]=size_hi, [8]=L/sign, [7:6]=size_lo
    // The simplest approach: decode from the full hw0 field directly.

    // LDR  Rt,[Rn,#imm12]: hw0=1111 1000 1101 Rn or 1111 1000 0101 Rn (U=1 pre-indexed)
    if ((hw0 & 0xfff0) === 0xf8d0) {
      // LDR unsigned 32-bit, positive offset
      const imm12 = hw1 & 0xfff;
      this.regs[rt] = this.read32(bus, u32(this.regs[rn] + imm12));
      return 2;
    }

    // STR  Rt,[Rn,#imm12]: hw0=1111 1000 1100 Rn
    if ((hw0 & 0xfff0) === 0xf8c0) {
      const imm12 = hw1 & 0xfff;
      this.write32(bus, u32(this.regs[rn] + imm12), this.regs[rt]);
      return 2;
    }

    // LDRB Rt,[Rn,#imm12]: hw0=1111 1000 1001 Rn
    if ((hw0 & 0xfff0) === 0xf890) {
      const imm12 = hw1 & 0xfff;
      this.regs[rt] = bus.read8(u32(this.regs[rn] + imm12));
      return 2;
    }

    // STRB Rt,[Rn,#imm12]: hw0=1111 1000 1000 Rn
    if ((hw0 & 0xfff0) === 0xf880) {
      const imm12 = hw1 & 0xfff;
      bus.write8(u32(this.regs[rn] + imm12), this.regs[rt] & 0xff);
      return 2;
    }

    // LDRH Rt,[Rn,#imm12]: hw0=1111 1000 1011 Rn
    if ((hw0 & 0xfff0) === 0xf8b0) {
      const imm12 = hw1 & 0xfff;
      this.regs[rt] = this.read16(bus, u32(this.regs[rn] + imm12));
      return 2;
    }

    // STRH Rt,[Rn,#imm12]: hw0=1111 1000 1010 Rn
    if ((hw0 & 0xfff0) === 0xf8a0) {
      const imm12 = hw1 & 0xfff;
      this.write16(bus, u32(this.regs[rn] + imm12), this.regs[rt] & 0xffff);
      return 2;
    }

    // LDRSB Rt,[Rn,#imm12]: hw0=1111 1001 1001 Rn
    if ((hw0 & 0xfff0) === 0xf990) {
      const imm12 = hw1 & 0xfff;
      this.regs[rt] = u32((bus.read8(u32(this.regs[rn] + imm12)) << 24) >> 24);
      return 2;
    }

    // LDRSH Rt,[Rn,#imm12]: hw0=1111 1001 1011 Rn
    if ((hw0 & 0xfff0) === 0xf9b0) {
      const imm12 = hw1 & 0xfff;
      this.regs[rt] = u32((this.read16(bus, u32(this.regs[rn] + imm12)) << 16) >> 16);
      return 2;
    }

    // LDRSB hw0=1111 1001 0001 Rn — two sub-encodings distinguished by hw1[11]:
    //   hw1[11]=0: register-indexed  Rt,[Rn,Rm,LSL#imm2]  (hw1 = Rt 000000 imm2 Rm)
    //   hw1[11]=1: PUW immediate     Rt,[Rn,#±imm8]        (hw1 = Rt 1PUW imm8)
    if ((hw0 & 0xfff0) === 0xf910) {
      if ((hw1 >>> 11) & 1) {
        // PUW immediate (negative or writeback)
        const P    = (hw1 >>> 10) & 1;
        const U    = (hw1 >>> 9)  & 1;
        const W    = (hw1 >>> 8)  & 1;
        const imm8 = hw1 & 0xff;
        const base = this.regs[rn];
        const offset = U ? imm8 : -imm8;
        const addr = P ? u32(base + offset) : u32(base);
        this.regs[rt] = u32((bus.read8(addr) << 24) >> 24);
        if (W) this.regs[rn] = u32(base + offset);
      } else {
        // Register indexed: Rt,[Rn,Rm,LSL#imm2]
        const rm   = hw1 & 0xf;
        const imm2 = (hw1 >>> 4) & 0x3;
        const addr = u32(this.regs[rn] + (this.regs[rm] << imm2));
        this.regs[rt] = u32((bus.read8(addr) << 24) >> 24);
      }
      return 2;
    }

    // LDR Rt,[Rn,{+/-}imm8] with PUW: hw0=1111 1000 0101 Rn, hw1=Rt 1PUW imm8
    if ((hw0 & 0xfff0) === 0xf850) {
      const P = (hw1 >>> 10) & 1;
      const U = (hw1 >>> 9)  & 1;
      const W = (hw1 >>> 8)  & 1;
      const imm8 = hw1 & 0xff;
      const base = this.regs[rn];
      const offset = U ? imm8 : -imm8;
      const addr = P ? u32(base + offset) : u32(base);
      this.regs[rt] = this.read32(bus, addr);
      if (W) this.regs[rn] = u32(base + offset);
      return 2;
    }

    // STR word: hw0=1111 1000 0100 Rn — register-indexed (hw1[11]=0) or the T4
    // PUW immediate (hw1[11]=1). The register form `str Rt,[Rn,Rm,LSL#imm2]` was
    // missing: it fell into the PUW path (P=0 → addr=base, index dropped), so
    // `arr[idx] = v` (e.g. thaw_timers[idx]=180) wrote to arr[0] for every idx —
    // only enemy 0 stayed frozen, the rest thawed instantly.
    if ((hw0 & 0xfff0) === 0xf840) {
      if ((hw1 >>> 11) & 1) {
        const P = (hw1 >>> 10) & 1, U = (hw1 >>> 9) & 1, W = (hw1 >>> 8) & 1;
        const imm8 = hw1 & 0xff;
        const base = this.regs[rn];
        const offset = U ? imm8 : -imm8;
        const addr = P ? u32(base + offset) : u32(base);
        this.write32(bus, addr, this.regs[rt]);
        if (W) this.regs[rn] = u32(base + offset);
      } else {
        const rm = hw1 & 0xf, imm2 = (hw1 >>> 4) & 0x3;
        this.write32(bus, u32(this.regs[rn] + (this.regs[rm] << imm2)), this.regs[rt]);
      }
      return 2;
    }

    // LDRB: hw0=1111 1000 0001 Rn — register (hw1[11]=0) or immediate pre/post
    // (hw1[11]=1). C uses `ldrb [Rn,#1]!` to walk NUL-terminated strings
    // (font_draw_string) — the register-only version broke that walk.
    if ((hw0 & 0xfff0) === 0xf810) {
      if ((hw1 >>> 11) & 1) {
        const P = (hw1 >>> 10) & 1, U = (hw1 >>> 9) & 1, W = (hw1 >>> 8) & 1;
        const imm8 = hw1 & 0xff;
        const base = this.regs[rn];
        const offset = U ? imm8 : -imm8;
        const addr = P ? u32(base + offset) : u32(base);
        this.regs[rt] = bus.read8(addr);
        if (W) this.regs[rn] = u32(base + offset);
      } else {
        const rm = hw1 & 0xf, imm2 = (hw1 >>> 4) & 0x3;
        this.regs[rt] = bus.read8(u32(this.regs[rn] + (this.regs[rm] << imm2)));
      }
      return 2;
    }

    // STRB: hw0=1111 1000 0000 Rn — register (hw1[11]=0) or immediate pre/post.
    if ((hw0 & 0xfff0) === 0xf800) {
      if ((hw1 >>> 11) & 1) {
        const P = (hw1 >>> 10) & 1, U = (hw1 >>> 9) & 1, W = (hw1 >>> 8) & 1;
        const imm8 = hw1 & 0xff;
        const base = this.regs[rn];
        const offset = U ? imm8 : -imm8;
        const addr = P ? u32(base + offset) : u32(base);
        bus.write8(addr, this.regs[rt] & 0xff);
        if (W) this.regs[rn] = u32(base + offset);
      } else {
        const rm = hw1 & 0xf, imm2 = (hw1 >>> 4) & 0x3;
        bus.write8(u32(this.regs[rn] + (this.regs[rm] << imm2)), this.regs[rt] & 0xff);
      }
      return 2;
    }

    // LDRH: hw0=1111 1000 0011 Rn — TWO sub-encodings (hw1[11] selects):
    //   hw1[11]=0: register  Rt,[Rn,Rm,LSL#imm2]
    //   hw1[11]=1: immediate  Rt,[Rn,#±imm8] with P/U/W (pre/post-index, C uses
    //     the post-index form `[Rn],#2` to walk .vec path streams — the bug that
    //     made draw_vec_stream read a garbage count and spin).
    if ((hw0 & 0xfff0) === 0xf830) {
      if ((hw1 >>> 11) & 1) {
        const P = (hw1 >>> 10) & 1, U = (hw1 >>> 9) & 1, W = (hw1 >>> 8) & 1;
        const imm8 = hw1 & 0xff;
        const base = this.regs[rn];
        const offset = U ? imm8 : -imm8;
        const addr = P ? u32(base + offset) : u32(base);
        this.regs[rt] = this.read16(bus, addr);
        if (W) this.regs[rn] = u32(base + offset);
      } else {
        const rm = hw1 & 0xf, imm2 = (hw1 >>> 4) & 0x3;
        this.regs[rt] = this.read16(bus, u32(this.regs[rn] + (this.regs[rm] << imm2)));
      }
      return 2;
    }

    // STRH: hw0=1111 1000 0010 Rn — register (hw1[11]=0) or immediate pre/post.
    if ((hw0 & 0xfff0) === 0xf820) {
      if ((hw1 >>> 11) & 1) {
        const P = (hw1 >>> 10) & 1, U = (hw1 >>> 9) & 1, W = (hw1 >>> 8) & 1;
        const imm8 = hw1 & 0xff;
        const base = this.regs[rn];
        const offset = U ? imm8 : -imm8;
        const addr = P ? u32(base + offset) : u32(base);
        this.write16(bus, addr, this.regs[rt] & 0xffff);
        if (W) this.regs[rn] = u32(base + offset);
      } else {
        const rm = hw1 & 0xf, imm2 = (hw1 >>> 4) & 0x3;
        this.write16(bus, u32(this.regs[rn] + (this.regs[rm] << imm2)), this.regs[rt] & 0xffff);
      }
      return 2;
    }

    // LDRSH: hw0=1111 1001 0011 Rn — register (hw1[11]=0) or immediate pre/post.
    if ((hw0 & 0xfff0) === 0xf930) {
      if ((hw1 >>> 11) & 1) {
        const P = (hw1 >>> 10) & 1, U = (hw1 >>> 9) & 1, W = (hw1 >>> 8) & 1;
        const imm8 = hw1 & 0xff;
        const base = this.regs[rn];
        const offset = U ? imm8 : -imm8;
        const addr = P ? u32(base + offset) : u32(base);
        this.regs[rt] = u32((this.read16(bus, addr) << 16) >> 16);
        if (W) this.regs[rn] = u32(base + offset);
      } else {
        const rm = hw1 & 0xf, imm2 = (hw1 >>> 4) & 0x3;
        this.regs[rt] = u32((this.read16(bus, u32(this.regs[rn] + (this.regs[rm] << imm2))) << 16) >> 16);
      }
      return 2;
    }

    throw new Error(`Unimplemented 32-bit LD/ST: hw0=0x${hw0.toString(16).padStart(4,'0')} hw1=0x${hw1.toString(16).padStart(4,'0')} at PC=0x${pc.toString(16)}`);
  }

  // ─── 32-bit: Data-processing immediate ───────────────────────────────────

  private exec32_dp_imm(hw0: number, hw1: number, _pc: number): number {
    // ARM Thumb-2 32-bit data-processing immediate.
    // hw0[15:11]=11110, hw1[15]=0.
    //
    // hw0[9]=0 → modified immediate  (AND/BIC/ORR/EOR/ADD/ADC/SBC/SUB/RSB + TST/CMP/CMN/TEQ/MOV/MVN)
    // hw0[9]=1 → plain binary immediate (MOVW/MOVT already caught in exec32_data; remaining: ADDW/SUBW/ADR)
    //
    // Field layout (hw0[9]=0, modified immediate):
    //   hw0[10]=i, hw0[8:5]=op, hw0[4]=S, hw0[3:0]=Rn
    //   hw1[15]=0, hw1[14:12]=imm3, hw1[11:8]=Rd, hw1[7:0]=imm8
    //   imm = decodeThumb2Imm((i<<11)|(imm3<<8)|imm8)
    //
    // Field layout (hw0[9]=1, plain binary immediate):
    //   Same field positions but imm12 = (i<<11)|(imm3<<8)|imm8 (no twist decoding)

    const op = (hw0 >>> 5) & 0xf;  // hw0[8:5]: opcode
    const rn  = hw0 & 0xf;          // hw0[3:0]: Rn
    const rd  = (hw1 >>> 8) & 0xf;  // hw1[11:8]: Rd
    const s   = (hw0 >>> 4) & 1;    // hw0[4]: S (update flags)
    const i   = (hw0 >>> 10) & 1;   // hw0[10]: i (extended immediate bit)

    // ── Plain binary immediate (hw0[9]=1): ADDW / SUBW / ADR ────────────
    // MOVW (op=0100) and MOVT (op=1100) are already intercepted in exec32_data.
    if (((hw0 >>> 9) & 1) === 1) {
      const imm12 = (i << 11) | (((hw1 >>> 12) & 0x7) << 8) | (hw1 & 0xff);
      if ((op & 0xd) === 0x0) {
        // ADDW Rd, Rn, #imm12  (or ADR T3: Rn=PC, add)
        const a = rn === 0xf ? u32(_pc + 4) : this.regs[rn];
        const r = u32(a + imm12);
        this.regs[rd] = r;
        if (s) this.setNZCV_add(a, imm12);
      } else if ((op & 0xd) === 0x4) {
        // SUBW Rd, Rn, #imm12  (or ADR T2: Rn=PC, subtract)
        const a = rn === 0xf ? u32(_pc + 4) : this.regs[rn];
        const r = u32(a - imm12);
        this.regs[rd] = r;
        if (s) this.setNZCV_sub(a, imm12);
      } else if (op === 0xe) {
        // UBFX Rd,Rn,#lsb,#width (T1): hw0=0xF3C0|Rn, op=0xE
        // hw1: 0 imm3[14:12] Rd[11:8] imm2[7:6] 1 widthm1[4:0]
        // lsb = {imm3, imm2}  width = widthm1+1
        const imm3    = (hw1 >>> 12) & 0x7;
        const imm2    = (hw1 >>> 6)  & 0x3;
        const lsb     = (imm3 << 2) | imm2;
        const widthm1 = hw1 & 0x1f;
        const width   = widthm1 + 1;
        const mask    = width >= 32 ? 0xFFFFFFFF : ((1 << width) - 1);
        this.regs[rd] = u32((this.regs[rn] >>> lsb) & mask);
      } else if (op === 0xa) {
        // SBFX Rd,Rn,#lsb,#width (T1): hw0=0xF340|Rn, op=0xA
        // Same encoding as UBFX but sign-extends the result
        const imm3    = (hw1 >>> 12) & 0x7;
        const imm2    = (hw1 >>> 6)  & 0x3;
        const lsb     = (imm3 << 2) | imm2;
        const widthm1 = hw1 & 0x1f;
        const width   = widthm1 + 1;
        const mask    = width >= 32 ? 0xFFFFFFFF : ((1 << width) - 1);
        const raw     = (this.regs[rn] >>> lsb) & mask;
        // Sign-extend: shift left to put sign bit at bit31, then arithmetic right shift
        const shift   = 32 - width;
        this.regs[rd] = u32((raw << shift) >> shift);
      } else if (op === 0xb) {
        // BFI Rd,Rn,#lsb,#width (T1) / BFC Rd,#lsb,#width (Rn=1111)
        // hw1: 0 imm3[14:12] Rd[11:8] imm2[7:6] 0 msb[4:0];  lsb={imm3,imm2}
        // BFC is the mask gcc emits for `x & 0xf000` etc.; skipping it left the
        // masked value unchanged (e.g. the ccpu conditional-jump page mask), which
        // silently corrupted the AAE Cinematronics cores on this emulator.
        const imm3 = (hw1 >>> 12) & 0x7;
        const imm2 = (hw1 >>> 6)  & 0x3;
        const lsb  = (imm3 << 2) | imm2;
        const msb  = hw1 & 0x1f;
        if (msb >= lsb) {
          const width     = msb - lsb + 1;
          const fieldMask = u32(width >= 32 ? 0xFFFFFFFF : (((1 << width) - 1) << lsb));
          const cleared   = u32(this.regs[rd] & ~fieldMask);
          this.regs[rd] = rn === 0xf
            ? cleared                                              // BFC: clear field
            : u32(cleared | (u32(this.regs[rn] << lsb) & fieldMask)); // BFI: insert Rn
        }
      }
      // Other plain-binary encodings (SSAT, USAT) — skip
      return 2;
    }

    // ── Modified immediate (hw0[9]=0) ────────────────────────────────────
    const imm3 = (hw1 >>> 12) & 0x7;
    const imm8 = hw1 & 0xff;
    const imm  = decodeThumb2Imm((i << 11) | (imm3 << 8) | imm8);

    switch (op) {
      case 0x0: {  // AND{S} Rd,Rn,#imm  /  TST Rn,#imm (Rd=1111,S=1)
        const r = u32(this.regs[rn] & imm);
        if (rd !== 0xf) this.regs[rd] = r;
        if (s) this.setNZ(r);
        break;
      }
      case 0x1: {  // BIC{S} Rd,Rn,#imm
        const r = u32(this.regs[rn] & ~imm);
        this.regs[rd] = r;
        if (s) this.setNZ(r);
        break;
      }
      case 0x2: {  // ORR{S} Rd,Rn,#imm  /  MOV{S} Rd,#imm (Rn=1111)
        const r = rn === 0xf ? imm : u32(this.regs[rn] | imm);
        this.regs[rd] = r;
        if (s) this.setNZ(r);
        break;
      }
      case 0x3: {  // ORN{S} Rd,Rn,#imm  /  MVN{S} Rd,#imm (Rn=1111)
        const r = rn === 0xf ? u32(~imm) : u32(this.regs[rn] | ~imm);
        this.regs[rd] = r;
        if (s) this.setNZ(r);
        break;
      }
      case 0x4: {  // EOR{S} Rd,Rn,#imm  /  TEQ Rn,#imm (Rd=1111,S=1)
        const r = u32(this.regs[rn] ^ imm);
        if (rd !== 0xf) this.regs[rd] = r;
        if (s) this.setNZ(r);
        break;
      }
      case 0x8: {  // ADD{S} Rd,Rn,#imm  /  CMN Rn,#imm (Rd=1111,S=1)
        const a = this.regs[rn];
        const r = u32(a + imm);
        if (rd !== 0xf) this.regs[rd] = r;
        if (s) this.setNZCV_add(a, imm);
        break;
      }
      case 0xa: {  // ADC{S} Rd,Rn,#imm
        const a = this.regs[rn];
        const c = this.flagC;
        const r = u32(a + imm + c);
        this.regs[rd] = r;
        if (s) {
          const r64 = (a >>> 0) + (imm >>> 0) + c;
          this.setN((r >>> 31) !== 0);
          this.setZ(r === 0);
          this.setC(r64 > 0xffff_ffff);
          this.setV(((~(a ^ imm) & (a ^ r)) >>> 31) !== 0);
        }
        break;
      }
      case 0xb: {  // SBC{S} Rd,Rn,#imm
        const a = this.regs[rn];
        const c = this.flagC;
        const r = u32(a - imm - (1 - c));
        this.regs[rd] = r;
        if (s) this.setNZCV_sub(a, imm);
        break;
      }
      case 0xd: {  // SUB{S} Rd,Rn,#imm  /  CMP Rn,#imm (Rd=1111,S=1)
        const a = this.regs[rn];
        const r = u32(a - imm);
        if (rd !== 0xf) this.regs[rd] = r;
        if (s) this.setNZCV_sub(a, imm);
        break;
      }
      case 0xe: {  // RSB{S} Rd,Rn,#imm
        const a = this.regs[rn];
        const r = u32(imm - a);
        this.regs[rd] = r;
        if (s) this.setNZCV_sub(imm, a);
        break;
      }
      default: break;
    }
    return 2;
  }

  // ─── 32-bit: Data-processing register (shifts, etc.) ─────────────────────

  private exec32_dp_reg(hw0: number, hw1: number): number {
    // hw0[15:9] = 1110 101
    // Handles wide shifts and logical/arithmetic operations.

    const op = (hw0 >>> 5) & 0xf;   // hw0[8:5]
    const s   = (hw0 >>> 4) & 1;
    const rn  = hw0 & 0xf;
    const rd  = (hw1 >>> 8) & 0xf;
    const rm  = hw1 & 0xf;
    const imm3 = (hw1 >>> 12) & 0x7;
    const imm2 = (hw1 >>> 6) & 0x3;
    const shiftType = (hw1 >>> 4) & 0x3;
    const shiftAmt  = (imm3 << 2) | imm2;

    // Shift the Rm value
    let rmVal = this.regs[rm];
    if (shiftAmt > 0) {
      switch (shiftType) {
        case 0: rmVal = this.lsl(rmVal, shiftAmt, false); break;
        case 1: rmVal = this.lsr(rmVal, shiftAmt, false); break;
        case 2: rmVal = this.asr(rmVal, shiftAmt, false); break;
        case 3: rmVal = this.ror(rmVal, shiftAmt, false); break;
      }
    }

    switch (op) {
      case 0x0: {  // AND{S}  /  TST Rn,Rm{,shift} (Rd=15,S=1 → discard result)
        const r = u32(this.regs[rn] & rmVal);
        if (rd !== 15) this.regs[rd] = r;
        if (s) this.setNZ(r);
        break;
      }
      case 0x1: {  // BIC{S}
        const r = u32(this.regs[rn] & ~rmVal);
        this.regs[rd] = r;
        if (s) this.setNZ(r);
        break;
      }
      case 0x2: {  // ORR{S} or MOV (Rn=1111)
        if (rn === 0xf) {
          // MOV{S} Rd, Rm (possibly shifted)
          this.regs[rd] = rmVal;
          if (s) this.setNZ(rmVal);
        } else {
          const r = u32(this.regs[rn] | rmVal);
          this.regs[rd] = r;
          if (s) this.setNZ(r);
        }
        break;
      }
      case 0x3: {  // ORN{S} or MVN (Rn=1111)
        if (rn === 0xf) {
          const r = u32(~rmVal);
          this.regs[rd] = r;
          if (s) this.setNZ(r);
        } else {
          const r = u32(this.regs[rn] | ~rmVal);
          this.regs[rd] = r;
          if (s) this.setNZ(r);
        }
        break;
      }
      case 0x4: {  // EOR{S}  /  TEQ Rn,Rm{,shift} (Rd=15,S=1 → discard result)
        const r = u32(this.regs[rn] ^ rmVal);
        if (rd !== 15) this.regs[rd] = r;
        if (s) this.setNZ(r);
        break;
      }
      case 0x6: {  // LSL (wide) — Rn=1111
        // LSLS.W Rd, Rm, Rn or LSLS Rd, Rm, #imm
        const r = this.lsl(rmVal, this.regs[rn] & 0xff, s !== 0);
        this.regs[rd] = r;
        if (s) this.setNZ(r);
        break;
      }
      case 0x8: {  // ADD{S}  /  CMN Rn,Rm{,shift} (Rd=15,S=1 → discard result)
        const a = this.regs[rn];
        const r = u32(a + rmVal);
        if (rd !== 15) this.regs[rd] = r;
        if (s) this.setNZCV_add(a, rmVal);
        break;
      }
      case 0xa: {  // ADC{S}
        const a = this.regs[rn];
        const c = this.flagC;
        const r = u32(a + rmVal + c);
        this.regs[rd] = r;
        if (s) this.setNZCV_add(a, rmVal + c);
        break;
      }
      case 0xb: {  // SBC{S} Rd,Rn,Rm{,shift} — Rn - Rm - borrow (borrow = 1-C).
        // Was MISSING: fell through to default (no-op). Soft-float __adddf3 uses
        // `sbc.w rX,rX,rX,lsl#1` to conditionally negate a mantissa by the sign
        // (carry) bit; without it, different-sign dadd/dsub added instead of
        // subtracting (5.0-3.0 → 8.0) and __divdf3 was wrong. See [[thumb2-bugs]].
        const a = this.regs[rn];
        const c = this.flagC;
        const r = u32(a - rmVal - (1 - c));
        this.regs[rd] = r;
        if (s) this.setNZCV_sub(a, rmVal + (1 - c));  // approximate borrow flags
        break;
      }
      case 0xd: {  // SUB{S}  /  CMP Rn,Rm{,shift} (Rd=15,S=1 → discard result)
        const a = this.regs[rn];
        const r = u32(a - rmVal);
        if (rd !== 15) this.regs[rd] = r;   // Rd=15 → CMP: flags only, no PC write
        if (s) this.setNZCV_sub(a, rmVal);
        break;
      }
      case 0xe: {  // RSB{S}
        const a = this.regs[rn];
        const r = u32(rmVal - a);
        this.regs[rd] = r;
        if (s) this.setNZCV_sub(rmVal, a);
        break;
      }
      // TST / TEQ / CMP / CMN (no Rd)
      default:
        break;
    }

    return 1;
  }

  // ─── 32-bit: Extend instructions ─────────────────────────────────────────

  private exec32_extend(hw0: number, hw1: number): number {
    const rd = (hw1 >>> 8) & 0xf;
    const rm = hw1 & 0xf;
    const op2 = (hw0 >>> 4) & 0x7;  // hw0[6:4]

    // Rotation for SXTAH/UXTAH etc.
    const rotate = ((hw1 >>> 4) & 0x3) << 3;
    let src = this.regs[rm];
    if (rotate) src = ror32(src, rotate);

    const rn = hw0 & 0xf;

    switch (op2) {
      case 0x0: {  // SXTAH / SXTH.W
        const ext = u32((src << 16) >> 16);
        this.regs[rd] = rn === 0xf ? ext : u32(this.regs[rn] + ext);
        break;
      }
      case 0x1: {  // UXTAH / UXTH.W
        const ext = src & 0xffff;
        this.regs[rd] = rn === 0xf ? ext : u32(this.regs[rn] + ext);
        break;
      }
      case 0x4: {  // SXTAB / SXTB.W
        const ext = u32((src << 24) >> 24);
        this.regs[rd] = rn === 0xf ? ext : u32(this.regs[rn] + ext);
        break;
      }
      case 0x5: {  // UXTAB / UXTB.W
        const ext = src & 0xff;
        this.regs[rd] = rn === 0xf ? ext : u32(this.regs[rn] + ext);
        break;
      }
    }
    return 1;
  }

  // ─── Utility ──────────────────────────────────────────────────────────────

  private bitCount(n: number): number {
    let count = 0;
    n = n | 0;
    while (n) { count += n & 1; n >>>= 1; }
    return count;
  }
}
