/**
 * VsmpPlayer — read-only player for .vsmp voice/sample files.
 *
 * A .vsmp is the Vectrex "voice" track (Spike-style): low-rate 4-bit PCM meant
 * to be streamed to the AY-3-8912 volume register as a crude DAC. Format:
 *   { version, name, sampleRate, bits: 4, numSamples, data: <base64 packed> }
 * The payload is packed 2 samples/byte (low nibble = even sample).
 *
 * This panel decodes it, draws the waveform, and plays it via Web Audio so you
 * can HEAR the exact 4-bit reconstruction the Vectrex would output — no need to
 * run a ROM. Read-only (the .vsmp is generated by tools/audio2vsmp).
 */

import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';

interface VsmpData {
  name: string;
  sampleRate: number;
  numSamples: number;
  bits: number;
  /** Unpacked 4-bit samples as Float32 in [-1, 1]. */
  samples: Float32Array;
}

function base64ToBytes(b64: string): Uint8Array {
  const bin = atob(b64);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}

/** Validate + decode a parsed .vsmp resource into playable Float32 samples. */
function normalizeVsmp(resource: any): VsmpData | null {
  if (!resource || typeof resource !== 'object') return null;
  const sampleRate = Number(resource.sampleRate) || 0;
  const numSamples = Number(resource.numSamples) || 0;
  if (sampleRate <= 0 || numSamples <= 0 || typeof resource.data !== 'string') return null;

  let bytes: Uint8Array;
  try { bytes = base64ToBytes(resource.data); } catch { return null; }

  // Unpack 4-bit nibbles (2/byte, low nibble = even sample) → Float32 [-1, 1].
  const n = Math.min(numSamples, bytes.length * 2);
  const samples = new Float32Array(n);
  for (let i = 0; i < n; i++) {
    const byte = bytes[i >> 1] ?? 0;
    const v = (i & 1) === 0 ? (byte & 0x0f) : ((byte >> 4) & 0x0f);
    samples[i] = (v / 15) * 2 - 1;
  }
  return {
    name: typeof resource.name === 'string' ? resource.name : 'sample',
    sampleRate,
    numSamples: n,
    bits: Number(resource.bits) || 4,
    samples,
  };
}

export const VsmpPlayer: React.FC<{ resource?: any }> = ({ resource }) => {
  const data = useMemo(() => normalizeVsmp(resource), [resource]);

  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const ctxRef = useRef<AudioContext | null>(null);
  const srcRef = useRef<AudioBufferSourceNode | null>(null);
  const startRef = useRef(0); // ctx.currentTime when playback started
  const rafRef = useRef<number | null>(null);

  const [playing, setPlaying] = useState(false);
  const [pos, setPos] = useState(0); // seconds

  const durationSec = data ? data.numSamples / data.sampleRate : 0;

  const stop = useCallback(() => {
    try { srcRef.current?.stop(); srcRef.current?.disconnect(); } catch { /* noop */ }
    srcRef.current = null;
    if (rafRef.current != null) cancelAnimationFrame(rafRef.current);
    rafRef.current = null;
    setPlaying(false);
    setPos(0);
  }, []);

  const play = useCallback(() => {
    if (!data) return;
    if (playing) { stop(); return; }
    let ctx = ctxRef.current;
    if (!ctx) {
      try { ctx = new AudioContext(); ctxRef.current = ctx; }
      catch { return; }
    }
    // Build a buffer at the sample's native rate (the browser resamples on play).
    const buf = ctx.createBuffer(1, data.numSamples, data.sampleRate);
    buf.getChannelData(0).set(data.samples);
    const src = ctx.createBufferSource();
    src.buffer = buf;
    src.connect(ctx.destination);
    src.onended = () => { if (srcRef.current === src) stop(); };
    if (ctx.state !== 'running') ctx.resume().catch(() => {});
    src.start();
    srcRef.current = src;
    startRef.current = ctx.currentTime;
    setPlaying(true);

    const tick = () => {
      const c = ctxRef.current;
      if (!c || srcRef.current !== src) return;
      setPos(Math.min(c.currentTime - startRef.current, durationSec));
      rafRef.current = requestAnimationFrame(tick);
    };
    rafRef.current = requestAnimationFrame(tick);
  }, [data, playing, stop, durationSec]);

  // Stop audio on unmount / when the file changes.
  useEffect(() => () => stop(), [stop, resource]);

  // Draw the waveform (peak-per-column downsample).
  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas || !data) return;
    const dpr = window.devicePixelRatio || 1;
    const W = canvas.clientWidth, H = canvas.clientHeight;
    canvas.width = Math.floor(W * dpr);
    canvas.height = Math.floor(H * dpr);
    const g = canvas.getContext('2d');
    if (!g) return;
    g.scale(dpr, dpr);
    g.clearRect(0, 0, W, H);
    g.fillStyle = '#0d0d14';
    g.fillRect(0, 0, W, H);
    // midline
    g.strokeStyle = '#233';
    g.beginPath(); g.moveTo(0, H / 2); g.lineTo(W, H / 2); g.stroke();

    const s = data.samples;
    const step = Math.max(1, Math.floor(s.length / W));
    g.strokeStyle = '#4ad0a0';
    g.lineWidth = 1;
    g.beginPath();
    for (let x = 0; x < W; x++) {
      let min = 1, max = -1;
      const start = x * step;
      for (let i = 0; i < step && start + i < s.length; i++) {
        const v = s[start + i];
        if (v < min) min = v;
        if (v > max) max = v;
      }
      const y0 = H / 2 - max * (H / 2 - 2);
      const y1 = H / 2 - min * (H / 2 - 2);
      g.moveTo(x + 0.5, y0);
      g.lineTo(x + 0.5, y1);
    }
    g.stroke();
  }, [data]);

  if (!data) {
    return (
      <div style={S.wrap}>
        <div style={S.msg}>
          <span style={{ fontSize: 28 }}>🎙️</span>
          <span>Not a valid .vsmp sample (need sampleRate, numSamples and base64 data).</span>
        </div>
      </div>
    );
  }

  const progressPct = durationSec > 0 ? (pos / durationSec) * 100 : 0;
  const sizeKb = Math.round((data.numSamples + 1) / 2 / 1024);

  return (
    <div style={S.wrap}>
      <div style={S.header}>
        <span style={{ fontSize: 22 }}>🎙️</span>
        <b style={{ color: '#cfe' }}>{data.name}</b>
        <span style={S.meta}>
          {data.numSamples.toLocaleString()} samples · {data.sampleRate.toLocaleString()} Hz ·{' '}
          {durationSec.toFixed(1)}s · {data.bits}-bit · {sizeKb} KB
        </span>
      </div>

      <div style={{ position: 'relative', margin: '10px 0' }}>
        <canvas ref={canvasRef} style={S.canvas} />
        {/* playhead */}
        <div style={{ ...S.playhead, left: `${progressPct}%`, opacity: playing ? 1 : 0 }} />
      </div>

      <div style={S.controls}>
        <button style={{ ...S.btn, background: playing ? '#4a2a2a' : '#2a4a2a', color: playing ? '#faa' : '#afa' }}
          onClick={play}>
          {playing ? '⏹ Stop' : '▶ Play'}
        </button>
        <div style={S.track}>
          <div style={{ ...S.trackFill, width: `${progressPct}%` }} />
        </div>
        <span style={{ color: '#9ab', fontSize: 12, fontVariantNumeric: 'tabular-nums', minWidth: 92, textAlign: 'right' }}>
          {pos.toFixed(1)} / {durationSec.toFixed(1)}s
        </span>
      </div>

      <div style={S.note}>
        Plays the exact 4-bit reconstruction the Vectrex would output — rough but recognizable.
        Read-only; regenerate with <code style={{ color: '#dd8' }}>tools/audio2vsmp</code>.
      </div>
    </div>
  );
};

const S: Record<string, React.CSSProperties> = {
  wrap: { background: '#0d0d14', color: '#cde', height: '100%', width: '100%', padding: 18, boxSizing: 'border-box', display: 'flex', flexDirection: 'column', fontFamily: 'system-ui, sans-serif' },
  header: { display: 'flex', alignItems: 'center', gap: 10, flexWrap: 'wrap' },
  meta: { color: '#89a', fontSize: 12 },
  canvas: { width: '100%', height: 220, display: 'block', border: '1px solid #223', borderRadius: 6 },
  playhead: { position: 'absolute', top: 0, bottom: 0, width: 2, background: '#8fd', pointerEvents: 'none', transition: 'opacity .2s' },
  controls: { display: 'flex', alignItems: 'center', gap: 12 },
  btn: { border: '1px solid #333', borderRadius: 5, padding: '6px 16px', cursor: 'pointer', fontSize: 13, fontWeight: 600 },
  track: { flex: 1, height: 6, background: '#1a1a26', borderRadius: 3, overflow: 'hidden' },
  trackFill: { height: '100%', background: '#4ad0a0' },
  note: { color: '#667', fontSize: 11, marginTop: 12 },
  msg: { display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 10, justifyContent: 'center', height: '100%', color: '#9ab' },
};
