#!/usr/bin/env python3
"""Generate uvm2_font.h from the emulator's vector font.

The 4x6 stroke font already exists as TypeScript data in
ide/frontend/src/emulator/systems/vectorFont.ts (and, out of reach in another
repo, in the cartridge firmware).  Rather than hand-copy it a third time, this
derives the C table from that file so the two can never silently drift: if a
glyph changes, re-run this and commit the result.

    ./gen_font.py            # writes ../uvm2_font.h
"""
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
SOURCE = HERE / "../../../../../ide/frontend/src/emulator/systems/vectorFont.ts"
OUTPUT = HERE / ".." / "uvm2_font.h"

FIRST, LAST = 32, 90          # the range the font covers


def parse(text):
    glyphs = {}
    for m in re.finditer(r"^\s*(\d+):\s*\[([0-9,\s]*)\]", text, re.M):
        code = int(m.group(1))
        body = [int(v) for v in m.group(2).replace(" ", "").split(",") if v != ""]
        if len(body) % 3:
            sys.exit(f"glyph {code}: stroke list is not a multiple of 3")
        glyphs[code] = body
    return glyphs


def main():
    src = SOURCE.resolve()
    if not src.exists():
        sys.exit(f"font source not found: {src}")
    glyphs = parse(src.read_text())
    if not glyphs:
        sys.exit("no glyphs parsed — has vectorFont.ts changed shape?")

    data, offsets, lengths = [], [], []
    for code in range(FIRST, LAST + 1):
        strokes = glyphs.get(code, [])
        offsets.append(len(data))
        lengths.append(len(strokes))
        data.extend(strokes)

    out = []
    out.append("/* GENERATED by tools/gen_font.py — do not edit by hand.")
    out.append(" * Source: ide/frontend/src/emulator/systems/vectorFont.ts")
    out.append(" *")
    out.append(" * 4x6 stroke font, ASCII %d..%d. Strokes are [cmd, gx, gy] triples with" % (FIRST, LAST))
    out.append(" * cmd 1 = move (beam off), 2 = draw; gx 0..4, gy 0..6 with y=0 at the")
    out.append(" * bottom. Lowercase folds to uppercase at lookup time. */")
    out.append("#ifndef UVM2_FONT_H")
    out.append("#define UVM2_FONT_H")
    out.append("")
    out.append("#include <stdint.h>")
    out.append("")
    out.append("#define UVM2_FONT_FIRST %d" % FIRST)
    out.append("#define UVM2_FONT_LAST  %d" % LAST)
    out.append("")
    out.append("static const uint8_t uvm2_font_data[] = {")
    for i in range(0, len(data), 24):
        out.append("    " + ",".join(str(v) for v in data[i:i + 24]) + ",")
    out.append("};")
    out.append("")
    out.append("static const uint16_t uvm2_font_offset[] = {")
    for i in range(0, len(offsets), 16):
        out.append("    " + ",".join(str(v) for v in offsets[i:i + 16]) + ",")
    out.append("};")
    out.append("")
    out.append("static const uint8_t uvm2_font_length[] = {")
    for i in range(0, len(lengths), 16):
        out.append("    " + ",".join(str(v) for v in lengths[i:i + 16]) + ",")
    out.append("};")
    out.append("")
    out.append("#endif /* UVM2_FONT_H */")

    OUTPUT.resolve().write_text("\n".join(out) + "\n")
    print(f"wrote {OUTPUT.resolve()}  ({len(glyphs)} glyphs, {len(data)} stroke bytes)")


if __name__ == "__main__":
    main()
