//! UVM2 Bus Helpers — CLK-synchronized VIA writes via GPIO bit-bang
//!
//! Architecture (per Ralf, 2026-04-17):
//!   - 6809 is halted (asserts /HALT via GPIO27)
//!   - 6809 still generates the 1.5 MHz CLK even in HALT mode
//!   - RP2350 must sync with CLK: after a CLK edge, set A+D+R/W, then
//!     the NEXT CLK edge causes the VIA to latch the write
//!
//! GPIO layout (Ralf, 2026-04-16):
//!   GPIO 0-7   = D0-D7   (data bus, bidirectional)
//!   GPIO 8-21  = A1-A14  (address bus, A0 not connected — see NOTE)
//!   GPIO 22    = PB6
//!   GPIO 23    = /IRQ    (input)
//!   GPIO 24    = A14 dup (/CART detect)
//!   GPIO 25    = A15
//!   GPIO 26    = R/W     (1=read, 0=write)
//!   GPIO 27    = /HALT   (assert LOW to take bus)
//!   GPIO 29    = /NMI    (input)
//!   GPIO 31    = CLK     (1.5 MHz, generated by 6809 even in HALT)
//!
//! NOTE on A0: A0 is not wired to the RP2350 GPIO. VIA register select
//! uses RS0=A0, so odd-addressed VIA registers ($D001, $D003, $D005, …)
//! differ from even ones only in A0. With A0 missing, the RP2350 cannot
//! independently address them via bit-bang. Confirm with Ralf if Port A
//! ($D001) or other odd VIA registers are needed.
//!
//! RP2350 SIO register offsets (from 0xD0000000):
//!   +0x004 = GPIO_IN        read GPIO0-31
//!   +0x010 = GPIO_OUT       set all output values (non-atomic)
//!   +0x014 = GPIO_SET       atomic: set bits high
//!   +0x018 = GPIO_CLR       atomic: clear bits low
//!   +0x024 = GPIO_OE_SET    enable output drivers
//!   +0x028 = GPIO_OE_CLR    disable output drivers (→ input / Hi-Z)

/// Emit all UVM2 bus helper functions.
pub fn emit_uvm2_bus_helpers() -> String {
    let mut s = String::new();
    s.push_str("@ ================================================================\n");
    s.push_str("@ UVM2 Bus Helpers — CLK-synchronized VIA bus mastering\n");
    s.push_str("@ Option A: uvm2_via_read  — real CLK-synced read from VIA bus\n");
    s.push_str("@ Option B: uvm2_timer_wait — fixed spin-delay (no read needed)\n");
    s.push_str("@ bus_read shim selects one; see uvm2/mod.rs emit_uvm2_bus_shims()\n");
    s.push_str("@ ================================================================\n\n");
    s.push_str(&emit_bus_init());
    s.push_str(&emit_via_write());
    s.push_str(&emit_via_read());
    s.push_str(&emit_timer_wait());
    s
}

// ── uvm2_bus_init ─────────────────────────────────────────────────────────────

fn emit_bus_init() -> String {
    // OUTPUT ENABLE mask:
    //   A1-A14  (GPIO 8-21)  = 0x003FFF00
    //   A15     (GPIO 25)    = 0x02000000
    //   R/W     (GPIO 26)    = 0x04000000
    //   /HALT   (GPIO 27)    = 0x08000000
    //   Total                = 0x0E3FFF00
    //
    // Data (GPIO 0-7) start as inputs; we switch them to output only
    // during a write, and back to input afterwards.
    r#"@ uvm2_bus_init ── configure GPIO directions for UVM2 bus mastering.
@ Must be called once at startup.  Assumes firmware has already muxed
@ GPIO pads to SIO function (standard Pico SDK board setup).
@ No arguments.  Clobbers r0, r1.
.global uvm2_bus_init
.thumb_func
uvm2_bus_init:
    ldr  r0, =0xD0000000    @ SIO_BASE

    @ Pre-drive /HALT and R/W HIGH before enabling outputs.
    @ This avoids a glitch that would spuriously freeze the 6809.
    ldr  r1, =0x0C000000    @ (1<<26) R/W | (1<<27) /HALT
    str  r1, [r0, #0x14]    @ SIO_GPIO_SET

    @ Enable output drivers for address + control lines.
    @ Data bus (GPIO0-7) stays as input until an explicit write.
    ldr  r1, =0x0E3FFF00    @ A1-A14 + A15 + R/W + /HALT
    str  r1, [r0, #0x24]    @ SIO_GPIO_OE_SET

    bx   lr

"#
    .to_string()
}

// ── uvm2_via_write ────────────────────────────────────────────────────────────

fn emit_via_write() -> String {
    // Address → GPIO mapping:
    //   GPIO8 = A1  →  address bit 1
    //   GPIO9 = A2  →  address bit 2
    //   …
    //   GPIO21 = A14 →  address bit 14
    //
    //   gpio_addr = (addr << 7) & ADDR_MASK   (ADDR_MASK = 0x003FFF00)
    //
    //   e.g. VIA_PORT_A at $D001:
    //     $D001 << 7 = 0x68_0080; & 0x003FFF00 = 0x00280000
    //     bits 21 (A14) and 19 (A12) set → correct chip-select
    //
    // Full GPIO clear mask for "all bus lines":
    //   D0-D7 (0xFF) | A1-A14 (0x003FFF00) | A15 (1<<25) | R/W (1<<26)
    //   = 0x063FFFFF
    //
    // Sequence (Ralf, 2026-04-17):
    //   1. Assert /HALT (GPIO27 = LOW)
    //   2. Wait for CLK LOW  (GPIO31 = 0)
    //   3. Set A1-A14, A15, D0-D7, R/W=0  (GPIO outputs)
    //   4. Wait for CLK HIGH (rising edge) → VIA latches the write
    //   5. Release data bus → inputs, R/W = 1, /HALT = HIGH
    r#"@ uvm2_via_write ── write one byte to a Vectrex VIA register.
@
@   r0 = VIA address  (e.g. 0xD001 for PORT_A, 0xD00B for ACR)
@   r1 = data byte
@
@ Clobbers: r2, r3, r4, r5  (r4, r5 preserved via push/pop)
.global uvm2_via_write
.thumb_func
uvm2_via_write:
    push    {r4, r5, lr}

    ldr     r4, =0xD0000000         @ SIO_BASE

    @ ── Step 1: Assert /HALT (take bus from 6809) ──────────────────────
    mov     r5, #(1 << 27)          @ /HALT pin mask
    str     r5, [r4, #0x18]         @ SIO_GPIO_CLR → GPIO27 = 0

    @ ── Step 2: Wait for CLK LOW (GPIO31 = 0) ──────────────────────────
.Luvm2_vw_wait_lo:
    ldr     r2, [r4, #0x04]         @ SIO_GPIO_IN
    tst     r2, #0x80000000         @ bit 31 = CLK
    bne     .Luvm2_vw_wait_lo       @ loop while CLK = 1

    @ ── Step 3: Build GPIO output word ─────────────────────────────────
    @ A1-A14 at GPIO8-21:  (addr << 7) & 0x003FFF00
    lsl     r2, r0, #7
    ldr     r3, =0x003FFF00         @ ADDR_MASK (GPIO8-21)
    and     r2, r2, r3

    @ A15 = 1 (all VIA addresses have A15=1, VIA lives at $D000-$D00F)
    orr     r2, r2, #(1 << 25)

    @ D0-D7 = data byte
    and     r3, r1, #0xFF
    orr     r2, r2, r3              @ R/W (GPIO26) = 0 by absence

    @ Atomically clear all bus lines, then set the new values.
    ldr     r3, =0x063FFFFF         @ D0-D7 | A1-A14 | A15 | R/W
    str     r3, [r4, #0x18]         @ SIO_GPIO_CLR
    str     r2, [r4, #0x14]         @ SIO_GPIO_SET

    @ Switch D0-D7 to output
    ldr     r3, =0x000000FF
    str     r3, [r4, #0x24]         @ SIO_GPIO_OE_SET

    @ ── Step 4: Wait for CLK HIGH (rising edge → VIA latches write) ────
.Luvm2_vw_wait_hi:
    ldr     r2, [r4, #0x04]         @ SIO_GPIO_IN
    tst     r2, #0x80000000
    beq     .Luvm2_vw_wait_hi       @ loop while CLK = 0

    @ ── Step 5: Release bus ─────────────────────────────────────────────
    @ D0-D7 back to input
    ldr     r3, =0x000000FF
    str     r3, [r4, #0x28]         @ SIO_GPIO_OE_CLR

    @ R/W = 1 (idle)
    mov     r3, #(1 << 26)
    str     r3, [r4, #0x14]         @ SIO_GPIO_SET

    @ /HALT = 1 (release 6809)
    mov     r3, #(1 << 27)
    str     r3, [r4, #0x14]         @ SIO_GPIO_SET

    pop     {r4, r5, pc}

"#
    .to_string()
}

// ── OPTION A: uvm2_via_read ───────────────────────────────────────────────────

fn emit_via_read() -> String {
    // Same CLK sync as via_write but R/W=1 (read cycle).
    // After rising CLK edge the VIA drives D0-D7; we sample GPIO_IN bits 0-7.
    r#"@ ── OPTION A ──────────────────────────────────────────────────────────────
@ uvm2_via_read ── read one byte from a Vectrex VIA register (CLK-synced).
@
@   r0 = VIA address  (e.g. 0xD00D for IFR)
@ Returns:
@   r0 = data byte read from bus
@
@ Clobbers: r2, r3, r4, r5  (r4, r5 preserved via push/pop)
.global uvm2_via_read
.thumb_func
uvm2_via_read:
    push    {r4, r5, lr}

    ldr     r4, =0xD0000000         @ SIO_BASE

    @ Assert /HALT
    mov     r5, #(1 << 27)
    str     r5, [r4, #0x18]         @ SIO_GPIO_CLR → GPIO27 = 0

    @ Wait for CLK LOW
.Luvm2_vr_wait_lo:
    ldr     r2, [r4, #0x04]
    tst     r2, #0x80000000
    bne     .Luvm2_vr_wait_lo

    @ Build address word: (addr << 7) & ADDR_MASK, A15=1
    lsl     r2, r0, #7
    ldr     r3, =0x003FFF00
    and     r2, r2, r3
    orr     r2, r2, #(1 << 25)      @ A15 = 1

    @ Clear all bus lines, then set address
    ldr     r3, =0x063FFFFF
    str     r3, [r4, #0x18]         @ SIO_GPIO_CLR
    str     r2, [r4, #0x14]         @ SIO_GPIO_SET (no D0-D7, R/W implicit HIGH)

    @ R/W = 1 (read) — ensure high
    mov     r3, #(1 << 26)
    str     r3, [r4, #0x14]

    @ D0-D7 as input (already input from init, ensure OE off)
    ldr     r3, =0x000000FF
    str     r3, [r4, #0x28]         @ SIO_GPIO_OE_CLR

    @ Wait for CLK HIGH — VIA drives D0-D7 on this edge
.Luvm2_vr_wait_hi:
    ldr     r2, [r4, #0x04]
    tst     r2, #0x80000000
    beq     .Luvm2_vr_wait_hi

    @ Sample D0-D7 (GPIO bits 0-7)
    ldr     r0, [r4, #0x04]         @ SIO_GPIO_IN
    and     r0, r0, #0xFF

    @ Release bus
    ldr     r3, =0x063FFF00         @ clear address lines
    str     r3, [r4, #0x18]
    mov     r3, #(1 << 27)          @ /HALT = 1
    str     r3, [r4, #0x14]

    pop     {r4, r5, pc}

"#
    .to_string()
}

// ── OPTION B: uvm2_timer_wait ─────────────────────────────────────────────────

fn emit_timer_wait() -> String {
    // The drawing code programs T1 with T1L_L=$7F, T1C_H=$00 → 127+2=129 Vectrex
    // clock cycles = 129 / 1.5MHz = 86 µs.  At 150 MHz RP2350: 86e-6 * 150e6 = 12,900 cycles.
    // We add 20% margin → 15,500 cycles.  Each loop iteration = 2 instructions = 2 cycles.
    // So loop count = 15500 / 2 = 7750.
    //
    // Usage: call uvm2_timer_wait INSTEAD OF polling bus_read($D00D).
    // The caller checks r0 & 0x40; we always return 0x40 (done) after the delay.
    r#"@ ── OPTION B ──────────────────────────────────────────────────────────────
@ uvm2_timer_wait ── spin-delay equivalent to VIA T1 at $7F/$00 (86 µs).
@ Returns r0 = 0x40 (mimics IFR bit6 set = timer done).
@ No bus access needed — the VIA timer is still ticking independently.
@ At 150 MHz RP2350, 86 µs = 12,900 cycles; +20% margin = 15,500 cycles.
.global uvm2_timer_wait
.thumb_func
uvm2_timer_wait:
    ldr     r0, =7750               @ loop count (2 cycles/iteration × 7750 = 15500)
.Luvm2_tw_loop:
    subs    r0, r0, #1
    bne     .Luvm2_tw_loop
    mov     r0, #0x40               @ return IFR=done to satisfy tst r0,#0x40
    bx      lr

"#
    .to_string()
}
