//! UVM2 (Ultimate Vectrex Multicart 2) Code Generator
//!
//! ARM Thumb2 / Cortex-M33 backend for the UVM2 cartridge by Ralf & Jason.
//! Reuses all ARM codegen (functions, builtins, assets, drawing) from the
//! `arm` module — only the GPIO pin constants differ from our debug cart.
//!
//! UVM2 GPIO pinout (from Ralf, 2026-04-16):
//!   IO00-IO07 = D0-D7   (data bus)
//!   IO08-IO21 = A0-A13  (address bus — A0 IS connected at GPIO8, corrected 2026-05-04)
//!   IO22      = PB6     (VIA Port B bit 6, beam/blank control)
//!   IO23      = /IRQ
//!   IO24      = A14
//!   IO25      = A15
//!   IO26      = R/W
//!   IO27      = /HALT   (RP2350 can assert this to take bus ownership)
//!   IO29      = /NMI
//!   IO31      = CLK     (system clock, 1.5MHz Vectrex)
//!
//! Standard Pico SDK toolchain:
//!   arm-none-eabi-gcc -mcpu=cortex-m33 -mthumb -mfloat-abi=softfp -mfpu=fpv5-sp-d16
//!
//! Deploy: generate UF2 with standard Pico SDK uf2conv.py, or copy binary to SD card
//! (the UVM2 firmware loads SD binaries as RAM-resident code).

use vpy_parser::Module;
use crate::AssetInfo;
use crate::arm::{
    header, ram_layout, functions, builtins, drawing, assets,
};

/// Entry point: generate a Thumb2 .s file targeting the UVM2 cartridge.
pub fn generate_uvm2_asm(
    module: &Module,
    title: &str,
    asset_list: &[AssetInfo],
) -> Result<String, String> {
    let mut asm = String::new();

    asm.push_str(&format!(
        "@ VPy — ARM Thumb2 target (UVM2 / Ultimate Vectrex Multicart 2)\n\
         @ Game: {}\n\
         @ Generated by vpy_codegen uvm2 backend\n\
         @ Assemble with: arm-none-eabi-as -mthumb -mcpu=cortex-m33 game.s -o game.o\n\n",
        title
    ));

    asm.push_str(".syntax unified\n");
    asm.push_str(".cpu cortex-m33\n");
    asm.push_str(".fpu fpv5-sp-d16\n");
    asm.push_str(".thumb\n\n");

    // ARM Cortex-M vector table — MUST be the very first bytes at 0x20000000.
    // UVM2 firmware reads:
    //   word 0: initial SP  → loaded into MSP before jump
    //   word 1: Reset_Handler (Thumb addr = game_main | 1) → firmware jumps here
    // Without this, the firmware sets SP to random bytes and crashes.
    // Bajo el pico-sdk (UVM2_PICO_RUNTIME) NADA de esto se emite: el crt0 pone su
    // propia tabla de vectores y su propio IMAGE_DEF, y dos IMAGE_DEF en la misma
    // imagen se estorban. `isr_svcall` es weak en el crt0, asi que uvm2_svc_handler
    // lo sustituye sin que hagamos nada.
    //
    // Requiere que el fichero se ensamble con gcc y extension .S, para que pase por
    // el preprocesador. Con .s y arm-none-eabi-as estas lineas serian texto muerto
    // y la guarda no haria nada — silenciosamente.
    asm.push_str("#ifndef UVM2_PICO_RUNTIME\n");
    asm.push_str("@ === ARM Cortex-M vector table (required by UVM2 firmware) ===\n");
    asm.push_str(".section .vectors, \"ax\"\n");
    asm.push_str(".align 2\n");
    asm.push_str(".word 0x20082000        @ Initial SP = top of RP2350 SRAM (520KB)\n");
    asm.push_str(".word game_main + 1     @ Reset_Handler (Thumb bit set)\n");
    // Minimal remaining Cortex-M33 vectors (16 system + 52 IRQ = 68 words total).
    // Point all unused handlers at a safe infinite-loop stub defined below.
    // Vector 11 (SVCall) is the whole point: every VPy builtin is an `svc #N`,
    // and uvm2_svc_handler (uvm2-sdk/uvm2_svc_entry.s) is the UVM2
    // implementation of the same syscall ABI the cartridge firmware and the IDE
    // emulator implement. Leave it on the default stub and the first
    // WAIT_RECAL parks the game in an infinite loop.
    for name in &["NMI","HardFault","MemManage","BusFault","UsageFault",
                  "SecureFault","_reserved7","_reserved8","_reserved9",
                  "SVC","DebugMon","_reserved11","PendSV","SysTick"] {
        if *name == "SVC" {
            asm.push_str(".word uvm2_svc_handler   @ SVCall → UVM2 syscall ABI\n");
        } else {
            asm.push_str(&format!(".word _uvm2_default_handler @ {}\n", name));
        }
    }
    // 52 external IRQs
    asm.push_str(".rept 52\n.word _uvm2_default_handler\n.endr\n");
    // === IMAGE_DEF ===
    // El RP2350 no reconoce una imagen sin este bloque, y sin reconocerla no la
    // ejecuta: LED apagado, pantalla negra, ni una pista. Es la SEGUNDA vez que
    // nos rompe la cadena UVM2 — la primera se tapo compilando aquel objetivo con
    // el pico-sdk, que lo emite solo; estos dos emisores escritos a mano no.
    //
    // MEDIDO: Asteroids_0_1a.um2 y Centipede_0_3a.um2 —las dos imagenes de
    // referencia que SI arrancan— lo llevan en payload+0x15c, y las siete palabras
    // son identicas byte a byte en ambas. Ninguna imagen nuestra lo tenia.
    //
    // El gemelo de esto vive en uvm2-sdk/uvm2_start.s (camino C/SBT). Los dos
    // tienen que decir lo mismo.
    asm.push_str(".word 0xffffded3        @ marca de inicio de bloque\n");
    asm.push_str(".word 0x10210142        @ IMAGE_DEF: ejecutable, ARM, RP2350\n");
    asm.push_str(".word 0x00000203        @ item VECTOR_TABLE, 2 palabras\n");
    asm.push_str(".word 0x20000000        @   -> la tabla esta en la base de la carga\n");
    asm.push_str(".word 0x000003ff        @ LAST_ITEM\n");
    asm.push_str(".word 0x00000000        @ sin bloque siguiente\n");
    asm.push_str(".word 0xab123579        @ marca de fin\n");
    asm.push_str("#endif  /* UVM2_PICO_RUNTIME */\n");
    // El envoltorio del pico-sdk (uvm2_pico_main.c) llama a uvm2_game_main(). En
    // el camino propio la tabla de vectores apunta a game_main. Un alias deja los
    // dos caminos contentos sin duplicar codigo ni renombrar nada.
    asm.push_str(".global uvm2_game_main\n");
    asm.push_str(".thumb_set uvm2_game_main, game_main\n");
    asm.push_str("\n");
    // Default handler: safe infinite loop (avoids runaway on unexpected exceptions)
    asm.push_str(".thumb_func\n_uvm2_default_handler:\n    b _uvm2_default_handler\n\n");
    // NOTE: base address matches uvm2_game.ld VPY_RAM region (0x2007C000)
    asm.push_str(&ram_layout::emit_ram_layout());

    // VIA register addresses (Vectrex bus — same hardware, same addresses)
    asm.push_str(&emit_via_constants());

    asm.push_str(".section .game_rom, \"ax\"\n");
    asm.push_str(".align 2\n\n");

    asm.push_str(&header::emit_image_def());

    // Usage analysis (shared with the arm target): emit runtime routines only
    // when the program actually uses them. Core stubs are always emitted.
    let usage = crate::arm::analysis::analyze(module);

    // Recordings (.vrec) are usage-filtered (shared with the arm target).
    let asset_list = assets::filter_recording_assets(asset_list, module);
    // Audio samples (.vsmp) usage-filtered the same way (shared with arm target).
    let asset_list = assets::filter_sample_assets(&asset_list, module);
    let asset_list = asset_list.as_slice();

    // Identical to the arm target: bus_write/bus_read are the SYS_BUS_WRITE /
    // SYS_BUS_READ syscalls. On UVM2 they land in uvm2_svc.c, which performs a
    // real halt-mode VIA cycle — same ABI, different implementation.
    asm.push_str(&crate::arm::helpers::emit_helpers(&usage));
    asm.push_str(&drawing::emit_drawing(&usage));

    let msg_entries = builtins::collect_msg_entries(module);
    asm.push_str(&builtins::emit_builtins(&msg_entries, &usage));

    asm.push_str(&functions::emit_functions(module, asset_list, &usage)?);
    asm.push_str(&assets::emit_arm_assets(asset_list));

    // Expand cbz, then inject the runtime bring-up call at start of game_main
    let expanded = crate::arm::expand_cbz_pub(&asm);
    inject_runtime_init(&expanded)
}

// ── VIA constants (same addresses — it's the same Vectrex VIA chip) ──────────

fn emit_via_constants() -> String {
    let mut s = String::from("@ --- VIA 6522 registers (Vectrex bus addresses) ---\n");
    s.push_str(".equ VIA_BASE,       0xD000\n");
    s.push_str(".equ VIA_PORT_B,     0xD000\n");
    s.push_str(".equ VIA_PORT_A,     0xD001\n");
    s.push_str(".equ VIA_DDR_B,      0xD002\n");
    s.push_str(".equ VIA_DDR_A,      0xD003\n");
    s.push_str(".equ VIA_T1C_L,      0xD004\n");
    s.push_str(".equ VIA_T1C_H,      0xD005\n");
    s.push_str(".equ VIA_T1L_L,      0xD006\n");
    s.push_str(".equ VIA_T1L_H,      0xD007\n");
    s.push_str(".equ VIA_SR,         0xD00A\n");
    s.push_str(".equ VIA_ACR,        0xD00B\n");
    s.push_str(".equ VIA_PCR,        0xD00C\n");
    s.push_str(".equ VIA_IFR,        0xD00D\n");
    s.push_str(".equ VIA_IER,        0xD00E\n");
    s.push_str("\n@ VIA Port B bits\n");
    s.push_str(".equ PB_MUX,         0x01\n");
    s.push_str(".equ PB_BEAM,        0x08\n");
    s.push_str(".equ PB_ZPULSE,      0x10\n");
    s.push_str("\n@ VIA ACR / PCR values\n");
    s.push_str(".equ ACR_SR_SHIFT,   0x18\n");
    s.push_str(".equ PCR_BEAM_OFF,   0xCE\n");
    s.push_str(".equ PCR_BEAM_ON,    0xDE\n");
    s.push_str(".equ T1_STANDARD,    0x7F\n");
    s.push_str("\n");
    s
}

// ── Post-processing ───────────────────────────────────────────────────────────

/// Inject `bl uvm2_runtime_init` as the very first instruction of `game_main`.
/// That call (uvm2-sdk/uvm2_svc.c) takes over the vector table and interrupts,
/// configures the pads, halts the 6809 and primes the VIA — all of which must
/// happen before any syscall runs.  If the shared ARM codegen ever changes
/// game_main's prologue the patch must fail loudly: silently skipping it
/// produces an image that boots into an unconfigured bus and does nothing.
fn inject_runtime_init(asm: &str) -> Result<String, String> {
    const ANCHOR: &str = "game_main:\n    push    {r4,";
    if !asm.contains(ANCHOR) {
        return Err("uvm2: could not inject uvm2_runtime_init — game_main prologue \
                    changed in arm::functions (expected `push {r4, ...}`)".to_string());
    }
    Ok(asm.replace(
        ANCHOR,
        "game_main:\n    bl      uvm2_runtime_init\n    push    {r4,",
    ))
}
