//! UVM2 (Ultimate Vectrex Multicart 2) Code Generator
//!
//! ARM Thumb2 / Cortex-M33 backend for the UVM2 cartridge by Ralf & Jason.
//! Reuses all ARM codegen (functions, builtins, assets, drawing) from the
//! `arm` module — only the GPIO pin constants differ from our debug cart.
//!
//! UVM2 GPIO pinout (from Ralf, 2026-04-16):
//!   IO00-IO07 = D0-D7   (data bus)
//!   IO08-IO21 = A0-A13  (address bus — A0 IS connected at GPIO8, corrected 2026-05-04)
//!   IO22      = PB6     (VIA Port B bit 6, beam/blank control)
//!   IO23      = /IRQ
//!   IO24      = A14
//!   IO25      = A15
//!   IO26      = R/W
//!   IO27      = /HALT   (RP2350 can assert this to take bus ownership)
//!   IO29      = /NMI
//!   IO31      = CLK     (system clock, 1.5MHz Vectrex)
//!
//! Standard Pico SDK toolchain:
//!   arm-none-eabi-gcc -mcpu=cortex-m33 -mthumb -mfloat-abi=softfp -mfpu=fpv5-sp-d16
//!
//! Deploy: generate UF2 with standard Pico SDK uf2conv.py, or copy binary to SD card
//! (the UVM2 firmware loads SD binaries as RAM-resident code).

pub mod bus;

use vpy_parser::Module;
use crate::AssetInfo;
use crate::arm::{
    header, ram_layout, functions, builtins, drawing, assets,
};

/// Entry point: generate a Thumb2 .s file targeting the UVM2 cartridge.
pub fn generate_uvm2_asm(
    module: &Module,
    title: &str,
    asset_list: &[AssetInfo],
) -> Result<String, String> {
    let mut asm = String::new();

    asm.push_str(&format!(
        "@ VPy — ARM Thumb2 target (UVM2 / Ultimate Vectrex Multicart 2)\n\
         @ Game: {}\n\
         @ Generated by vpy_codegen uvm2 backend\n\
         @ Assemble with: arm-none-eabi-as -mthumb -mcpu=cortex-m33 game.s -o game.o\n\n",
        title
    ));

    asm.push_str(".syntax unified\n");
    asm.push_str(".cpu cortex-m33\n");
    asm.push_str(".fpu fpv5-sp-d16\n");
    asm.push_str(".thumb\n\n");

    // ARM Cortex-M vector table — MUST be the very first bytes at 0x20000000.
    // UVM2 firmware reads:
    //   word 0: initial SP  → loaded into MSP before jump
    //   word 1: Reset_Handler (Thumb addr = game_main | 1) → firmware jumps here
    // Without this, the firmware sets SP to random bytes and crashes.
    asm.push_str("@ === ARM Cortex-M vector table (required by UVM2 firmware) ===\n");
    asm.push_str(".section .vectors, \"ax\"\n");
    asm.push_str(".align 2\n");
    asm.push_str(".word 0x20082000        @ Initial SP = top of RP2350 SRAM (520KB)\n");
    asm.push_str(".word game_main + 1     @ Reset_Handler (Thumb bit set)\n");
    // Minimal remaining Cortex-M33 vectors (16 system + 52 IRQ = 68 words total).
    // Point all unused handlers at a safe infinite-loop stub defined below.
    for name in &["NMI","HardFault","MemManage","BusFault","UsageFault",
                  "SecureFault","_reserved7","_reserved8","_reserved9",
                  "SVC","DebugMon","_reserved11","PendSV","SysTick"] {
        asm.push_str(&format!(".word _uvm2_default_handler @ {}\n", name));
    }
    // 52 external IRQs
    asm.push_str(".rept 52\n.word _uvm2_default_handler\n.endr\n");
    asm.push_str("\n");
    // Default handler: safe infinite loop (avoids runaway on unexpected exceptions)
    asm.push_str(".thumb_func\n_uvm2_default_handler:\n    b _uvm2_default_handler\n\n");
    // NOTE: base address matches uvm2_game.ld VPY_RAM region (0x2007C000)
    asm.push_str(&ram_layout::emit_ram_layout());

    // VIA register addresses (Vectrex bus — same hardware, same addresses)
    asm.push_str(&emit_via_constants());

    // UVM2 SIO GPIO constants (Ralf's pinout)
    asm.push_str(&emit_sio_constants());

    asm.push_str(".section .game_rom, \"ax\"\n");
    asm.push_str(".align 2\n\n");

    asm.push_str(&header::emit_image_def());
    asm.push_str(&bus::emit_uvm2_bus_helpers());

    // Usage analysis (shared with the arm target): emit runtime routines only
    // when the program actually uses them. Core stubs are always emitted.
    let usage = crate::arm::analysis::analyze(module);

    // Recordings (.vrec) are usage-filtered (shared with the arm target).
    let asset_list = assets::filter_recording_assets(asset_list, module);
    // Audio samples (.vsmp) usage-filtered the same way (shared with arm target).
    let asset_list = assets::filter_sample_assets(&asset_list, module);
    let asset_list = asset_list.as_slice();

    // For UVM2, bus_write/bus_read delegate to uvm2_via_write (CLK-synced GPIO),
    // so we skip helpers::emit_bus_helpers() — that uses the debug-cart pinout.
    // The pinout-agnostic runtime (enemy pool) is emitted when used.
    asm.push_str(&emit_uvm2_bus_shims());
    asm.push_str(&crate::arm::helpers::emit_runtime_helpers(&usage));
    asm.push_str(&drawing::emit_drawing(&usage));

    let msg_entries = builtins::collect_msg_entries(module);
    asm.push_str(&builtins::emit_builtins(&msg_entries, &usage));

    asm.push_str(&functions::emit_functions(module, asset_list, &usage)?);
    asm.push_str(&assets::emit_arm_assets(asset_list));

    // Expand cbz, then inject uvm2_bus_init call at start of game_main
    let expanded = crate::arm::expand_cbz_pub(&asm);
    Ok(inject_bus_init(&expanded))
}

// ── UVM2 bus shims ────────────────────────────────────────────────────────────
// drawing.rs calls bus_write(r0=addr, r1=data) and bus_read(r0=addr).
// For UVM2 these are thin wrappers around uvm2_via_write / uvm2_via_read
// so the drawing code works unchanged with the CLK-synced GPIO protocol.

fn emit_uvm2_bus_shims() -> String {
    r#"@ --- UVM2 bus shims: bus_write / bus_read → CLK-synced GPIO ---
@ bus_write(r0=addr, r1=data) — delegates to uvm2_via_write
.global bus_write
.thumb_func
bus_write:
    b       uvm2_via_write

@ bus_read(r0=addr) → r0=data
@ OPTION A: real CLK-synced read  → uncomment the line below
@ OPTION B: fixed spin-delay      → uncomment the line below
@ Change one line to switch between them. Default: OPTION B (safer first test).
.global bus_read
.thumb_func
bus_read:
    @ OPTION A (CLK-synced read):
    @ b       uvm2_via_read
    @ OPTION B (spin delay, always returns 0x40 = timer done):
    b       uvm2_timer_wait

"#
    .to_string()
}

// ── VIA constants (same addresses — it's the same Vectrex VIA chip) ──────────

fn emit_via_constants() -> String {
    let mut s = String::from("@ --- VIA 6522 registers (Vectrex bus addresses) ---\n");
    s.push_str(".equ VIA_BASE,       0xD000\n");
    s.push_str(".equ VIA_PORT_B,     0xD000\n");
    s.push_str(".equ VIA_PORT_A,     0xD001\n");
    s.push_str(".equ VIA_DDR_B,      0xD002\n");
    s.push_str(".equ VIA_DDR_A,      0xD003\n");
    s.push_str(".equ VIA_T1C_L,      0xD004\n");
    s.push_str(".equ VIA_T1C_H,      0xD005\n");
    s.push_str(".equ VIA_T1L_L,      0xD006\n");
    s.push_str(".equ VIA_T1L_H,      0xD007\n");
    s.push_str(".equ VIA_SR,         0xD00A\n");
    s.push_str(".equ VIA_ACR,        0xD00B\n");
    s.push_str(".equ VIA_PCR,        0xD00C\n");
    s.push_str(".equ VIA_IFR,        0xD00D\n");
    s.push_str(".equ VIA_IER,        0xD00E\n");
    s.push_str("\n@ VIA Port B bits\n");
    s.push_str(".equ PB_MUX,         0x01\n");
    s.push_str(".equ PB_BEAM,        0x08\n");
    s.push_str(".equ PB_ZPULSE,      0x10\n");
    s.push_str("\n@ VIA ACR / PCR values\n");
    s.push_str(".equ ACR_SR_SHIFT,   0x18\n");
    s.push_str(".equ PCR_BEAM_OFF,   0xCE\n");
    s.push_str(".equ PCR_BEAM_ON,    0xDE\n");
    s.push_str(".equ T1_STANDARD,    0x7F\n");
    s.push_str("\n");
    s
}

// ── UVM2 GPIO constants (Ralf's pinout) ──────────────────────────────────────

fn emit_sio_constants() -> String {
    let mut s = String::from("@ --- RP2350 SIO (GPIO bit-bang) — UVM2 pinout ---\n");
    s.push_str("@ Source: Ralf (UVM2 firmware author), 2026-04-16\n");
    s.push_str(".equ SIO_BASE,       0xD0000000\n");
    s.push_str(".equ SIO_GPIO_OUT,   0xD0000010\n");
    s.push_str(".equ SIO_GPIO_SET,   0xD0000014\n");
    s.push_str(".equ SIO_GPIO_CLR,   0xD0000018\n");
    s.push_str(".equ SIO_GPIO_OE_SET,0xD0000024\n");
    s.push_str(".equ SIO_GPIO_OE_CLR,0xD0000028\n");
    s.push_str(".equ SIO_GPIO_IN,    0xD0000004\n");
    s.push_str("\n@ UVM2 GPIO pin assignments\n");
    // Data bus: GPIO 0-7 = D0-D7
    s.push_str(".equ PIN_D0,         0          @ D0\n");
    s.push_str(".equ PIN_D7,         7          @ D7\n");
    s.push_str(".equ DATA_MASK,      0x000000FF  @ GPIO 0-7\n");
    // Address bus: GPIO 8-21 = A0-A13
    s.push_str(".equ PIN_A0,         8          @ A0  (GPIO8)\n");
    s.push_str(".equ PIN_A13,        21         @ A13 (GPIO21)\n");
    s.push_str(".equ ADDR_MASK,      0x003FFF00  @ GPIO 8-21 = A0-A13\n");
    // Control signals
    s.push_str(".equ PIN_PB6,        22         @ VIA Port B bit 6 (beam control)\n");
    s.push_str(".equ PIN_NIRQ,       23         @ /IRQ\n");
    s.push_str(".equ PIN_A14,        24         @ A14 (GPIO24)\n");
    s.push_str(".equ PIN_A15,        25         @ A15\n");
    s.push_str(".equ PIN_RW,         26         @ R/W (1=read, 0=write)\n");
    s.push_str(".equ PIN_NHALT,      27         @ /HALT — assert LOW to take bus\n");
    s.push_str(".equ PIN_NNMI,       29         @ /NMI\n");
    s.push_str(".equ PIN_CLK,        31         @ System clock (1.5 MHz)\n");
    s.push_str("\n@ Convenience masks\n");
    s.push_str(".equ MASK_NHALT,     (1 << 27)  @ /HALT pin mask\n");
    s.push_str(".equ MASK_RW,        (1 << 26)  @ R/W pin mask\n");
    s.push_str(".equ MASK_CLK,       (1 << 31)  @ CLK pin mask\n");
    s.push_str("\n");
    s
}

// ── Post-processing ───────────────────────────────────────────────────────────

/// Inject `bl uvm2_bus_init` as the very first instruction of `game_main`.
/// This ensures GPIO directions are configured before any game code runs.
fn inject_bus_init(asm: &str) -> String {
    // The ARM codegen always emits game_main with this exact prologue.
    // We insert the init call before the push so it runs unconditionally.
    asm.replace(
        "game_main:\n    push    {r4,",
        "game_main:\n    bl      uvm2_bus_init\n    push    {r4,",
    )
}
