//! Expression Compilation for M6809
//!
//! Compiles VPy expressions to M6809 assembly
//! Result stored in RESULT (2-byte RAM variable)

use vpy_parser::{Expr, BinOp, CmpOp, LogicOp};
use super::builtins;
use super::context;  // For checking mutable arrays
use crate::AssetInfo;
use std::sync::atomic::{AtomicUsize, Ordering};

static LABEL_COUNTER: AtomicUsize = AtomicUsize::new(0);

/// Emit code for simple expression (numbers, vars, strings, calls)
///
/// CRITICAL CONTRACT: This function MUST return with a balanced stack.
/// Every PSHS operation must have a corresponding PULS or equivalent pop operation
/// BEFORE returning to the caller. Violations will cause stack corruption when
/// expressions are evaluated in branching contexts (if/elif/while conditions).
pub fn emit_simple_expr(expr: &Expr, out: &mut String, assets: &[AssetInfo]) {
    match expr {
        Expr::Number(n) => {
            out.push_str(&format!("    LDD #{}\n", n));
        }
        
        Expr::StringLit(s) => {
            // String literals use hash-based labels generated by builtins::collect_print_text_strings
            let label = format!("PRINT_TEXT_STR_{}", builtins::hash_string(s));
            out.push_str(&format!("    LDX #{}      ; Pointer to string literal \"{}\"\n", label, s));
            out.push_str("    TFR X,D\n");      // D = X (string pointer) — D valid after emit
        }
        
        Expr::Ident(id) => {
            // Compile-time consts: emit an immediate value instead of a RAM load.
            // This prevents reading from uninitialized RAM and matches how core handles consts.
            if let Some(const_val) = context::get_const_value(&id.name) {
                out.push_str(&format!("    LDD #{}  ; const {}\n", const_val, id.name));
                return;
            }

            // Check if this is a function parameter → use VAR_ARGn
            let var_label = resolve_var_label(&id.name);

            // Variable references use uppercase labels
            // Check variable size: use LDB + sign/zero-extend for 8-bit, LDD for 16-bit
            let size = context::get_var_size(&id.name);
            if size.bytes == 1 {
                // 8-bit load: LDB then extend to 16-bit in D (use > for extended addressing)
                out.push_str(&format!("    LDB >{}\n", var_label));
                if size.signed {
                    out.push_str("    SEX             ; Sign-extend B -> D\n");
                } else {
                    out.push_str("    CLRA            ; Zero-extend: A=0, B=value\n");
                }
            } else {
                // 16-bit load: standard LDD (use > for extended addressing)
                out.push_str(&format!("    LDD >{}\n", var_label));
            }
        }
        
        Expr::Call(call) => {
            // Check if builtin
            if builtins::emit_builtin(&call.name, &call.args, out, assets) {
                return;
            }
            
            // User function call (name already uppercase from unifier)
            // Evaluate arguments and store in VAR_ARG0-4
            // D already holds the result after emit_simple_expr; no LDD RESULT reload needed.
            for (i, arg) in call.args.iter().enumerate().take(5) {
                emit_simple_expr(arg, out, assets);
                out.push_str(&format!("    STD VAR_ARG{}\n", i));
            }
            
            // Call function
            out.push_str(&format!("    JSR {}\n", call.name));
        }
        
        Expr::Binary { left, op, right } => {
            emit_binop(left, *op, right, out, assets);
        }

        Expr::Logic { op, left, right } => {
            let id = LABEL_COUNTER.fetch_add(1, Ordering::SeqCst);
            match op {
                LogicOp::And => {
                    // Short-circuit AND: if left is false, result is 0 (false)
                    emit_simple_expr(left, out, assets);
                    out.push_str(&format!("    LBEQ .LOGIC_{}_FALSE\n", id));

                    // Left is true, check right
                    emit_simple_expr(right, out, assets);
                    out.push_str(&format!("    LBEQ .LOGIC_{}_FALSE\n", id));
                    
                    // Both true
                    out.push_str("    LDD #1\n");
                    out.push_str(&format!("    LBRA .LOGIC_{}_END\n", id));

                    out.push_str(&format!(".LOGIC_{}_FALSE:\n", id));
                    out.push_str("    LDD #0\n");
                    out.push_str(&format!(".LOGIC_{}_END:\n", id));
                }
                LogicOp::Or => {
                    // Short-circuit OR: if left is true, result is 1 (true)
                    emit_simple_expr(left, out, assets);
                    out.push_str(&format!("    LBNE .LOGIC_{}_TRUE\n", id));

                    // Left is false, check right
                    emit_simple_expr(right, out, assets);
                    out.push_str(&format!("    LBNE .LOGIC_{}_TRUE\n", id));
                    
                    // Both false
                    out.push_str("    LDD #0\n");
                    out.push_str(&format!("    LBRA .LOGIC_{}_END\n", id));

                    out.push_str(&format!(".LOGIC_{}_TRUE:\n", id));
                    out.push_str("    LDD #1\n");
                    out.push_str(&format!(".LOGIC_{}_END:\n", id));
                }
            }
        }
        
        Expr::Not(expr) => {
            let id = LABEL_COUNTER.fetch_add(1, Ordering::SeqCst);
            emit_simple_expr(expr, out, assets);
            out.push_str(&format!("    LBNE .NOT_{}_ZERO\n", id));
            out.push_str("    LDD #1\n");
            out.push_str(&format!("    LBRA .NOT_{}_END\n", id));
            out.push_str(&format!(".NOT_{}_ZERO:\n", id));
            out.push_str("    LDD #0\n");
            out.push_str(&format!(".NOT_{}_END:\n", id));
        }

        Expr::BitNot(expr) => {
            emit_simple_expr(expr, out, assets);
            out.push_str("    COMA\n");
            out.push_str("    COMB\n");
        }
        
        Expr::Compare { left, op, right } => {
            emit_compare(left, *op, right, out, assets);
        }
        
        Expr::Index { target, index } => {
            emit_index(target, index, out, assets);
        }
        
        _ => {
            // Unimplemented expression types (List, StructInit, FieldAccess, MethodCall)
            // These should likely be transformed before codegen or are not supported yet
            out.push_str(&format!("    ; Unimplemented Expr {:?}\n", expr));
            out.push_str("    LDD #0\n");
        }
    }
}

fn emit_binop(left: &Expr, op: BinOp, right: &Expr, out: &mut String, assets: &[AssetInfo]) {
    // CRITICAL FIX (2026-02-22): Stack balance - use TMPVAL instead of PSHS/PULS
    // The `,S++` addressing mode doesn't properly pop for 16-bit operations.
    // Instead, save LEFT to TMPVAL, evaluate RIGHT into D, then operate.

    // Evaluate left
    emit_simple_expr(left, out, assets);
    out.push_str("    STD TMPVAL          ; Save left operand to TMPVAL (stack-safe temp)\n");

    // Evaluate right
    emit_simple_expr(right, out, assets);

    // Perform operation
    match op {
        BinOp::Add => {
            out.push_str("    ADDD TMPVAL         ; D = D + LEFT (from TMPVAL)\n");
        }
        BinOp::Sub => {
            out.push_str("    STD TMPPTR      ; Save right operand to TMPPTR\n");
            out.push_str("    LDD TMPVAL      ; Get left operand from TMPVAL\n");
            out.push_str("    SUBD TMPPTR     ; Left - Right\n");
        }
        BinOp::Mul => {
            out.push_str("    LDX TMPVAL      ; Get left into X from TMPVAL\n");
            out.push_str("    JSR MUL16       ; D = X * D\n");
        }
        BinOp::Div | BinOp::FloorDiv => {
            out.push_str("    LDX TMPVAL      ; Get left into X from TMPVAL\n");
            out.push_str("    JSR DIV16       ; D = X / D\n");
        }
        BinOp::Mod => {
            out.push_str("    LDX TMPVAL      ; Get left into X from TMPVAL\n");
            out.push_str("    JSR MOD16       ; D = X % D\n");
        }
        BinOp::Shl => {
            // Shift Left: D = Left << Right
            // LEFT in TMPVAL, RIGHT in D
            let id = LABEL_COUNTER.fetch_add(1, Ordering::SeqCst);
            out.push_str("    STD TMPPTR      ; Save shift amount (Right)\n");
            out.push_str("    LDD TMPVAL      ; Get value to shift (Left)\n");
            out.push_str("    LDX TMPPTR      ; Load shift amount into X\n");
            out.push_str(&format!("    BEQ .SHL_{}_END\n", id)); // Shift 0 -> done

            // Limit shift to 16
            out.push_str("    CMPX #16\n");
            out.push_str(&format!("    BLE .SHL_{}_LOOP\n", id));
            out.push_str("    LDX #16\n");

            out.push_str(&format!(".SHL_{}_LOOP:\n", id));
            out.push_str("    ASLB\n");
            out.push_str("    ROLA\n");
            out.push_str("    LEAX -1,X\n");
            out.push_str(&format!("    BNE .SHL_{}_LOOP\n", id));

            out.push_str(&format!(".SHL_{}_END:\n", id));
        }
        BinOp::Shr => {
            // Shift Right: D = Left >> Right
            // LEFT in TMPVAL, RIGHT in D
            let id = LABEL_COUNTER.fetch_add(1, Ordering::SeqCst);
            out.push_str("    STD TMPPTR      ; Save shift amount\n");
            out.push_str("    LDD TMPVAL      ; Get value to shift (Left)\n");
            out.push_str("    LDX TMPPTR\n");
            out.push_str(&format!("    BEQ .SHR_{}_END\n", id));

            out.push_str("    CMPX #16\n");
            out.push_str(&format!("    BLE .SHR_{}_LOOP\n", id));
            out.push_str("    LDX #16\n");

            out.push_str(&format!(".SHR_{}_LOOP:\n", id));
            out.push_str("    ASRA\n");
            out.push_str("    RORB\n");
            out.push_str("    LEAX -1,X\n");
            out.push_str(&format!("    BNE .SHR_{}_LOOP\n", id));

            out.push_str(&format!(".SHR_{}_END:\n", id));
        }
        BinOp::BitAnd => {
            out.push_str("    STD TMPPTR2     ; Save right operand to TMPPTR2\n");
            out.push_str("    LDD TMPVAL      ; Get left from TMPVAL\n");
            out.push_str("    ANDA TMPPTR2    ; A AND TMPPTR2+0 (high byte)\n");
            out.push_str("    ANDB TMPPTR2+1  ; B AND TMPPTR2+1 (low byte)\n");
        }
        BinOp::BitOr => {
            out.push_str("    STD TMPPTR2     ; Save right operand to TMPPTR2\n");
            out.push_str("    LDD TMPVAL      ; Get left from TMPVAL\n");
            out.push_str("    ORA TMPPTR2     ; A OR TMPPTR2+0 (high byte)\n");
            out.push_str("    ORB TMPPTR2+1   ; B OR TMPPTR2+1 (low byte)\n");
        }
        BinOp::BitXor => {
            out.push_str("    STD TMPPTR2     ; Save right operand to TMPPTR2\n");
            out.push_str("    LDD TMPVAL      ; Get left from TMPVAL\n");
            out.push_str("    EORA TMPPTR2    ; A XOR TMPPTR2+0 (high byte)\n");
            out.push_str("    EORB TMPPTR2+1  ; B XOR TMPPTR2+1 (low byte)\n");
        }
    }
}

fn emit_compare(left: &Expr, op: CmpOp, right: &Expr, out: &mut String, assets: &[AssetInfo]) {
    let id = LABEL_COUNTER.fetch_add(1, Ordering::SeqCst);

    // CRITICAL FIX (2026-02-22): Stack balance - use TMPVAL instead of PSHS/PULS
    // The `,S++` addressing mode doesn't properly pop for 16-bit comparisons.
    // Instead, evaluate RIGHT into TMPVAL, evaluate LEFT into D, then CMPD TMPVAL.
    // This avoids stack corruption from unbalanced PSHS/PULS pairs.

    // Evaluate RIGHT first, save to TMPVAL
    emit_simple_expr(right, out, assets);
    out.push_str("    STD TMPVAL          ; Save right operand to TMPVAL (stack-safe temp)\n");

    // Evaluate LEFT
    emit_simple_expr(left, out, assets);
    out.push_str("    CMPD TMPVAL\n");     // Compare LEFT - RIGHT (using memory temp, not stack)

    let branch_true = match op {
        CmpOp::Eq => "LBEQ",
        CmpOp::Ne => "LBNE",
        CmpOp::Lt => "LBLT",
        CmpOp::Le => "LBLE",
        CmpOp::Gt => "LBGT",
        CmpOp::Ge => "LBGE",
    };

    out.push_str(&format!("    {} .CMP_{}_TRUE\n", branch_true, id));
    out.push_str("    LDD #0\n");
    out.push_str(&format!("    LBRA .CMP_{}_END\n", id));
    out.push_str(&format!(".CMP_{}_TRUE:\n", id));
    out.push_str("    LDD #1\n");
    out.push_str(&format!(".CMP_{}_END:\n", id));
}

fn emit_index(array: &Expr, index: &Expr, out: &mut String, assets: &[AssetInfo]) {
    // CRITICAL FIX (2026-02-22): Use TMPPTR for array index storage, not TMPVAL
    // TMPVAL is reserved for comparison operands in conditional expressions
    // Using TMPVAL here causes overwrites when array access appears in comparisons like:
    //   joystick1_state[2] == 1  (TMPVAL gets 1, then gets overwritten by index 2)
    //
    // Solution: Use TMPPTR to store the index, keeping TMPVAL free for comparisons
    // This avoids register pressure and maintains expression evaluation safety

    // CRITICAL FIX (2026-01-19): Use correct label based on array type
    // Mutable arrays (GlobalLet): VAR_{NAME}_DATA (in RAM)
    // Const arrays: ARRAY_{NAME}_DATA (in ROM)
    // Use context::is_mutable_array() to check which type

    let element_size = if let Expr::Ident(id) = array {
        context::get_var_size(&id.name).bytes  // Get element size for stride calculation
    } else {
        2  // Default to 16-bit if not a simple identifier
    };

    // Step 1: Load array base into X
    if let Expr::Ident(id) = array {
        let name_upper = id.name.to_uppercase();
        let label = if context::is_mutable_array(&id.name) {
            format!("VAR_{}_DATA", name_upper)  // RAM
        } else {
            format!("ARRAY_{}_DATA", name_upper)  // ROM
        };
        out.push_str(&format!("    LDX #{}  ; Array base\n", label));
    } else {
        // Complex array expression - evaluate it; D holds result after emit
        emit_simple_expr(array, out, assets);
        out.push_str("    TFR D,X     ; Array base address (D -> X, avoids RESULT read)\n");
    }

    // Step 2: Evaluate index and save to TMPPTR (NOT TMPVAL - keeps comparison operand safe)
    emit_simple_expr(index, out, assets);
    out.push_str("    STD TMPPTR  ; Save index to TMPPTR (safe from TMPVAL overwrites)\n");

    // Step 3: Calculate stride and adjust X
    // Stride multiply: only if element_size == 2 (8-bit arrays have stride 1, no multiply needed)
    if element_size == 2 {
        out.push_str("    LDD TMPPTR  ; Load index\n");
        out.push_str("    ASLB        ; Multiply by 2 (16-bit elements)\n");
        out.push_str("    ROLA\n");
    } else {
        out.push_str("    LDD TMPPTR  ; Load index (stride = 1 for 8-bit)\n");
    }

    // Step 4: Calculate address: X = X + (D = index * element_size)
    out.push_str("    LEAX D,X    ; X = base + (index * element_size)\n");

    // Step 5: Load element: use correct load instruction based on element type
    if element_size == 1 {
        // 8-bit element: LDB then zero-extend (arrays are typically unsigned)
        out.push_str("    LDB ,X      ; Load 8-bit value\n");
        out.push_str("    CLRA        ; Zero-extend to 16-bit (arrays are typically unsigned)\n");
    } else {
        // 16-bit element: standard LDD
        out.push_str("    LDD ,X      ; Load 16-bit value\n");
    }
}

/// Resolve a variable name to its ASM label.
/// If the name is a function parameter, returns VAR_ARGn; otherwise VAR_NAME.
pub fn resolve_var_label(name: &str) -> String {
    if let Some(idx) = context::get_param_index(name) {
        format!("VAR_ARG{}", idx)
    } else {
        format!("VAR_{}", name.to_uppercase())
    }
}
