#!/usr/bin/env python3
"""Generate vpy_trig_q14.h — the quarter-wave sine table libvpy uses for Q14 trig.

Run from anywhere; it writes the header next to vpy.c:

    python3 tools/gen_trig_q14.py

The table is a QUARTER wave: 4096 units per full turn means one quadrant is
1024 units, so 1025 entries (0..1024 inclusive) cover it with one entry per
unit and NO interpolation is needed at lookup time. The other three quadrants
come from folding, and cosine is sine shifted by 1024.

Amplitude is Q14: 16384 = 1.0. That is deliberately one bit below Q15 so a
product of two Q14 values still fits a signed 32-bit intermediate with room to
spare, which is what the 3D transform path relies on.
"""
import math
import os

TURN = 4096          # units per full turn
QUAD = TURN // 4     # 1024 units per quadrant
ONE = 16384          # Q14: 16384 = 1.0

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, os.pardir, "vpy_trig_q14.h")


def main() -> None:
    vals = [round(math.sin(i * 2.0 * math.pi / TURN) * ONE) for i in range(QUAD + 1)]
    assert vals[0] == 0 and vals[QUAD] == ONE, "quarter wave endpoints moved"
    assert max(vals) == ONE and min(vals) == 0, "amplitude is not Q14"

    lines = [
        "/* vpy_trig_q14.h — GENERATED by tools/gen_trig_q14.py. Do not edit by hand.",
        " *",
        " * Quarter-wave sine: %d units per full turn, Q14 (%d = 1.0)." % (TURN, ONE),
        " * %d entries = one quadrant at one entry per unit, so lookup needs no" % (QUAD + 1),
        " * interpolation. See vpy_sin_q14() in vpy.c for the folding. */",
        "#ifndef VPY_TRIG_Q14_H",
        "#define VPY_TRIG_Q14_H",
        "",
        "#include <stdint.h>",
        "",
        "#define VPY_Q14_TURN %d   /* units per full turn */" % TURN,
        "#define VPY_Q14_ONE  %d  /* Q14 scale: this is 1.0 */" % ONE,
        "",
        "static const int16_t VPY_SIN_Q14[%d] = {" % (QUAD + 1),
    ]
    for i in range(0, len(vals), 8):
        lines.append("    " + ",".join("%6d" % v for v in vals[i:i + 8]) + ",")
    lines += ["};", "", "#endif /* VPY_TRIG_Q14_H */", ""]

    with open(OUT, "w") as f:
        f.write("\n".join(lines))
    print("wrote %s (%d entries)" % (os.path.normpath(OUT), QUAD + 1))


if __name__ == "__main__":
    main()
