#!/usr/bin/env python3
"""Generate src/sb_font.h — a compact stroke font for the game's text tiles.

The game writes text straight into Pandora RAM as ASCII tile codes (0x20-0x5a),
plus a bold digit set at 0x04-0x0d and three composite tiles (1P / 2P / HI).
Instead of tracing ~90 raster tiles, every text tile renders as a few vector
strokes from this original single-stroke font.

Glyphs are authored on a 6x8 grid (y down) and pre-scaled here to pixel
coordinates inside a 16px tile: x -> 2 + gx*2 (2..14), y -> 1 + gy*13/8.
Header layout: packed points (x,y,penup) per glyph + an index by ASCII code.
"""
from pathlib import Path

G = {
 'A': [[(0,8),(3,0),(6,8)],[(1,5),(5,5)]],
 'B': [[(0,8),(0,0),(5,0),(6,1),(6,3),(5,4),(0,4)],[(5,4),(6,5),(6,7),(5,8),(0,8)]],
 'C': [[(6,1),(5,0),(1,0),(0,1),(0,7),(1,8),(5,8),(6,7)]],
 'D': [[(0,8),(0,0),(4,0),(6,2),(6,6),(4,8),(0,8)]],
 'E': [[(6,0),(0,0),(0,8),(6,8)],[(0,4),(4,4)]],
 'F': [[(6,0),(0,0),(0,8)],[(0,4),(4,4)]],
 'G': [[(6,1),(5,0),(1,0),(0,1),(0,7),(1,8),(5,8),(6,7),(6,4),(3,4)]],
 'H': [[(0,0),(0,8)],[(6,0),(6,8)],[(0,4),(6,4)]],
 'I': [[(1,0),(5,0)],[(3,0),(3,8)],[(1,8),(5,8)]],
 'J': [[(6,0),(6,7),(5,8),(1,8),(0,7)]],
 'K': [[(0,0),(0,8)],[(6,0),(0,4),(6,8)]],
 'L': [[(0,0),(0,8),(6,8)]],
 'M': [[(0,8),(0,0),(3,4),(6,0),(6,8)]],
 'N': [[(0,8),(0,0),(6,8),(6,0)]],
 'O': [[(1,0),(5,0),(6,1),(6,7),(5,8),(1,8),(0,7),(0,1),(1,0)]],
 'P': [[(0,8),(0,0),(5,0),(6,1),(6,3),(5,4),(0,4)]],
 'Q': [[(1,0),(5,0),(6,1),(6,7),(5,8),(1,8),(0,7),(0,1),(1,0)],[(4,6),(6,8)]],
 'R': [[(0,8),(0,0),(5,0),(6,1),(6,3),(5,4),(0,4)],[(2,4),(6,8)]],
 'S': [[(6,1),(5,0),(1,0),(0,1),(0,3),(1,4),(5,4),(6,5),(6,7),(5,8),(1,8),(0,7)]],
 'T': [[(0,0),(6,0)],[(3,0),(3,8)]],
 'U': [[(0,0),(0,7),(1,8),(5,8),(6,7),(6,0)]],
 'V': [[(0,0),(3,8),(6,0)]],
 'W': [[(0,0),(1,8),(3,4),(5,8),(6,0)]],
 'X': [[(0,0),(6,8)],[(6,0),(0,8)]],
 'Y': [[(0,0),(3,4),(6,0)],[(3,4),(3,8)]],
 'Z': [[(0,0),(6,0),(0,8),(6,8)]],
 '0': [[(1,0),(5,0),(6,1),(6,7),(5,8),(1,8),(0,7),(0,1),(1,0)]],
 '1': [[(1,2),(3,0),(3,8)],[(1,8),(5,8)]],
 '2': [[(0,1),(1,0),(5,0),(6,1),(6,3),(0,8),(6,8)]],
 '3': [[(0,0),(6,0),(3,4),(5,4),(6,5),(6,7),(5,8),(1,8),(0,7)]],
 '4': [[(4,8),(4,0),(0,5),(6,5)]],
 '5': [[(6,0),(0,0),(0,4),(5,4),(6,5),(6,7),(5,8),(0,8)]],
 '6': [[(5,0),(1,0),(0,1),(0,7),(1,8),(5,8),(6,7),(6,5),(5,4),(0,4)]],
 '7': [[(0,0),(6,0),(2,8)]],
 '8': [[(1,0),(5,0),(6,1),(6,3),(5,4),(1,4),(0,3),(0,1),(1,0)],
       [(1,4),(0,5),(0,7),(1,8),(5,8),(6,7),(6,5),(5,4)]],
 '9': [[(6,4),(1,4),(0,3),(0,1),(1,0),(5,0),(6,1),(6,7),(5,8),(1,8)]],
 '.': [[(2,7),(3,7),(3,8),(2,8),(2,7)]],
 ',': [[(3,6),(2,8)]],
 '-': [[(1,4),(5,4)]],
 '!': [[(3,0),(3,5)],[(3,7),(3,8)]],
 '?': [[(0,1),(1,0),(5,0),(6,1),(6,3),(3,4),(3,5)],[(3,7),(3,8)]],
 ':': [[(3,2),(3,3)],[(3,6),(3,7)]],
 '/': [[(0,8),(6,0)]],
 "'": [[(3,0),(3,2)]],
 '&': [[(6,8),(1,2),(1,1),(2,0),(3,0),(4,1),(4,2),(0,5),(0,7),(1,8),(3,8),(5,6)]],
 '(': [[(4,0),(2,2),(2,6),(4,8)]],
 ')': [[(2,0),(4,2),(4,6),(2,8)]],
}


def scale(pt, half=0, shift=0):
    x, y = pt
    # glyph body 9x11 inside the 16px cell — adjacent characters need air,
    # at full cell width they read as one clump
    px = 3 + (x * 3) // 2
    if half:
        px = 1 + x  # half-width variant for composite tiles
    return (px + shift, 2 + (y * 11) // 8)


def main():
    pts, entries = [], {}

    def emit(strokes, half=0, shift=0):
        first = len(pts)
        for s in strokes:
            for i, p in enumerate(s):
                x, y = scale(p, half, shift)
                pts.append((x, y, 1 if i == 0 else 0))
        return (first, len(pts) - first)

    for ch, strokes in G.items():
        entries[ord(ch)] = emit(strokes)

    # composite tiles: two half-width glyphs side by side in one cell
    for code, txt in {0x5B: '1P', 0x5C: '2P', 0x5D: 'HI'}.items():
        first = len(pts)
        for i, ch in enumerate(txt):
            emit(G[ch], half=1, shift=i * 7)
        entries[code] = (first, len(pts) - first)

    out = ['/* generated by tools/make_font.py — do not edit */']
    out.append('static const unsigned char sb_font_pts[][3] = {')
    for x, y, pen in pts:
        out.append(f' {{{x},{y},{pen}}},')
    out.append('};')
    out.append('/* index by (code - 0x20) for codes 0x20-0x5f; count 0 = blank */')
    out.append('static const struct { unsigned short first, count; } sb_font_idx[0x40] = {')
    for code in range(0x20, 0x60):
        f, c = entries.get(code, (0, 0))
        label = chr(code) if 0x20 < code < 0x5B else {0x5B: '1P', 0x5C: '2P', 0x5D: 'HI'}.get(code, ' ')
        out.append(f' {{{f},{c}}}, /* {label} */')
    out.append('};')

    Path(__file__).resolve().parent.parent.joinpath('src/sb_font.h').write_text('\n'.join(out) + '\n')
    print(f'src/sb_font.h: {len(entries)} glyph entries, {len(pts)} points')


if __name__ == '__main__':
    main()
