#!/usr/bin/env python3
"""Embed the Snow Bros ROMs as C arrays.

sb_rom.h:   sb_prog[0x40000] — 68000 program, sn6.bin/sn5.bin interleaved
            big-endian (sn6 = even/high byte, sn5 = odd/low byte, as
            ROM_LOAD16_BYTE lays them out).
sb_tiles.h: per-tile silhouette bounding boxes from sbros-1.41 (4096 tiles,
            gfx_8x8x4_row_2x2_group_packed_msb) so the renderer can draw a
            tight outline per tile before real vec shapes exist, plus a
            blank-tile bitmap.
"""
import sys
import zipfile
from pathlib import Path

here = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(here / 'tools'))
from extract_sprites import decode_tile, load_tiles

z = zipfile.ZipFile(here / 'rom' / 'snowbros.zip')
sn6, sn5 = z.read('sn6.bin'), z.read('sn5.bin')
prog = bytearray()
for a, b in zip(sn6, sn5):
    prog += bytes((a, b))

out = here / 'src' / 'sb_rom.h'
with open(out, 'w') as f:
    f.write('/* generated by tools/roms_to_c.py — do not edit */\n')
    f.write(f'static const unsigned char sb_prog[{len(prog)}] = {{\n')
    for i in range(0, len(prog), 16):
        f.write(' ' + ','.join(str(b) for b in prog[i:i+16]) + ',\n')
    f.write('};\n')
print(out, len(prog), 'bytes')

tiles = load_tiles(here / 'rom' / 'snowbros.zip')
boxes, blanks = [], []
for t in tiles:
    px = decode_tile(t)
    xs = [i % 16 for i, p in enumerate(px) if p]
    ys = [i // 16 for i, p in enumerate(px) if p]
    if xs:
        boxes.append((min(xs), min(ys), max(xs), max(ys)))
        blanks.append(0)
    else:
        boxes.append((0, 0, 0, 0))
        blanks.append(1)

toprows = []
for t in tiles:
    px = decode_tile(t)
    row = px[0:16]  # topmost row's palette indices
    toprows.append(bytes((row[i] << 4) | row[i + 1] for i in range(0, 16, 2)))

out = here / 'src' / 'sb_tiles.h'
with open(out, 'w') as f:
    f.write('/* generated by tools/roms_to_c.py — do not edit */\n')
    f.write(f'static const unsigned char sb_tile_box[{len(boxes)}][4] = {{\n')
    for b in boxes:
        f.write(' {%d,%d,%d,%d},\n' % b)
    f.write('};\n')
    f.write(f'static const unsigned char sb_tile_blank[{len(blanks)}] = {{\n')
    for i in range(0, len(blanks), 32):
        f.write(' ' + ','.join(str(x) for x in blanks[i:i+32]) + ',\n')
    f.write('};\n')
    f.write('/* top pixel row of each tile, two 4-bit palette indices per byte —\n')
    f.write(' * the renderer detects snow-capped (walkable) tiles with the live CRAM */\n')
    f.write(f'static const unsigned char sb_tile_toprow[{len(toprows)}][8] = {{\n')
    for r in toprows:
        f.write(' {' + ','.join(str(b) for b in r) + '},\n')
    f.write('};\n')
print(out, len(boxes), 'tiles (+toprows)')
