#!/usr/bin/env python3
"""Compile the editable per-level platform .vec files into src/sb_shapes.h.

Same pattern dkong_sbt/jetpac_sbt use: the .vec files ARE the geometry source,
and this build step turns them into C the renderer draws directly. It replaces
the old snowy-tile detection in sb_render.c (which missed the left side and had
no diagonals) — now every platform, diagonals included, is authored in the .vec
and drawn exactly as traced.

Each assets/vectors/level_NN.vec carries a "platforms" layer of closed paths.
compose_levels.py wrote those points PRE-SCALED to the tilted-console geometry
(vscale: (px-128)*0.857, (112-py)*0.857). The live renderer, though, draws the
players and enemies in raw arcade space (DX/DY, scale 90, no 0.857) and lets the
SDK rotate the whole frame. So for a platform to land UNDER the sprite that
stands on it, we undo the 0.857 here and emit arcade px/py — one shared space for
platforms and sprites.

Output (mirrors dkong's vk_shapes.h idea): int16 {py,px} streams, SB_PEN lifts
the pen between platforms, SB_END ends; one stream per level, indexed by the
level word the game keeps at 0x101572.

Usage: vec_to_shapes.py [vecdir] [out.h]
"""
import glob
import json
import os
import sys

GAME_SCALE = 192.0 / 224.0   # must match compose_levels.vscale

# compose_levels.rasterize draws the backdrop tiles 16px HIGH (Y = y + sy - 16),
# and the platform detection inherits that shift, so the .vec platform tops sit
# 16px above the sprite tile they came from. The live renderer draws sprites at
# their raw tile Y, so we push the platforms back DOWN by 16 arcade px to land
# them under the players' feet instead of their chests. Env PLAT_DY overrides it.
PLAT_DY = int(os.environ.get('PLAT_DY', '16'))

SB_PEN = -32768
SB_END = 32767


def unscale(vx, vy):
    """tilted-geometry vec unit -> arcade pixel (0..256, 0..224)."""
    px = vx / GAME_SCALE + 128.0
    py = 112.0 - vy / GAME_SCALE + PLAT_DY
    return int(round(py)), int(round(px))   # stream point is {py, px}


def level_index(path):
    base = os.path.splitext(os.path.basename(path))[0]   # level_NN
    return int(base.split('_')[1])


def stream_for(vec):
    """A level's platform paths -> a flat {py,px} stream with SB_PEN breaks."""
    d = json.load(open(vec))
    plats = []
    for layer in d.get('layers', []):
        if layer.get('name') != 'platforms':
            continue
        for p in layer.get('paths', []):
            pts = p.get('points', [])
            if len(pts) < 2:
                continue
            poly = [unscale(pt['x'], pt['y']) for pt in pts]
            if p.get('closed', True) and poly[0] != poly[-1]:
                poly.append(poly[0])   # close the rectangle outline
            plats.append(poly)
    out = []
    for k, poly in enumerate(plats):
        if k:
            out.append(SB_PEN)
        for py, px in poly:
            out.append(py)
            out.append(px)
    out.append(SB_END)
    return out


def main():
    here = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    vecdir = sys.argv[1] if len(sys.argv) > 1 else os.path.join(here, 'assets', 'vectors')
    out = sys.argv[2] if len(sys.argv) > 2 else os.path.join(here, 'src', 'sb_shapes.h')

    vecs = sorted(glob.glob(os.path.join(vecdir, 'level_*.vec')), key=level_index)
    if not vecs:
        sys.exit('no level_*.vec in %s' % vecdir)
    nlevels = level_index(vecs[-1]) + 1

    streams = {}
    for v in vecs:
        streams[level_index(v)] = stream_for(v)

    lines = [
        '/* GENERATED by tools/vec_to_shapes.py — do not edit by hand.',
        ' * Per-level platform geometry, un-scaled from assets/vectors/level_NN.vec',
        ' * back to arcade px/py (the space sb_render draws sprites in). Edit the',
        ' * .vec in the editor and rebuild to change the level geometry. */',
        '#ifndef SB_SHAPES_H',
        '#define SB_SHAPES_H',
        '#include <stdint.h>',
        '',
        '#define SB_PEN ((int16_t)-32768)  /* lift pen between platforms */',
        '#define SB_END ((int16_t) 32767)  /* end of a level stream */',
        '/* stream points are {py, px} in arcade coords (py 0..224, px 0..256) */',
        '',
    ]
    for n in range(nlevels):
        s = streams.get(n, [SB_END])
        body = ', '.join(str(v) for v in s)
        lines.append('static const int16_t sb_level_%02d[] = { %s };' % (n, body))
    lines.append('')
    lines.append('#define SB_NLEVELS %d' % nlevels)
    lines.append('static const int16_t *const sb_levels[SB_NLEVELS] = {')
    for n in range(nlevels):
        lines.append('    sb_level_%02d,' % n)
    lines.append('};')
    lines.append('')
    lines.append('#endif')
    open(out, 'w').write('\n'.join(lines) + '\n')
    tot = sum((len(s) - 1) // 2 for s in streams.values())
    print('sb_shapes.h: %d levels, %d platform points' % (nlevels, tot))


if __name__ == '__main__':
    main()
