#!/usr/bin/env python3
"""Bake traced .vec shapes + tile signatures into src/sb_sprites.h.

Each traced .vec corresponds to one composed sprite frame captured from the
attract (the same frames the refs in assets/images came from). An on-screen
object is identified by the LOWEST tile code in its chain group (frames are
consecutive-tile runs, so the base tile is a stable signature); on a hit the
renderer draws the vec strokes instead of per-tile boxes.

Vec coordinate contract: traced sprites are centred on the origin, y-up,
1 unit = 1 arcade pixel. The renderer anchors them at the centre of the
object's bounding box.
"""
import json
import sys
from pathlib import Path

here = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(here / 'tools'))
from compose_sprites import parse_objects, normalize

DUMPS = Path.home() / 'projects/mame/snowdump'

# vec name -> index in the frame ordering compose_sprites.py produces
# (the ref_fNNN images the vecs were traced from use the same numbering)
VEC_FRAMES = {
    'ball':         13,
    'enemy_pink_0': 19,
    'nick_stand':   24,
    'nick_walk_0':  28,
    'nick_walk_1':  32,
    'nick_jump':    43,
}


def rebuild_frames():
    from extract_sprites import load_tiles
    tiles = load_tiles(here / 'rom' / 'snowbros.zip')
    blank = {i for i, t in enumerate(tiles) if not any(b & 0x0F or b & 0xF0 for b in t)}
    seen = {}
    dump_files = sorted(DUMPS.glob('sprites_*.bin')) + \
                 sorted((DUMPS.parent / 'snowdump_cmp').glob('sprites_*.bin')) + \
                 sorted((here / 'dumps').glob('sprites_*.bin'))
    for f in dump_files:
        for obj in parse_objects(f.read_bytes()):
            obj = [t for t in obj if t[2] not in blank]
            if 1 <= len(obj) <= 64:
                seen.setdefault(normalize(obj), None)
    frames = list(seen)
    frames.sort(key=lambda o: (-len(o), o[0][2]))
    return frames


def vec_strokes(path: Path):
    """-> list of polylines [(x,y),...] in arcade-pixel units (y still up)."""
    d = json.loads(path.read_text())
    polys = []
    for layer in d['layers']:
        for p in layer['paths']:
            pts = [(q['x'], q['y']) for q in p['points']]
            if p.get('closed') and len(pts) > 2:
                pts.append(pts[0])
            if len(pts) > 1:
                polys.append(pts)
    return polys


# tile ranges whose every composed frame reuses one already-traced shape
# (a rolling snowball still reads as the lumpy circle)
ALIAS_RANGES = [
    (0x0100, 0x011b, 'ball'),
]

# vecs traced from ROM-aligned cuts (not captured frames):
# name -> (base tile, width tiles, height tiles); ref flip is ROM-native (0)
VEC_ROM = {
    'enemy2_walk_0': (0x480, 2, 2),
    'enemy2_walk_1': (0x484, 2, 2),
    'enemy2_walk_2': (0x488, 2, 2),
    'hud_1up':       (0x180, 1, 1),
    'item_blue':     (0x402, 1, 1),
}

# vecs whose signature comes from a captured object looked up by its LOWEST
# tile code (largest such object wins): title/attract pieces and poses that
# only exist chained (logo, lettering, banner rows, the pusher)
VEC_CAPTURED = {
    'logo_medallion': 0xd8f,
    'title_snow':     0xddc,
    'title_bros':     0xdee,
    'nick_push':      0x3b0,
    'instr_row_1':    0x0df,
    'instr_row_2':    0x0e8,
    'instr_row_3':    0x0ee,
}


def main():
    frames = rebuild_frames()
    out = ['/* generated by tools/vec_to_sprites.py — do not edit */']

    all_pts, all_polys, shapes = [], [], []
    sig_rows = []
    shape_idx = {}
    for name, idx in sorted(VEC_FRAMES.items(), key=lambda kv: kv[1]):
        obj = frames[idx]
        base = min(t[2] for t in obj)
        w = max(t[0] for t in obj) + 16
        h = max(t[1] for t in obj) + 16
        # the vec was traced over the frame AS CAPTURED — if that capture was
        # the flipped rendition, the runtime must mirror when its flip DIFFERS
        # from this reference flip, not when it's simply set
        ref_flip = 1 if sum(1 for t in obj if t[4]) * 2 > len(obj) else 0
        polys = vec_strokes(here / 'assets' / 'vectors' / f'{name}.vec')
        p0 = len(all_polys)
        for poly in polys:
            all_polys.append((len(all_pts), len(poly)))
            all_pts.extend(poly)
        shapes.append((name, p0, len(polys)))
        shape_idx[name] = len(shapes) - 1
        sig_rows.append((base, len(shapes) - 1, w, h, name, len(obj), ref_flip))
        print(f'{name:14s} frame {idx:3d}  base tile {base:04x}  {w}x{h}  '
              f'{len(obj)} tiles  refflip={ref_flip}  {len(polys)} strokes')

    for name, (base, tw, th) in sorted(VEC_ROM.items(), key=lambda kv: kv[1]):
        path = here / 'assets' / 'vectors' / f'{name}.vec'
        if not path.exists():
            print(f'{name:14s} SKIPPED (not traced yet)')
            continue
        polys = vec_strokes(path)
        p0 = len(all_polys)
        for poly in polys:
            all_polys.append((len(all_pts), len(poly)))
            all_pts.extend(poly)
        shapes.append((name, p0, len(polys)))
        shape_idx[name] = len(shapes) - 1
        sig_rows.append((base, len(shapes) - 1, tw * 16, th * 16, name, tw * th, 0))
        print(f'{name:14s} ROM cut   base tile {base:04x}  {tw*16}x{th*16}  {len(polys)} strokes')

    for name, base in sorted(VEC_CAPTURED.items(), key=lambda kv: kv[1]):
        path = here / 'assets' / 'vectors' / f'{name}.vec'
        cands = [o for o in frames if min(t[2] for t in o) == base]
        if not path.exists() or not cands:
            print(f'{name:14s} SKIPPED (vec or capture missing, base {base:04x})')
            continue
        obj = max(cands, key=len)
        w = max(t[0] for t in obj) + 16
        h = max(t[1] for t in obj) + 16
        ref_flip = 1 if sum(1 for t in obj if t[4]) * 2 > len(obj) else 0
        polys = vec_strokes(path)
        p0 = len(all_polys)
        for poly in polys:
            all_polys.append((len(all_pts), len(poly)))
            all_pts.extend(poly)
        shapes.append((name, p0, len(polys)))
        shape_idx[name] = len(shapes) - 1
        sig_rows.append((base, len(shapes) - 1, w, h, name, len(obj), ref_flip))
        print(f'{name:14s} captured  base tile {base:04x}  {w}x{h}  '
              f'{len(obj)} tiles  {len(polys)} strokes')

    # bulk-catalogued frames (tools/autotrace.py --catalog)
    mf = here / 'assets' / 'vectors' / 'auto_manifest.json'
    if mf.exists():
        known0 = {r[0] for r in sig_rows}
        nauto = 0
        for m in json.loads(mf.read_text()):
            if m['base'] in known0:
                continue
            path = here / 'assets' / 'vectors' / f"{m['name']}.vec"
            if not path.exists():
                continue
            polys = vec_strokes(path)
            p0 = len(all_polys)
            for poly in polys:
                all_polys.append((len(all_pts), len(poly)))
                all_pts.extend(poly)
            shapes.append((m['name'], p0, len(polys)))
            sig_rows.append((m['base'], len(shapes) - 1, m['w'], m['h'],
                             m['name'], m['ntiles'], m['refflip']))
            nauto += 1
        print(f'auto catalog: {nauto} signatures added')

    known = {r[0] for r in sig_rows}
    for lo, hi, name in ALIAS_RANGES:
        for obj in frames:
            base = min(t[2] for t in obj)
            if lo <= base <= hi and base not in known and len(obj) <= 8:
                w = max(t[0] for t in obj) + 16
                h = max(t[1] for t in obj) + 16
                aflip = 1 if sum(1 for t in obj if t[4]) * 2 > len(obj) else 0
                sig_rows.append((base, shape_idx[name], w, h, f'alias->{name}', len(obj), aflip))
                known.add(base)
    print(f'{len(sig_rows)} signatures ({len(shapes)} shapes)')

    out.append(f'static const short sb_vec_pts[][2] = {{')
    for x, y in all_pts:
        out.append(f' {{{int(round(x))},{int(round(y))}}},')
    out.append('};')
    out.append('static const struct { int first, npts; } sb_vec_polys[] = {')
    for first, n in all_polys:
        out.append(f' {{{first},{n}}},')
    out.append('};')
    out.append('static const struct { int poly0, npolys; } sb_vec_shapes[] = {')
    for name, p0, n in shapes:
        out.append(f' {{{p0},{n}}}, /* {name} */')
    out.append('};')
    out.append('/* base tile -> shape; sorted by tile for binary search */')
    out.append('static const struct { unsigned short tile; short shape, w, h, refflip, ntiles; } sb_vec_sigs[] = {')
    for base, shape, w, h, name, ntiles, rf in sorted(sig_rows):
        out.append(f' {{0x{base:04x},{shape},{w},{h},{rf},{ntiles}}}, /* {name} */')
    out.append('};')
    out.append(f'#define SB_NSIGS {len(sig_rows)}')

    (here / 'src' / 'sb_sprites.h').write_text('\n'.join(out) + '\n')
    print('src/sb_sprites.h written')


if __name__ == '__main__':
    main()
