//! PiTrex ARM32 Code Generator
//!
//! Target: Pi Zero (ARM1176JZF-S, ARMv6) inside a PiTrex cartridge.
//! Emits GNU ARM32 assembly (.s) linked against the PiTrex SDK.
//!
//! Pipeline:
//!   VPy AST (UnifiedModule)
//!     → generate_pitrex_asm()
//!     → game.s   (ARM32 ASM, not Thumb)
//!     → arm-none-eabi-as -march=armv6 -mfpu=vfp -mfloat-abi=hard game.s -o game.o
//!     → arm-none-eabi-gcc -march=armv6 -mfpu=vfp -mfloat-abi=hard -nostartfiles
//!         -L$PITREX_SDK/lib game.o -lbaremetal -lvectrexInterface -luspi -o game.elf
//!     → arm-none-eabi-objcopy -O binary game.elf game.img
//!     → copy game.img to SD card as kernel.img (standalone) or piZero1/<name>.img (loader)
//!
//! Key SDK functions used:
//!   vectrexinit(1), v_init(), v_setRefresh(50)
//!   v_WaitRecal(), v_readButtons(), v_readJoystick1Analog()
//!   v_directDraw32(x0, y0, x1, y1, brightness)
//!   v_setBrightness(brightness)
//!   v_printStringRaster(x, y, str, size, -7, '\0')
//!
//! Coordinate system:
//!   VPy: ±96 X, ±128 Y (signed bytes in .vec paths)
//!   PiTrex: ±16129 X, ±16129 Y (int32)
//!   Scale factor = 127 (matches rp2350 VIA T1=127: VPy×127 = same physical deflection)
//!
//! ARM32 vs Thumb2 differences:
//!   - No .thumb_func / .thumb directives (ARM mode by default)
//!   - No SDIV hardware instruction → bl __aeabi_idiv
//!   - PUSH/POP are aliases for STMFD/LDMFD (GAS accepts both)
//!   - All instructions are 32-bit, no 16-bit forms
//!   - Variable addresses: .bss labels (linker resolves, no hardcoded addresses)

pub mod functions;
pub mod expressions;
pub mod builtins;
pub mod assets;
pub mod analysis;
pub mod libvpy;

use vpy_parser::Module;
use crate::AssetInfo;

/// Coordinate scale factor: VPy unit → PiTrex unit
/// Scale factor: 127 (matches rp2350 T1=127 timer: VPy×127 = 127×127 = 16129 integration units)
pub const COORD_SCALE: i32 = 127;

/// Entry point: generate a complete ARM32 .s file for the PiTrex target.
pub fn generate_pitrex_asm(
    module: &Module,
    title: &str,
    assets: &[AssetInfo],
) -> Result<String, String> {
    let mut asm = String::new();

    // ── File header ──────────────────────────────────────────────────────────
    asm.push_str(&format!(
        "@ VPy — PiTrex target (ARM32 / ARMv6 / Pi Zero)\n\
         @ Game: {title}\n\
         @ Generated by vpy_codegen pitrex backend\n\
         @ Assemble: arm-none-eabi-as -march=armv6 -mfpu=vfp -mfloat-abi=hard game.s -o game.o\n\
         @ Link:     arm-none-eabi-gcc -march=armv6 -mfpu=vfp -mfloat-abi=hard -nostartfiles\n\
         @             -L$(PITREX_SDK)/lib game.o -lbaremetal -lvectrexInterface -luspi -o game.elf\n\
         @ Binary:   arm-none-eabi-objcopy -O binary game.elf game.img\n\n"
    ));

    // ── CPU / FPU directives ─────────────────────────────────────────────────
    asm.push_str(".arch armv6\n");
    asm.push_str(".fpu vfp\n");
    asm.push_str(".syntax unified\n\n");

    // ── External PiTrex SDK symbols ──────────────────────────────────────────
    asm.push_str("@ --- PiTrex SDK externals ---\n");
    for sym in &[
        "vectrexinit", "v_init", "v_setRefresh",
        "v_WaitRecal", "v_readButtons", "v_readJoystick1Analog",
        "v_directDraw32", "v_directMove32", "v_setBrightness", "v_setScale",
        "v_printString", "v_printStringRaster",
        "v_writePSG", "v_doSound",
        "currentJoy1X", "currentJoy1Y", "currentButtonState",
        "currentJoy2X", "currentJoy2Y",
        "commonHints",
        "__aeabi_idiv", "__aeabi_idivmod",
        "RPI_AuxUartInit", "RPI_AuxUartWrite",
        "bcm2835_st",
    ] {
        asm.push_str(&format!(".extern {sym}\n"));
    }
    asm.push('\n');

    // ── BSS section: all RAM variables ──────────────────────────────────────
    asm.push_str(".section .bss\n");
    asm.push_str(".align 2\n");
    let (var_addrs, bss_decls) = functions::allocate_globals_bss(module);
    asm.push_str(&bss_decls);
    // PiTrex beam tracker (current draw position in PiTrex coords)
    // NOTE: all other runtime vars (RAND_SEED, PSG_*, CAMERA_*, TEXT_SIZE etc.)
    // are allocated as .equ constants by allocate_globals_bss() above.
    asm.push_str("PITREX_CUR_X: .space 4\n");
    asm.push_str("PITREX_CUR_Y: .space 4\n");
    // PITREX_MOVE_X/Y: set only by MOVE() builtin, read by DRAW_LINE as offset.
    // Separate from PITREX_CUR_X/Y which tracks beam position inside DRAW_VECTOR.
    asm.push_str("PITREX_MOVE_X: .space 4\n");
    asm.push_str("PITREX_MOVE_Y: .space 4\n");
    asm.push_str("UART_TRACE_FRAMES_LEFT: .space 4\n");
    asm.push_str("UART_FRAME_NUM: .space 4\n");
    asm.push_str("FRAME_WORK_START: .space 4\n");    // µs timestamp after v_WaitRecal
    asm.push_str("SAMPLE_POS_START: .space 4\n");    // µs timestamp latched on first SAMPLE_POS call (0 = not started)
    asm.push_str("DRAW_REC_PEN_X: .space 4\n");      // DRAW_RECORDING chained running pen X (VPy units); PEN_Y must follow
    asm.push_str("DRAW_REC_PEN_Y: .space 4\n");      // running pen Y (consecutive after PEN_X)
    asm.push_str("CPU_PRINT_CTR: .space 4\n");       // countdown: print every 50 frames
    asm.push_str("_DV3D_BUF: .space 256\n");           // static buffer for pitrex_draw_vector_3d
    asm.push_str("_DV3D_TRIG: .space 8\n");            // sin/cos cache: sin_x, cos_x, sin_y, cos_y, sin_z, cos_z (1 byte each, +2 pad)
    asm.push('\n');

    // ── Read-only data: const array data + circle table ─────────────────────
    asm.push_str(".section .rodata\n");
    asm.push_str(".align 2\n");
    
    // Precomputed unit circle table (16 segments, 17 vertices for closed loop)
    // Each entry is (x, y) scaled by 1024 for fixed-point math
    // Used by draw_circle, draw_ellipse, and draw_arc to avoid runtime trig
    asm.push_str("@ Precomputed unit circle table: 16 segments × 2 coords (x,y) × 4 bytes = 136 bytes\n");
    asm.push_str(".global PITREX_CIRCLE_TABLE\n");
    asm.push_str("PITREX_CIRCLE_TABLE:\n");
    let circle_pts: [(i32, i32); 17] = [
        (1024, 0), (946, 392), (724, 724), (392, 946),
        (0, 1024), (-392, 946), (-724, 724), (-946, 392),
        (-1024, 0), (-946, -392), (-724, -724), (-392, -946),
        (0, -1024), (392, -946), (724, -724), (946, -392),
        (1024, 0),
    ];
    for (x, y) in circle_pts.iter() {
        asm.push_str(&format!("    .word {x}, {y}\n"));
    }
    asm.push_str("\n");
    
    asm.push_str(&functions::emit_const_array_data(module));
    asm.push('\n');

    // ── Text section: code ───────────────────────────────────────────────────
    asm.push_str(".section .text\n");
    asm.push_str(".align 2\n\n");

    // Builtin helper functions — tree-shaken: only the helpers whose VPy
    // builtin names appear in the AST (plus the always-on scaffolding set)
    // are emitted. See analysis.rs for the collection + dep-closure logic.
    let needed = analysis::collect_used_builtins(module);
    asm.push_str(&builtins::emit_builtins(&needed));

    // User-defined functions + game_main()
    asm.push_str(&functions::emit_functions(module, assets, &var_addrs)?);

    // Filter assets to only those used in code (like M6809 does)
    let used_assets = assets::filter_used_assets(assets, module);

    // Asset data (vector graphics, music event tables, SFX tables)
    asm.push_str(&assets::emit_pitrex_assets(&used_assets));

    Ok(asm)
}
