//! PiTrex ARM32 Code Generator
//!
//! Target: Pi Zero (ARM1176JZF-S, ARMv6) inside a PiTrex cartridge.
//! Emits GNU ARM32 assembly (.s) linked against the PiTrex SDK.
//!
//! Pipeline:
//!   VPy AST (UnifiedModule)
//!     → generate_pitrex_asm()
//!     → game.s   (ARM32 ASM, not Thumb)
//!     → arm-none-eabi-as -march=armv6 -mfpu=vfp -mfloat-abi=hard game.s -o game.o
//!     → arm-none-eabi-gcc -march=armv6 -mfpu=vfp -mfloat-abi=hard -nostartfiles
//!         -L$PITREX_SDK/lib game.o -lbaremetal -lvectrexInterface -luspi -o game.elf
//!     → arm-none-eabi-objcopy -O binary game.elf game.img
//!     → copy game.img to SD card as kernel.img (standalone) or piZero1/<name>.img (loader)
//!
//! Key SDK functions used:
//!   vectrexinit(1), v_init(), v_setRefresh(50)
//!   v_WaitRecal(), v_readButtons(), v_readJoystick1Analog()
//!   v_directDraw32(x0, y0, x1, y1, brightness)
//!   v_setBrightness(brightness)
//!   v_printStringRaster(x, y, str, size, -7, '\0')
//!
//! Coordinate system:
//!   VPy: ±96 X, ±128 Y (signed bytes in .vec paths)
//!   PiTrex: ±18000 X, ±24000 Y (int32)
//!   Scale factor: 180 (VPy 96 → 17280, VPy 128 → 23040, both within PiTrex range)
//!
//! ARM32 vs Thumb2 differences:
//!   - No .thumb_func / .thumb directives (ARM mode by default)
//!   - No SDIV hardware instruction → bl __aeabi_idiv
//!   - PUSH/POP are aliases for STMFD/LDMFD (GAS accepts both)
//!   - All instructions are 32-bit, no 16-bit forms
//!   - Variable addresses: .bss labels (linker resolves, no hardcoded addresses)

pub mod functions;
pub mod expressions;
pub mod builtins;
pub mod assets;

use vpy_parser::Module;
use crate::AssetInfo;

/// Coordinate scale factor: VPy unit → PiTrex unit
pub const COORD_SCALE: i32 = 180;

/// Entry point: generate a complete ARM32 .s file for the PiTrex target.
pub fn generate_pitrex_asm(
    module: &Module,
    title: &str,
    assets: &[AssetInfo],
) -> Result<String, String> {
    let mut asm = String::new();

    // ── File header ──────────────────────────────────────────────────────────
    asm.push_str(&format!(
        "@ VPy — PiTrex target (ARM32 / ARMv6 / Pi Zero)\n\
         @ Game: {title}\n\
         @ Generated by vpy_codegen pitrex backend\n\
         @ Assemble: arm-none-eabi-as -march=armv6 -mfpu=vfp -mfloat-abi=hard game.s -o game.o\n\
         @ Link:     arm-none-eabi-gcc -march=armv6 -mfpu=vfp -mfloat-abi=hard -nostartfiles\n\
         @             -L$(PITREX_SDK)/lib game.o -lbaremetal -lvectrexInterface -luspi -o game.elf\n\
         @ Binary:   arm-none-eabi-objcopy -O binary game.elf game.img\n\n"
    ));

    // ── CPU / FPU directives ─────────────────────────────────────────────────
    asm.push_str(".arch armv6\n");
    asm.push_str(".fpu vfp\n");
    asm.push_str(".syntax unified\n\n");

    // ── External PiTrex SDK symbols ──────────────────────────────────────────
    asm.push_str("@ --- PiTrex SDK externals ---\n");
    for sym in &[
        "vectrexinit", "v_init", "v_setRefresh",
        "v_WaitRecal", "v_readButtons", "v_readJoystick1Analog",
        "v_directDraw32", "v_setBrightness",
        "v_printStringRaster",
        "currentJoy1X", "currentJoy1Y", "currentButtonState",
        "__aeabi_idiv",
    ] {
        asm.push_str(&format!(".extern {sym}\n"));
    }
    asm.push('\n');

    // ── BSS section: all RAM variables ──────────────────────────────────────
    asm.push_str(".section .bss\n");
    asm.push_str(".align 2\n");
    let (var_addrs, bss_decls) = functions::allocate_globals_bss(module);
    asm.push_str(&bss_decls);
    // PiTrex beam tracker (current draw position in PiTrex coords)
    asm.push_str("PITREX_CUR_X: .space 4\n");
    asm.push_str("PITREX_CUR_Y: .space 4\n");
    asm.push('\n');

    // ── Read-only data: const array data ────────────────────────────────────
    asm.push_str(".section .rodata\n");
    asm.push_str(".align 2\n");
    asm.push_str(&functions::emit_const_array_data(module));
    asm.push('\n');

    // ── Text section: code ───────────────────────────────────────────────────
    asm.push_str(".section .text\n");
    asm.push_str(".align 2\n\n");

    // Builtin helper functions (draw_vector_ex, math, joystick, etc.)
    asm.push_str(&builtins::emit_builtins());

    // User-defined functions + game_main()
    asm.push_str(&functions::emit_functions(module, assets, &var_addrs)?);

    // Asset data (music event tables, SFX tables)
    asm.push_str(&assets::emit_pitrex_assets(assets));

    Ok(asm)
}
